// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Difficulty Scaler presets (F09 SS5.1): named modifier sets applied at resolution time to the
// enemy side; stat blocks are never mutated (baseHpMax stays pristine on each Combatant).

import type { DifficultySetting } from './types.ts'

export const DIFFICULTY_PRESETS: DifficultySetting[] = [
  { name: 'Story', hpMult: 0.75, toHit: -2, dc: -1, dmgMult: 0.8 },
  { name: 'Easy', hpMult: 0.9, toHit: -1, dc: 0, dmgMult: 0.9 },
  { name: 'Standard', hpMult: 1, toHit: 0, dc: 0, dmgMult: 1 },
  { name: 'Hard', hpMult: 1.3, toHit: 1, dc: 1, dmgMult: 1.15 },
  { name: 'Deadly', hpMult: 1.5, toHit: 2, dc: 2, dmgMult: 1.3 },
]

export const STANDARD_DIFFICULTY: DifficultySetting = DIFFICULTY_PRESETS[2]

/** Effective max HP for an enemy-side combatant under a setting (min 1, rounded). */
export function scaledHpMax(baseHpMax: number, setting: DifficultySetting): number {
  return Math.max(1, Math.round(baseHpMax * setting.hpMult))
}
