// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Turn Manager + action resolution (F09 SS3, SS4.1 Phase 1). Every public function is a pure
// reducer: it deep-clones the incoming state, mutates the clone, and returns it with the events
// the resolution produced. Illegal actions throw CombatError BEFORE any rng call, so a rejected
// action never perturbs the roll sequence and replays stay byte-identical.

import type { Rng } from '../play/rng.ts'
import { GRID_SIZE } from '../state/types.ts'
import { applyDamage, checkCombatEnd, conscious, resolveAttack } from './attack.ts'
import { rollD20 } from './dice.ts'
import { scaledHpMax, STANDARD_DIFFICULTY } from './difficulty.ts'
import { blockedCells, cellKey, chebyshev, findPath, gridBounds, inBounds, lineOfSight } from './grid.ts'
import { resolveCast, spellAffects } from './spells.ts'
import { CombatError } from './types.ts'
import type {
  AttackSpec, Combatant, CombatAction, CombatantSetup, CombatEngineState, CombatEvent,
  CombatSide, ConditionName, DifficultySetting, EngineResult, SaveModifiers, SpellSpec,
} from './types.ts'

export interface CombatSetup {
  combatants: CombatantSetup[]
  obstacles: [number, number][]
  difficulty?: DifficultySetting
  /** Grid dimensions in squares; both default to GRID_SIZE when omitted. */
  gridWidth?: number
  gridHeight?: number
}

/** State is plain JSON data, so a JSON round-trip is a safe, runtime-portable deep clone. */
function cloneState(state: CombatEngineState): CombatEngineState {
  return JSON.parse(JSON.stringify(state)) as CombatEngineState
}

export function activeCombatant(state: CombatEngineState): Combatant {
  const entry = state.initiative[state.turnIndex]
  const combatant = state.combatants.find((c) => c.id === entry.id)
  if (!combatant) throw new CombatError('Active combatant missing')
  return combatant
}

function beginTurn(state: CombatEngineState, events: CombatEvent[]): void {
  const active = activeCombatant(state)
  state.economy = { action: true, bonus: true, move: active.speed }
  active.reactionAvailable = true
  active.dodging = false
  events.push({ kind: 'turn_start', id: active.id, name: active.name })
}

function advanceTurn(state: CombatEngineState, events: CombatEvent[]): void {
  const active = activeCombatant(state)
  active.disengaged = false
  events.push({ kind: 'turn_end', id: active.id })
  if (state.status !== 'active') return
  // End-of-combat check keeps one conscious combatant per side while active, so this terminates.
  for (;;) {
    state.turnIndex++
    if (state.turnIndex >= state.initiative.length) {
      state.turnIndex = 0
      state.round++
      events.push({ kind: 'round_start', round: state.round })
    }
    const next = state.combatants.find((c) => c.id === state.initiative[state.turnIndex].id)
    if (!next) throw new CombatError('Initiative entry missing')
    if (next.dead) {
      events.push({ kind: 'turn_skip', id: next.id, name: next.name, reason: 'dead' })
      continue
    }
    if (next.conditions.includes('unconscious')) {
      events.push({ kind: 'turn_skip', id: next.id, name: next.name, reason: 'unconscious' })
      continue
    }
    beginTurn(state, events)
    return
  }
}

export function createCombat(setup: CombatSetup, rng: Rng): EngineResult {
  const difficulty = setup.difficulty ?? STANDARD_DIFFICULTY
  const gridWidth = setup.gridWidth ?? GRID_SIZE
  const gridHeight = setup.gridHeight ?? GRID_SIZE
  const bounds = { width: gridWidth, height: gridHeight }
  const seen = new Set<string>()
  const occupied = new Set<string>()
  const obstacleSet = new Set(setup.obstacles.map(([x, y]) => cellKey(x, y)))
  for (const c of setup.combatants) {
    if (seen.has(c.id)) throw new CombatError(`Duplicate combatant id: ${c.id}`)
    seen.add(c.id)
    if (!inBounds(c.x, c.y, bounds)) throw new CombatError(`${c.name} placed outside the map`)
    if (obstacleSet.has(cellKey(c.x, c.y))) throw new CombatError(`${c.name} placed on an obstacle`)
    if (occupied.has(cellKey(c.x, c.y))) throw new CombatError(`${c.name} placed on an occupied square`)
    occupied.add(cellKey(c.x, c.y))
    if (c.hpMax < 1) throw new CombatError(`${c.name} needs at least 1 HP`)
    if (c.attacks.length === 0) throw new CombatError(`${c.name} has no attacks`)
  }
  if (!setup.combatants.some((c) => c.side === 'party') || !setup.combatants.some((c) => c.side === 'enemy')) {
    throw new CombatError('Both sides need at least one combatant')
  }

  const combatants: Combatant[] = setup.combatants.map((c) => {
    const hpMax = c.side === 'enemy' ? scaledHpMax(c.hpMax, difficulty) : c.hpMax
    return {
      id: c.id,
      name: c.name,
      side: c.side,
      kind: c.kind,
      refId: c.refId,
      imageUrl: c.imageUrl,
      x: c.x,
      y: c.y,
      hp: { current: hpMax, max: hpMax, temp: 0 },
      baseHpMax: c.hpMax,
      ac: c.ac,
      speed: c.speed,
      dexMod: c.dexMod,
      saves: { str: 0, dex: c.dexMod, con: 0, int: 0, wis: 0, cha: 0, ...c.saves },
      attacks: c.attacks,
      spells: c.spells ?? [],
      conditions: [],
      dead: false,
      dodging: false,
      disengaged: false,
      reactionAvailable: true,
      auto: c.auto ?? false,
    }
  })

  // Initiative rolled in setup order (fixed rng order), then sorted: total desc, DEX desc,
  // setup order as the final stable tiebreak.
  const rolls = combatants.map((c, index) => {
    const { dice, used } = rollD20(rng, 'none')
    const total = used + c.dexMod
    return {
      id: c.id,
      name: c.name,
      index,
      dexMod: c.dexMod,
      roll: { dice, used, mods: [{ label: 'DEX', value: c.dexMod }], total, advantage: 'none' as const },
    }
  })
  const ordered = [...rolls].sort(
    (a, b) => b.roll.total - a.roll.total || b.dexMod - a.dexMod || a.index - b.index,
  )

  const state: CombatEngineState = {
    obstacles: setup.obstacles,
    combatants,
    initiative: ordered.map((r) => ({ id: r.id, total: r.roll.total })),
    round: 1,
    turnIndex: 0,
    economy: { action: true, bonus: true, move: 0 },
    difficulty,
    gridWidth,
    gridHeight,
    status: 'active',
    winner: null,
  }

  const events: CombatEvent[] = [
    { kind: 'combat_start', difficulty: difficulty.name },
    { kind: 'initiative', order: ordered.map((r) => ({ id: r.id, name: r.name, roll: r.roll })) },
    { kind: 'round_start', round: 1 },
  ]
  beginTurn(state, events)
  return { state, events }
}

/** Opportunity attacks triggered by the mover leaving `from` for `to` (F09 SS4.1). */
function opportunityAttacks(
  state: CombatEngineState,
  mover: Combatant,
  from: [number, number],
  to: [number, number],
  rng: Rng,
  events: CombatEvent[],
): void {
  if (mover.disengaged) return
  for (const enemy of state.combatants) {
    if (enemy.side === mover.side || !conscious(enemy) || !enemy.reactionAvailable) continue
    const melee = enemy.attacks.find((a) => a.kind === 'melee')
    if (!melee) continue
    const fromPos = { x: from[0], y: from[1] }
    const toPos = { x: to[0], y: to[1] }
    if (chebyshev(fromPos, enemy) === 1 && chebyshev(toPos, enemy) > 1) {
      enemy.reactionAvailable = false
      resolveAttack(state, enemy, mover, melee, true, rng, events)
      if (mover.hp.current === 0) return
    }
  }
}

function resolveMove(state: CombatEngineState, to: [number, number], rng: Rng, events: CombatEvent[]): void {
  const active = activeCombatant(state)
  const stepCost = active.conditions.includes('prone') ? 2 : 1
  const blocked = blockedCells(state.obstacles, state.combatants, active.id)
  const path = findPath([active.x, active.y], to, blocked, gridBounds(state))
  if (!path || path.length === 0) throw new CombatError('No path to that square')
  if (path.length * stepCost > state.economy.move) throw new CombatError('Not enough movement')

  // Walk step by step so opportunity attacks land in chronological order; each contiguous run
  // of unopposed steps is flushed as one move event before the interrupting attack events.
  let segment: [number, number][] = []
  const flush = () => {
    if (segment.length === 0) return
    events.push({
      kind: 'move',
      id: active.id,
      path: segment,
      cost: segment.length * stepCost,
      remaining: state.economy.move,
    })
    segment = []
  }
  for (const step of path) {
    const from: [number, number] = [active.x, active.y]
    const before = events.length
    opportunityAttacks(state, active, from, step, rng, events)
    if (events.length > before) {
      const interrupting = events.splice(before)
      flush()
      events.push(...interrupting)
    }
    if (active.hp.current === 0 || state.status !== 'active') break
    active.x = step[0]
    active.y = step[1]
    state.economy.move -= stepCost
    segment.push(step)
  }
  flush()
  if (state.status === 'active' && !conscious(active)) advanceTurn(state, events)
}

function resolveAttackAction(
  state: CombatEngineState,
  targetId: string,
  attackIndex: number,
  rng: Rng,
  events: CombatEvent[],
): void {
  const active = activeCombatant(state)
  if (!state.economy.action) throw new CombatError('No action left')
  const target = state.combatants.find((c) => c.id === targetId)
  if (!target || target.id === active.id) throw new CombatError('Invalid target')
  if (target.dead) throw new CombatError(`${target.name} is already dead`)
  const attack = active.attacks[attackIndex] as AttackSpec | undefined
  if (!attack) throw new CombatError('Unknown attack')
  if (chebyshev(active, target) > (attack.longRange ?? attack.range)) throw new CombatError('Target out of range')
  if (attack.kind === 'ranged') {
    const obstacleSet = new Set(state.obstacles.map(([x, y]) => cellKey(x, y)))
    if (!lineOfSight([active.x, active.y], [target.x, target.y], obstacleSet)) {
      throw new CombatError('No line of sight')
    }
  }
  state.economy.action = false
  resolveAttack(state, active, target, attack, false, rng, events)
}

function resolveCastAction(
  state: CombatEngineState,
  spellIndex: number,
  targetId: string | undefined,
  aim: [number, number] | undefined,
  rng: Rng,
  events: CombatEvent[],
): void {
  const active = activeCombatant(state)
  const spell = active.spells[spellIndex] as SpellSpec | undefined
  if (!spell) throw new CombatError('Unknown spell')
  const budget = spell.cost === 'bonus' ? state.economy.bonus : state.economy.action
  if (!budget) throw new CombatError(spell.cost === 'bonus' ? 'No bonus action left' : 'No action left')

  const obstacleSet = new Set(state.obstacles.map(([x, y]) => cellKey(x, y)))
  if (spell.area.shape === 'single') {
    const target = state.combatants.find((c) => c.id === targetId)
    if (!target || target.dead) throw new CombatError('Invalid target')
    if (!sideAllowed(spell, active, target)) throw new CombatError('Not a legal target for this spell')
    if (chebyshev(active, target) > spell.range) throw new CombatError('Target out of range')
    if (!lineOfSight([active.x, active.y], [target.x, target.y], obstacleSet)) throw new CombatError('No line of sight')
  } else {
    if (!aim) throw new CombatError('No aim point')
    if (!inBounds(aim[0], aim[1], gridBounds(state))) throw new CombatError('Aim outside the map')
    // range 0 = self-origin (cone/line burst from the caster); otherwise the aim cell must be in range.
    if (spell.range > 0 && chebyshev(active, { x: aim[0], y: aim[1] }) > spell.range) {
      throw new CombatError('Aim point out of range')
    }
  }

  if (spell.cost === 'bonus') state.economy.bonus = false
  else state.economy.action = false
  resolveCast(state, active, spell, { targetId, cell: aim }, rng, events)
}

function sideAllowed(spell: SpellSpec, caster: Combatant, target: Combatant): boolean {
  const affects = spellAffects(spell)
  if (affects === 'any') return true
  const ally = target.side === caster.side
  return affects === 'allies' ? ally : !ally
}

export function resolveAction(prev: CombatEngineState, action: CombatAction, rng: Rng): EngineResult {
  if (prev.status !== 'active') throw new CombatError('Combat is over')
  const state = cloneState(prev)
  const events: CombatEvent[] = []
  const active = activeCombatant(state)

  switch (action.type) {
    case 'move':
      resolveMove(state, action.to, rng, events)
      break
    case 'attack':
      resolveAttackAction(state, action.targetId, action.attackIndex, rng, events)
      break
    case 'cast':
      resolveCastAction(state, action.spellIndex, action.targetId, action.aim, rng, events)
      break
    case 'dodge':
      if (!state.economy.action) throw new CombatError('No action left')
      state.economy.action = false
      active.dodging = true
      events.push({ kind: 'action', id: active.id, action: 'dodge' })
      break
    case 'dash':
      if (!state.economy.action) throw new CombatError('No action left')
      state.economy.action = false
      state.economy.move += active.speed
      events.push({ kind: 'action', id: active.id, action: 'dash' })
      break
    case 'disengage':
      if (!state.economy.action) throw new CombatError('No action left')
      state.economy.action = false
      active.disengaged = true
      events.push({ kind: 'action', id: active.id, action: 'disengage' })
      break
    case 'stand_up': {
      if (!active.conditions.includes('prone')) throw new CombatError('Not prone')
      const cost = Math.ceil(active.speed / 2)
      if (state.economy.move < cost) throw new CombatError('Not enough movement to stand')
      state.economy.move -= cost
      active.conditions = active.conditions.filter((c) => c !== 'prone')
      events.push({ kind: 'action', id: active.id, action: 'stand_up' })
      break
    }
    case 'end_turn':
      advanceTurn(state, events)
      break
  }
  return { state, events }
}

/** Live stat editing (Lab sidebar). Edited hp.max becomes the new pre-difficulty base. */
export interface CombatantPatch {
  hpCurrent?: number
  hpMax?: number
  hpTemp?: number
  ac?: number
  speed?: number
  x?: number
  y?: number
  side?: CombatSide
  attacks?: AttackSpec[]
  spells?: SpellSpec[]
  saves?: Partial<SaveModifiers>
  conditions?: ConditionName[]
  auto?: boolean
}

export function editCombatant(prev: CombatEngineState, id: string, patch: CombatantPatch): EngineResult {
  const state = cloneState(prev)
  const events: CombatEvent[] = []
  const c = state.combatants.find((x) => x.id === id)
  if (!c) throw new CombatError('Unknown combatant')

  if (patch.x !== undefined || patch.y !== undefined) {
    const nx = patch.x ?? c.x
    const ny = patch.y ?? c.y
    const blocked = blockedCells(state.obstacles, state.combatants, c.id)
    if (!inBounds(nx, ny, gridBounds(state)) || blocked.has(cellKey(nx, ny))) throw new CombatError('Square not free')
    c.x = nx
    c.y = ny
  }
  if (patch.hpMax !== undefined) {
    c.hp.max = Math.max(1, Math.round(patch.hpMax))
    c.baseHpMax = c.hp.max
    c.hp.current = Math.min(c.hp.current, c.hp.max)
  }
  if (patch.hpCurrent !== undefined) c.hp.current = Math.max(0, Math.min(Math.round(patch.hpCurrent), c.hp.max))
  if (patch.hpTemp !== undefined) c.hp.temp = Math.max(0, Math.round(patch.hpTemp))
  if (patch.ac !== undefined) c.ac = patch.ac
  if (patch.speed !== undefined) c.speed = Math.max(0, patch.speed)
  if (patch.side !== undefined) c.side = patch.side
  if (patch.attacks !== undefined && patch.attacks.length > 0) c.attacks = patch.attacks
  if (patch.spells !== undefined) c.spells = patch.spells
  if (patch.saves !== undefined) c.saves = { ...c.saves, ...patch.saves }
  if (patch.conditions !== undefined) c.conditions = patch.conditions
  if (patch.auto !== undefined) c.auto = patch.auto

  // Reconcile down-state with the edited HP (a lab revive/kill switch, not an SRD rule).
  if (c.hp.current > 0) {
    c.dead = false
    c.conditions = c.conditions.filter((x) => x !== 'unconscious')
  } else if (!c.dead && !c.conditions.includes('unconscious')) {
    if (c.kind === 'npc') c.dead = true
    else c.conditions.push('unconscious')
  }

  events.push({ kind: 'edit', id: c.id, note: `${c.name} edited: ${Object.keys(patch).join(', ')}` })
  checkCombatEnd(state, events)
  return { state, events }
}

/** Mid-combat difficulty change (F09 SS5.1): enemy HP rescales proportionally, from next resolution. */
export function setDifficulty(prev: CombatEngineState, setting: DifficultySetting): EngineResult {
  const state = cloneState(prev)
  const events: CombatEvent[] = []
  state.difficulty = setting
  for (const c of state.combatants) {
    if (c.side !== 'enemy') continue
    const newMax = scaledHpMax(c.baseHpMax, setting)
    if (newMax === c.hp.max) continue
    const rescaled = Math.round((c.hp.current * newMax) / c.hp.max)
    c.hp.current = c.hp.current > 0 ? Math.max(1, Math.min(newMax, rescaled)) : 0
    c.hp.max = newMax
  }
  events.push({ kind: 'difficulty', name: setting.name, note: `Difficulty set to ${setting.name}` })
  return { state, events }
}

export { applyDamage }
