// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Minion heuristic (F09 SS6.3): scripted target-nearest/lowest-HP policy, zero LLM calls.
// chooseAutoAction returns ONE next action for the active combatant; runAutoTurn loops it
// through resolveAction until the turn ends. Fully deterministic: ties break by combatant
// array order, so the same state always yields the same action.

import type { Rng } from '../play/rng.ts'
import { conscious } from './attack.ts'
import { expectedDamage } from './dice.ts'
import { activeCombatant, resolveAction } from './engine.ts'
import { blockedCells, cellKey, chebyshev, findPath, gridBounds, inBounds, lineOfSight } from './grid.ts'
import type { Cell, GridBounds } from './grid.ts'
import type { Combatant, CombatAction, CombatEngineState, CombatEvent, EngineResult } from './types.ts'

/** Shortest path to any free cell adjacent to `target`; [] when already adjacent. */
function pathToAdjacent(active: Combatant, target: Combatant, blocked: Set<string>, bounds: GridBounds): Cell[] | null {
  if (chebyshev(active, target) === 1) return []
  let best: Cell[] | null = null
  for (let dy = -1; dy <= 1; dy++) {
    for (let dx = -1; dx <= 1; dx++) {
      if (dx === 0 && dy === 0) continue
      const cell: Cell = [target.x + dx, target.y + dy]
      if (!inBounds(cell[0], cell[1], bounds) || blocked.has(cellKey(cell[0], cell[1]))) continue
      const path = findPath([active.x, active.y], cell, blocked, bounds)
      if (path && (best === null || path.length < best.length)) best = path
    }
  }
  return best
}

/** Furthest affordable step toward the target, stopping early once a ranged shot lines up. */
function moveDestination(
  state: CombatEngineState,
  active: Combatant,
  target: Combatant,
  obstacleSet: Set<string>,
): Cell | null {
  const blocked = blockedCells(state.obstacles, state.combatants, active.id)
  const path = pathToAdjacent(active, target, blocked, gridBounds(state))
  if (!path || path.length === 0) return null
  const steps = path.slice(0, state.economy.move)
  if (steps.length === 0) return null
  const ranged = active.attacks
    .filter((a) => a.kind === 'ranged')
    .sort((a, b) => expectedDamage(b.damage) - expectedDamage(a.damage))[0]
  if (ranged) {
    for (const cell of steps) {
      if (
        chebyshev({ x: cell[0], y: cell[1] }, target) <= ranged.range &&
        lineOfSight(cell, [target.x, target.y], obstacleSet)
      ) {
        return cell
      }
    }
  }
  return steps[steps.length - 1]
}

export function chooseAutoAction(state: CombatEngineState): CombatAction {
  if (state.status !== 'active') return { type: 'end_turn' }
  const active = activeCombatant(state)
  const order = new Map(state.combatants.map((c, i) => [c.id, i]))
  const enemies = state.combatants.filter((c) => c.side !== active.side && conscious(c))
  if (enemies.length === 0) return { type: 'end_turn' }

  if (active.conditions.includes('prone')) {
    if (state.economy.move >= Math.ceil(active.speed / 2)) return { type: 'stand_up' }
    return { type: 'end_turn' }
  }

  const target = [...enemies].sort(
    (a, b) =>
      chebyshev(active, a) - chebyshev(active, b) ||
      a.hp.current - b.hp.current ||
      (order.get(a.id) as number) - (order.get(b.id) as number),
  )[0]

  const obstacleSet = new Set(state.obstacles.map(([x, y]) => cellKey(x, y)))
  if (state.economy.action) {
    const usable = active.attacks
      .map((attack, index) => ({ attack, index }))
      .filter(
        ({ attack }) =>
          chebyshev(active, target) <= attack.range &&
          (attack.kind === 'melee' ||
            lineOfSight([active.x, active.y], [target.x, target.y], obstacleSet)),
      )
      .sort((a, b) => expectedDamage(b.attack.damage) - expectedDamage(a.attack.damage) || a.index - b.index)
    if (usable.length > 0) {
      return { type: 'attack', targetId: target.id, attackIndex: usable[0].index }
    }
  }

  // Hold position once any attack reaches from here - archers keep their distance instead of
  // drifting into melee after shooting.
  const canHitFromHere = active.attacks.some(
    (a) =>
      chebyshev(active, target) <= a.range &&
      (a.kind === 'melee' || lineOfSight([active.x, active.y], [target.x, target.y], obstacleSet)),
  )
  if (!canHitFromHere && state.economy.move > 0) {
    const dest = moveDestination(state, active, target, obstacleSet)
    if (dest) return { type: 'move', to: dest }
  }
  // Out of reach with movement spent: convert the action into more movement.
  if (state.economy.action) return { type: 'dash' }
  return { type: 'end_turn' }
}

/** Cap well above any legal action count per turn (stand + dash + moves + attack + end). */
const AUTO_TURN_CAP = 24

/** Plays the active combatant's whole turn with the heuristic; stops when the turn passes on. */
export function runAutoTurn(prev: CombatEngineState, rng: Rng): EngineResult {
  let state = prev
  const events: CombatEvent[] = []
  const turnOwner = activeCombatant(state).id
  for (let i = 0; i < AUTO_TURN_CAP; i++) {
    if (state.status !== 'active' || activeCombatant(state).id !== turnOwner) break
    const action = chooseAutoAction(state)
    const result = resolveAction(state, action, rng)
    state = result.state
    events.push(...result.events)
    if (action.type === 'end_turn') break
  }
  return { state, events }
}
