// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Read-only queries the UI asks before committing an action. These mirror the engine's own
// trigger logic (engine.ts opportunityAttacks) so previews can never disagree with resolution.

import { conscious } from './attack.ts'
import { chebyshev } from './grid.ts'
import type { Cell } from './grid.ts'
import { CombatError } from './types.ts'
import type { CombatEngineState } from './types.ts'

/**
 * Which enemies would get an opportunity attack if `moverId` walked `path` (each spends its
 * one reaction, so each appears at most once). Ignores mid-path damage outcomes - it predicts
 * triggers, not results.
 */
export function predictOpportunityAttacks(
  state: CombatEngineState,
  moverId: string,
  path: Cell[],
): { id: string; name: string }[] {
  const mover = state.combatants.find((c) => c.id === moverId)
  if (!mover) throw new CombatError('Unknown combatant')
  if (mover.disengaged || path.length === 0) return []
  const reactors: { id: string; name: string }[] = []
  const spent = new Set<string>()
  let pos = { x: mover.x, y: mover.y }
  for (const [sx, sy] of path) {
    const step = { x: sx, y: sy }
    for (const enemy of state.combatants) {
      if (enemy.side === mover.side || !conscious(enemy) || !enemy.reactionAvailable || spent.has(enemy.id)) continue
      if (!enemy.attacks.some((a) => a.kind === 'melee')) continue
      if (chebyshev(pos, enemy) === 1 && chebyshev(step, enemy) > 1) {
        spent.add(enemy.id)
        reactors.push({ id: enemy.id, name: enemy.name })
      }
    }
    pos = step
  }
  return reactors
}
