// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Spell resolution (F09 SS4.1): attack-roll, saving-throw (with half-on-save), and healing
// spells, single-target or over an AoE template rasterized to tiles. Pure and deterministic;
// the same rng discipline as attack.ts so previews (dry runs) and resolution never disagree.

import type { Rng } from '../play/rng.ts'
import { applyDamage, applyHeal, conscious } from './attack.ts'
import { rollD20, rollDiceExpr } from './dice.ts'
import { cellKey, DEFAULT_BOUNDS, gridBounds, inBounds } from './grid.ts'
import type { Cell, GridBounds } from './grid.ts'
import type {
  Combatant, CombatEngineState, CombatEvent, RollBreakdown, SpellArea, SpellSpec,
} from './types.ts'

/** Default legal-target side for a spell: heals allies, everything else hits enemies. */
export function spellAffects(spell: SpellSpec): 'enemies' | 'allies' | 'any' {
  return spell.affects ?? (spell.effect === 'heal' ? 'allies' : 'enemies')
}

function sideMatches(affects: 'enemies' | 'allies' | 'any', caster: Combatant, other: Combatant): boolean {
  if (affects === 'any') return true
  const ally = other.side === caster.side
  return affects === 'allies' ? ally : !ally
}

/**
 * Cells covered by a spell's template. `single` returns just the aim cell. circle/cube are
 * placed on the aim cell; cone/line project from the caster toward it. Continuous geometry so
 * the shape reads naturally on the grid; every cell is clamped in-bounds.
 */
export function spellArea(area: SpellArea, caster: Cell, aim: Cell, bounds: GridBounds = DEFAULT_BOUNDS): Cell[] {
  if (area.shape === 'single') return inBounds(aim[0], aim[1], bounds) ? [aim] : []

  const cells: Cell[] = []
  const push = (x: number, y: number) => {
    if (inBounds(x, y, bounds)) cells.push([x, y])
  }

  if (area.shape === 'circle') {
    const r = area.radius
    for (let dy = -r; dy <= r; dy++) {
      for (let dx = -r; dx <= r; dx++) {
        if (Math.hypot(dx, dy) <= r + 0.001) push(aim[0] + dx, aim[1] + dy)
      }
    }
    return cells
  }

  if (area.shape === 'cube') {
    const half = Math.floor(area.size / 2)
    for (let dy = -half; dy <= half; dy++) {
      for (let dx = -half; dx <= half; dx++) push(aim[0] + dx, aim[1] + dy)
    }
    return cells
  }

  // cone/line: axis = caster -> aim. Degenerate aim (== caster) yields nothing.
  const vx = aim[0] - caster[0]
  const vy = aim[1] - caster[1]
  const mag = Math.hypot(vx, vy)
  if (mag === 0) return []
  const ux = vx / mag
  const uy = vy / mag
  const length = area.shape === 'cone' ? area.length : area.length

  for (let dy = -length; dy <= length; dy++) {
    for (let dx = -length; dx <= length; dx++) {
      if (dx === 0 && dy === 0) continue
      const along = dx * ux + dy * uy
      if (along <= 0 || along > length + 0.001) continue
      const perp = Math.abs(dx * uy - dy * ux)
      // line: 1-wide corridor. cone: half-width grows to ~length/2 at the far end (5e cone).
      const maxPerp = area.shape === 'line' ? 0.5 : 0.5 * along + 0.5
      if (perp <= maxPerp) push(caster[0] + dx, caster[1] + dy)
    }
  }
  return cells
}

/** Living combatants a cast would affect (side-filtered), given a single target or an aim cell. */
export function spellTargets(
  state: CombatEngineState,
  caster: Combatant,
  spell: SpellSpec,
  aim: { targetId?: string; cell?: Cell },
): Combatant[] {
  const affects = spellAffects(spell)
  if (spell.area.shape === 'single') {
    const target = state.combatants.find((c) => c.id === aim.targetId)
    if (!target || target.dead || !sideMatches(affects, caster, target)) return []
    return [target]
  }
  const cell = aim.cell
  if (!cell) return []
  const covered = new Set(spellArea(spell.area, [caster.x, caster.y], cell, gridBounds(state)).map(([x, y]) => cellKey(x, y)))
  return state.combatants.filter(
    (c) => !c.dead && sideMatches(affects, caster, c) && covered.has(cellKey(c.x, c.y)),
  )
}

/** Effective damage number for a caster (enemy side takes the difficulty dmg multiplier). */
function scaledDamage(state: CombatEngineState, caster: Combatant, raw: number): number {
  const mult = caster.side === 'enemy' ? state.difficulty.dmgMult : 1
  return Math.max(0, Math.round(raw * mult))
}

function resolveSpellAttack(
  state: CombatEngineState,
  caster: Combatant,
  target: Combatant,
  spell: SpellSpec,
  rng: Rng,
  events: CombatEvent[],
): void {
  const { dice, used } = rollD20(rng, 'none')
  const mods: { label: string; value: number }[] = [{ label: 'spell attack', value: spell.toHit ?? 0 }]
  if (caster.side === 'enemy' && state.difficulty.toHit !== 0) {
    mods.push({ label: `difficulty (${state.difficulty.name})`, value: state.difficulty.toHit })
  }
  const total = used + mods.reduce((a, m) => a + m.value, 0)
  const roll: RollBreakdown = { dice, used, mods, total, advantage: 'none' }
  let outcome: 'crit' | 'hit' | 'miss'
  if (used === 1) outcome = 'miss'
  else if (used === 20) outcome = 'crit'
  else outcome = total >= target.ac ? 'hit' : 'miss'

  let damage = null as null | { rolls: number[]; sides: number; bonus: number; mult: number; total: number }
  if (outcome !== 'miss') {
    const extraDice = outcome === 'crit' ? spell.amount.count : 0
    const { rolls, sum } = rollDiceExpr(rng, spell.amount, extraDice)
    const mult = caster.side === 'enemy' ? state.difficulty.dmgMult : 1
    damage = {
      rolls, sides: spell.amount.sides, bonus: spell.amount.bonus, mult,
      total: scaledDamage(state, caster, sum + spell.amount.bonus),
    }
  }
  events.push({
    kind: 'attack', attackerId: caster.id, targetId: target.id, attackName: spell.name,
    reaction: false, roll, targetAc: target.ac, outcome, damage,
  })
  if (damage && damage.total > 0) applyDamage(state, target, damage.total, events)
}

function resolveSpellSave(
  state: CombatEngineState,
  caster: Combatant,
  target: Combatant,
  spell: SpellSpec,
  rng: Rng,
  events: CombatEvent[],
): void {
  const ability = spell.saveAbility ?? 'dex'
  const dc = (spell.saveDc ?? 10) + (caster.side === 'enemy' ? state.difficulty.dc : 0)
  const { dice, used } = rollD20(rng, 'none')
  const mod = target.saves[ability] ?? 0
  const total = used + mod
  const success = used !== 1 && (used === 20 || total >= dc)
  const roll: RollBreakdown = {
    dice, used, mods: [{ label: `${ability.toUpperCase()} save`, value: mod }], total, advantage: 'none',
  }
  events.push({ kind: 'save', id: target.id, name: target.name, ability, roll, dc, success })

  const { sum } = rollDiceExpr(rng, spell.amount)
  const full = scaledDamage(state, caster, sum + spell.amount.bonus)
  let dealt = full
  if (success) dealt = spell.onSave === 'half' ? Math.floor(full / 2) : 0
  if (dealt > 0) applyDamage(state, target, dealt, events)
}

export function resolveCast(
  state: CombatEngineState,
  caster: Combatant,
  spell: SpellSpec,
  aim: { targetId?: string; cell?: Cell },
  rng: Rng,
  events: CombatEvent[],
): void {
  const targets = spellTargets(state, caster, spell, aim)
  events.push({
    kind: 'spell_cast',
    casterId: caster.id,
    casterName: caster.name,
    spellName: spell.name,
    effect: spell.effect,
    area: spell.area,
    targets: targets.map((t) => ({ id: t.id, name: t.name })),
  })
  // Resolve in initiative-array order for deterministic rng consumption across the AoE.
  const ordered = state.combatants.filter((c) => targets.some((t) => t.id === c.id))
  for (const target of ordered) {
    if (spell.effect === 'attack') resolveSpellAttack(state, caster, target, spell, rng, events)
    else if (spell.effect === 'save') resolveSpellSave(state, caster, target, spell, rng, events)
    else applyHeal(target, rollDiceExpr(rng, spell.amount).sum + spell.amount.bonus, events)
    if (state.status !== 'active') return
  }
}

export { conscious }
