// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// `srd_monsters` rows -> engine CombatantSetup (F09 SS3.1). The initiator's third enemy source,
// between the hand-tuned fixtures and the CR-derived last resort.
//
// Why it exists: measured over 224 authored enemy lines, 185 fell through to a CR-derived generic
// block - MONSTER_FIXTURES carries ten monsters and the guide writes thug (32x), guard (13x),
// specter (13x), merrow, sahuagin, animated armor. The full SRD 5.2.1 set was in the database the
// whole time; nothing read it. A derived block is not just approximate, it is harsher: the CR-1
// derivation gives a Ghoul AC 14 / 33 hp against the SRD's AC 12 / 22.
//
// Pure, like every other module behind the manifest boundary: the caller fetches the rows, this
// parses them. Nothing here invents a number - a row with no usable attack returns null and the
// caller falls through.

import { abilityModifier } from '../guide/npc-stats.ts'
import type { AttackSpec, CombatantSetup, CombatSide, SaveModifiers } from './types.ts'

/** An `srd_monsters` row, as selected. `data` is the untyped SRD payload. */
export interface SrdMonsterRow {
  name: string
  armor_class: number | null
  hit_points: number | null
  data: unknown
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value) ? (value as Record<string, unknown>) : {}
}

function num(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null
}

/** "D6" -> 6. The SRD payload spells die types, not sides. */
function dieSides(value: unknown): number | null {
  if (typeof value !== 'string') return null
  const sides = Number.parseInt(value.replace(/^d/i, ''), 10)
  return Number.isFinite(sides) && sides > 0 ? sides : null
}

/** Feet -> grid squares, floored at one so nothing is immobile through rounding. */
const squares = (feet: number | null): number => Math.max(1, Math.round((feet ?? 30) / 5))

/**
 * One SRD attack entry -> up to two AttackSpecs. A spear is "Melee or Ranged" - it carries a reach
 * AND a range - and the engine's AttackSpec is one or the other, so both are emitted and the
 * heuristic picks per turn, exactly as a PC's melee/ranged pair works.
 */
function toAttackSpecs(actionName: string, attack: Record<string, unknown>): AttackSpec[] {
  const sides = dieSides(attack.damage_die_type)
  const count = num(attack.damage_die_count)
  if (sides === null || count === null) return []
  const damage = { count, sides, bonus: num(attack.damage_bonus) ?? 0 }
  const toHit = num(attack.to_hit_mod) ?? 0
  const reach = num(attack.reach)
  const range = num(attack.range)
  const specs: AttackSpec[] = []
  if (reach !== null && reach > 0) {
    specs.push({ name: actionName, kind: 'melee', toHit, damage, range: squares(reach) })
  }
  if (range !== null && range > 0) {
    const longRange = num(attack.long_range)
    specs.push({
      name: specs.length > 0 ? `${actionName} (thrown)` : actionName,
      kind: 'ranged',
      toHit,
      damage,
      range: squares(range),
      ...(longRange !== null && longRange > 0 ? { longRange: squares(longRange) } : {}),
    })
  }
  return specs
}

/** Every attack the row's ACTION-type actions declare, in statblock order. */
function parseAttacks(data: Record<string, unknown>): AttackSpec[] {
  const actions = Array.isArray(data.actions) ? data.actions : []
  const specs: AttackSpec[] = []
  for (const raw of actions) {
    const action = asRecord(raw)
    if (typeof action.action_type === 'string' && action.action_type !== 'ACTION') continue
    const name = typeof action.name === 'string' ? action.name : 'Attack'
    for (const rawAttack of Array.isArray(action.attacks) ? action.attacks : []) {
      specs.push(...toAttackSpecs(name, asRecord(rawAttack)))
    }
  }
  return specs
}

/**
 * Creature types that do not break (F09 SS8.3). A skeleton has no morale to lose; a bandit does.
 * The flat 0.25 for everything else is a placeholder until authored tactics profiles land at
 * F09.1 - the same role MORALE_BY_ARCHETYPE plays for lightweight NPC blocks.
 */
const UNBREAKABLE_TYPES = new Set(['undead', 'construct', 'ooze', 'plant'])
const SRD_DEFAULT_MORALE = 0.25

function moraleFor(data: Record<string, unknown>): number {
  const type = asRecord(data.type).key
  return typeof type === 'string' && UNBREAKABLE_TYPES.has(type.toLowerCase()) ? 0 : SRD_DEFAULT_MORALE
}

/**
 * An SRD row -> a CombatantSetup, or null when the row carries no usable attack (a swarm whose
 * only action is a save-based aura, a creature statted purely through traits). Null means "not a
 * source for this enemy" and the caller falls through to the CR-derived block.
 *
 * The AUTHORED name is kept, not the SRD one: "Brine Raider" reskinning a bandit must read as
 * authored, the same rule the fixture path follows.
 */
export function srdMonsterToSetup(
  row: SrdMonsterRow,
  opts: { id: string; name: string; side?: CombatSide; auto?: boolean },
): CombatantSetup | null {
  const data = asRecord(row.data)
  const attacks = parseAttacks(data)
  if (attacks.length === 0) return null

  const scores = asRecord(data.ability_scores)
  const mod = (key: string, fallback = 10) => abilityModifier(num(scores[key]) ?? fallback)
  const dexMod = mod('dexterity')
  const saves: SaveModifiers = {
    str: mod('strength'), dex: dexMod, con: mod('constitution'),
    int: mod('intelligence'), wis: mod('wisdom'), cha: mod('charisma'),
  }
  const hpMax = num(row.hit_points) ?? num(data.hit_points)
  const ac = num(row.armor_class) ?? num(data.armor_class)

  return {
    id: opts.id,
    name: opts.name,
    side: opts.side ?? 'enemy',
    kind: 'npc',
    refId: null,
    imageUrl: null,
    x: 0,
    y: 0,
    hpMax: hpMax !== null && hpMax > 0 ? hpMax : 10,
    ac: ac !== null && ac > 0 ? ac : 10 + dexMod,
    speed: squares(num(asRecord(data.speed).walk)),
    dexMod,
    saves,
    attacks,
    spells: [],
    morale: moraleFor(data),
    auto: opts.auto ?? true,
  }
}

/**
 * Words that qualify a creature rather than name it - a "Giant" is not a monster, a "Giant Spider"
 * is. Blocks the species alias below from claiming them.
 */
const QUALIFIERS = new Set(['giant', 'young', 'adult', 'ancient', 'swarm', 'animated', 'dire', 'greater', 'lesser'])

/**
 * Index SRD rows for name lookup.
 *
 * Two keys per row: its exact name, and - for a two-word name whose first word is the species -
 * that species alone, because the SRD stats a variant where the guide writes the creature
 * ("Sahuagin" vs the table's "Sahuagin Warrior"). Exact names are indexed last so they always win
 * a collision, and a caller reaches a reskin ("Vane's Hired Thug") through `srdLookupNames`.
 */
export function indexSrdMonsters(rows: SrdMonsterRow[]): Map<string, SrdMonsterRow> {
  const byName = new Map<string, SrdMonsterRow>()
  const key = (s: string) => s.trim().toLowerCase()
  for (const row of rows) {
    const words = key(row.name).split(/\s+/)
    if (words.length === 2 && !QUALIFIERS.has(words[0]) && !byName.has(words[0])) byName.set(words[0], row)
  }
  for (const row of rows) byName.set(key(row.name), row)
  return byName
}

/** The lookup keys a caller should fetch for an authored enemy name: the name and its head noun. */
export function srdLookupNames(enemyName: string): string[] {
  const name = enemyName.trim()
  if (!name) return []
  const words = name.toLowerCase().split(/\s+/)
  const last = words[words.length - 1]
  return last && last !== name.toLowerCase() ? [name, last] : [name]
}
