// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// F09 combat engine (SS4): pure, deterministic, tile-based. All distances are in grid squares
// (5 ft each) on the GRID_SIZE grid from state/. Plain data + pure functions only - runs under
// Vitest, the frontend bundle, and (once synced) the Deno edge runtime. The engine never reads
// wall-clock or unseeded randomness: every roll comes from the Rng passed in, so a fixed seed
// plus the same action sequence replays byte-identically (F09 SS8 golden-file criterion).

export interface DiceExpr {
  count: number
  sides: number
  bonus: number
}

export interface AttackSpec {
  name: string
  kind: 'melee' | 'ranged'
  toHit: number
  damage: DiceExpr
  /** Normal range/reach in squares (melee reach 1, shortbow 16). */
  range: number
  /** Ranged long range in squares (shortbow 64): reachable at disadvantage. Absent = no long range. */
  longRange?: number
}

export type CombatSide = 'party' | 'enemy'

export type AbilityKey = 'str' | 'dex' | 'con' | 'int' | 'wis' | 'cha'
export const ABILITY_KEYS: readonly AbilityKey[] = ['str', 'dex', 'con', 'int', 'wis', 'cha']
export type SaveModifiers = Record<AbilityKey, number>

/** Area of effect. Sizes are in squares; cone/line project from the caster toward the aim cell. */
export type SpellArea =
  | { shape: 'single' }
  | { shape: 'circle'; radius: number }
  | { shape: 'cone'; length: number }
  | { shape: 'line'; length: number }
  | { shape: 'cube'; size: number }

/**
 * A castable spell (F09 SS4.1). `effect` picks the resolution path: an attack roll vs AC, a
 * saving throw vs the caster's DC (damage on fail; onSave decides success), or healing. `range`
 * is squares to the single target or the AoE aim cell (0 = self-origin templates).
 */
export interface SpellSpec {
  name: string
  cost: 'action' | 'bonus'
  effect: 'attack' | 'save' | 'heal'
  range: number
  area: SpellArea
  /** Damage (attack/save) or healing (heal) rolled per affected creature. */
  amount: DiceExpr
  damageType?: string
  /** effect 'attack': spell attack bonus. */
  toHit?: number
  /** effect 'save': ability the target rolls, the DC, and the damage on a success. */
  saveAbility?: AbilityKey
  saveDc?: number
  onSave?: 'half' | 'none'
  /** Who legal targets are; defaults to enemies for damage, allies for heal. */
  affects?: 'enemies' | 'allies' | 'any'
}

/** Phase 1 condition subset (F09 SS4.1). */
export type ConditionName = 'prone' | 'unconscious'

export interface CombatantSetup {
  id: string
  name: string
  side: CombatSide
  kind: 'pc' | 'npc'
  /** characters.id / npcs.id / fixture key; null for ad-hoc tokens. */
  refId: string | null
  imageUrl: string | null
  x: number
  y: number
  hpMax: number
  ac: number
  /** Movement per turn in squares. */
  speed: number
  dexMod: number
  attacks: AttackSpec[]
  /** Saving-throw modifiers; dex defaults to dexMod, others to 0 when omitted. */
  saves?: Partial<SaveModifiers>
  spells?: SpellSpec[]
  /** Driver hint: the minion heuristic takes this combatant's turns. The engine ignores it. */
  auto?: boolean
}

export interface CombatantHp {
  current: number
  max: number
  temp: number
}

export interface Combatant {
  id: string
  name: string
  side: CombatSide
  kind: 'pc' | 'npc'
  refId: string | null
  imageUrl: string | null
  x: number
  y: number
  hp: CombatantHp
  /** Pre-difficulty max HP; hp.max is rescaled from this when hp_mult changes (F09 SS5.1). */
  baseHpMax: number
  ac: number
  speed: number
  dexMod: number
  saves: SaveModifiers
  attacks: AttackSpec[]
  spells: SpellSpec[]
  conditions: ConditionName[]
  /** NPCs die at 0 HP; PCs fall unconscious instead (death saves are a later slice). */
  dead: boolean
  /** Dodge lasts until the start of this combatant's next turn. */
  dodging: boolean
  /** Disengage lasts until the end of this combatant's turn. */
  disengaged: boolean
  /** One reaction (opportunity attack) per round; resets at own turn start. */
  reactionAvailable: boolean
  auto: boolean
}

/** Active-combatant economy; the reaction lives on each Combatant since it spends off-turn. */
export interface TurnEconomy {
  action: boolean
  bonus: boolean
  /** Remaining movement squares this turn. */
  move: number
}

/** Named modifier set applied at resolution time to the enemy side (F09 SS5.1). */
export interface DifficultySetting {
  name: string
  hpMult: number
  toHit: number
  dc: number
  dmgMult: number
}

export interface CombatEngineState {
  obstacles: [number, number][]
  combatants: Combatant[]
  /** Initiative order, highest total first; fixed for the whole combat. */
  initiative: { id: string; total: number }[]
  round: number
  /** Index into initiative of the active combatant. */
  turnIndex: number
  economy: TurnEconomy
  difficulty: DifficultySetting
  /** Grid dimensions in squares (default GRID_SIZE x GRID_SIZE); custom map sizes come from the Lab. */
  gridWidth: number
  gridHeight: number
  status: 'active' | 'ended'
  winner: CombatSide | null
}

/** Turn actions, always for the active combatant. Stat edits/difficulty are separate calls. */
export type CombatAction =
  | { type: 'move'; to: [number, number] }
  | { type: 'attack'; targetId: string; attackIndex: number }
  | { type: 'cast'; spellIndex: number; targetId?: string; aim?: [number, number] }
  | { type: 'dodge' }
  | { type: 'dash' }
  | { type: 'disengage' }
  | { type: 'stand_up' }
  | { type: 'end_turn' }

export interface RollBreakdown {
  /** Raw d20 results - two entries under advantage/disadvantage. */
  dice: number[]
  used: number
  mods: { label: string; value: number }[]
  total: number
  advantage: 'none' | 'advantage' | 'disadvantage'
}

export interface DamageBreakdown {
  rolls: number[]
  sides: number
  bonus: number
  /** Difficulty dmg_mult actually applied (1 when neutral or attacker is party-side). */
  mult: number
  total: number
}

export type CombatEvent =
  | { kind: 'combat_start'; difficulty: string }
  | { kind: 'initiative'; order: { id: string; name: string; roll: RollBreakdown }[] }
  | { kind: 'round_start'; round: number }
  | { kind: 'turn_start'; id: string; name: string }
  | { kind: 'turn_skip'; id: string; name: string; reason: 'dead' | 'unconscious' }
  | { kind: 'move'; id: string; path: [number, number][]; cost: number; remaining: number }
  | {
      kind: 'attack'
      attackerId: string
      targetId: string
      attackName: string
      /** true for opportunity attacks. */
      reaction: boolean
      roll: RollBreakdown
      targetAc: number
      outcome: 'crit' | 'hit' | 'miss'
      damage: DamageBreakdown | null
    }
  | { kind: 'damage'; id: string; amount: number; hp: CombatantHp }
  | { kind: 'heal'; id: string; amount: number; hp: CombatantHp }
  | {
      kind: 'spell_cast'
      casterId: string
      casterName: string
      spellName: string
      effect: 'attack' | 'save' | 'heal'
      area: SpellArea
      targets: { id: string; name: string }[]
    }
  | {
      kind: 'save'
      id: string
      name: string
      ability: AbilityKey
      roll: RollBreakdown
      dc: number
      success: boolean
    }
  | { kind: 'down'; id: string; name: string; result: 'dead' | 'unconscious' }
  | { kind: 'action'; id: string; action: 'dodge' | 'dash' | 'disengage' | 'stand_up' }
  | { kind: 'edit'; id: string; note: string }
  | { kind: 'difficulty'; name: string; note: string }
  | { kind: 'turn_end'; id: string }
  | { kind: 'combat_end'; winner: CombatSide }

export interface EngineResult {
  state: CombatEngineState
  events: CombatEvent[]
}

/** Illegal action (out of range, no budget, not your turn...). Thrown before any rng use. */
export class CombatError extends Error {}
