// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Deterministic serialization + hash for checkpoint/resync identity checks (F05 SS4.2
// "checkpoint restore reproduces identical state - hash comparison", F06 SS7 "reconnect
// resyncs to identical state"). Pure and synchronous so it runs identically in tests, the
// browser, and the edge runtime.

import type { Json } from './types.ts'

/** JSON.stringify with object keys sorted at every depth - key order can't change the hash. */
export function stableStringify(value: Json): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value)
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`
  const entries = Object.keys(value)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`)
  return `{${entries.join(',')}}`
}

/** FNV-1a 64-bit over the stable serialization, as a 16-char hex string. */
export function hashState(value: Json): string {
  const text = stableStringify(value)
  let hash = 0xcbf29ce484222325n
  const prime = 0x100000001b3n
  const mask = 0xffffffffffffffffn
  for (let i = 0; i < text.length; i++) {
    hash ^= BigInt(text.charCodeAt(i))
    hash = (hash * prime) & mask
  }
  return hash.toString(16).padStart(16, '0')
}
