// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

export { applyDiff, applyDiffs, mergePatch } from './diff.ts'
export { hashState, stableStringify } from './hash.ts'
export { moveCost, moveDiff, validateMove } from './move.ts'
export type { MoveActor, MoveVerdict } from './move.ts'
export { computePartyProfile } from './party.ts'
export type { PartyCharacter, PartyProfile } from './party.ts'
export { buildDemoScript } from './demo-script.ts'
export type { DemoContext, DemoStep } from './demo-script.ts'
export { GRID_SIZE, initialGameState } from './types.ts'
export type {
  ActionEconomy, CombatState, DialogueLine, DialogueState, DiffDomain, DmState, FxEvent,
  GameState, HpState, Json, ObjectivesState, ObjectiveView, PlayersState, PlayerView,
  SceneMode, SceneState, SessionState, SpeakerSlot, StateDiff, TokenState,
} from './types.ts'
