// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Live GameState contract (F06 SS6): everything the adventure page renders derives from this
// shape, delivered as per-domain diffs over the game:{adventure_id} channel. Owned by the
// single writer (the session function now, F07's Adventure Manager later). Plain data only -
// runs under Vitest, the frontend bundle, and the Deno edge runtime (relative imports with
// explicit .ts extensions, no platform APIs).

export type Json = string | number | boolean | null | Json[] | { [key: string]: Json }

export type SceneMode = 'narration' | 'roleplay' | 'battle' | 'puzzle' | 'downtime'

/** Grid side length of every battle map (F04/F06: 32x32 over a 1024x1024 image). */
export const GRID_SIZE = 32

export interface SceneState {
  mode: SceneMode
  /** Background XOR map - decided upstream by the Scene Manager, never by the client. */
  activeVisual: 'background' | 'map'
  locationId: string | null
  locationName: string
  backgroundUrl: string | null
  musicTrack: string | null
  /** In-game day from the World Clock (F06 header). */
  day: number
}

export interface DialogueLine {
  id: string
  /** Display name; null speaker = narrator voice. */
  speaker: string | null
  npcId: string | null
  text: string
}

export interface SpeakerSlot {
  npcId: string
  name: string
  side: 'left' | 'right'
  imageUrl: string | null
}

export interface DialogueState {
  /** Bounded history, newest last (scroll-up history in the renderers). */
  lines: DialogueLine[]
  /** Line currently being revealed/spoken; older lines render instantly. */
  activeLineId: string | null
  /** Half-body portraits on stage in roleplay mode. */
  speakers: SpeakerSlot[]
}

export interface HpState {
  current: number
  max: number
  temp: number
}

export interface TokenState {
  id: string
  kind: 'pc' | 'npc'
  /** characters.id or npcs.id. */
  refId: string
  name: string
  imageUrl: string | null
  x: number
  y: number
  hp: HpState | null
  conditions: string[]
  allegiance: 'party' | 'enemy' | 'neutral'
  controller: 'player' | 'dm' | 'ai'
  controllerUserId: string | null
  /** Movement per turn, in grid squares. */
  speed: number
}

export interface ActionEconomy {
  action: boolean
  bonus: boolean
  /** Remaining movement squares this turn. */
  move: number
  reaction: boolean
}

export interface CombatState {
  locationId: string | null
  mapUrl: string | null
  obstacles: [number, number][]
  tokens: TokenState[]
  /** Initiative order, highest first. */
  initiative: { tokenId: string; roll: number }[]
  round: number
  activeTokenId: string
  economy: ActionEconomy
}

export interface PlayerView {
  userId: string
  characterId: string
  name: string
  connected: boolean
  hp: HpState
  conditions: string[]
}

export interface PlayersState {
  list: PlayerView[]
}

export interface ObjectiveView {
  id: string
  /** Revealed player-facing title only - hidden descriptions never enter GameState. */
  title: string
  state: 'revealed' | 'active' | 'completed'
}

export interface ObjectivesState {
  currentId: string | null
  list: ObjectiveView[]
}

export interface SessionState {
  id: string | null
  index: number
  status: 'lobby' | 'active' | 'ended'
  /** "Previously on..." text rendered at session start (F05 SS4.1). */
  recap: string | null
}

/** DM-only domains, stripped from player resyncs and broadcast on dm:{id} only. */
export interface DmState {
  /** Full objective checklist incl. hidden ones (DM overview tab). */
  objectives: { id: string; title: string; hidden: boolean; state: string }[]
  /** F07 proposal tray arrives in Phase 5; typed as an empty list until then. */
  proposals: Json[]
}

export interface GameState {
  scene: SceneState
  dialogue: DialogueState
  combat: CombatState | null
  players: PlayersState
  objectives: ObjectivesState
  session: SessionState
  dm: DmState | null
}

export type DiffDomain = 'scene' | 'dialogue' | 'combat' | 'players' | 'objectives' | 'session' | 'dm'

/**
 * One state-diff message. `patch` is an RFC 7386-style merge patch against that domain:
 * objects merge recursively, arrays and scalars replace, null deletes (or clears the whole
 * domain when the domain itself is nullable, e.g. combat end).
 */
export interface StateDiff {
  domain: DiffDomain
  patch: Json
}

/** Transient effects (floating damage numbers, etc.) - broadcast alongside diffs, never stored. */
export interface FxEvent {
  kind: 'damage' | 'heal' | 'banner'
  tokenId?: string
  value?: number
  text?: string
}

export function initialGameState(): GameState {
  return {
    scene: {
      mode: 'narration',
      activeVisual: 'background',
      locationId: null,
      locationName: '',
      backgroundUrl: null,
      musicTrack: null,
      day: 1,
    },
    dialogue: { lines: [], activeLineId: null, speakers: [] },
    combat: null,
    players: { list: [] },
    objectives: { currentId: null, list: [] },
    session: { id: null, index: 0, status: 'lobby', recap: null },
    dm: { objectives: [], proposals: [] },
  }
}
