// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Adventure Lab explainer: turns a raw event_log row into one plain-English line a human can
// scan for bugs, WITHOUT the reader needing to know the event vocabulary. Pure and unit-tested;
// the lab endpoint fetches events + naming context and calls this, the frontend just renders.
//
// Curated by design (the lab's "what changed + why" mode): routine plumbing returns null and
// only shows in the raw toggle. Unknown types fall back to a generic line, so a new event kind
// never breaks the view - the same forgiving contract the old generic log had.

export interface PlayEvent {
  id: number
  type: string
  payload: Record<string, unknown>
  created_at: string
}

/** Id -> human name maps the endpoint assembles from the guide tables. */
export interface ExplainContext {
  npcs: Record<string, string>
  objectives: Record<string, string>
  locations: Record<string, string>
  ingredients: Record<string, string>
  characters: Record<string, string>
}

export type RowSeverity = 'info' | 'good' | 'warn' | 'issue'

export interface LaymanRow {
  eventId: number
  at: string
  type: string
  icon: string
  text: string
  severity: RowSeverity
  detail: Record<string, unknown>
}

const s = (v: unknown, fallback = ''): string => (typeof v === 'string' ? v : v == null ? fallback : String(v))
const n = (v: unknown): string => (typeof v === 'number' ? String(v) : s(v))
const cut = (v: unknown, len: number): string => {
  const str = s(v).replace(/\s+/g, ' ').trim()
  return str.length > len ? `${str.slice(0, len)}…` : str
}
const nameOf = (map: Record<string, string>, id: unknown): string => map[s(id)] ?? (id ? `${s(id).slice(0, 8)}…` : 'someone')
const list = (v: unknown): unknown[] => (Array.isArray(v) ? v : [])

interface Explained {
  icon: string
  text: string
  severity: RowSeverity
}

type Explainer = (p: Record<string, unknown>, ctx: ExplainContext) => Explained | null

// Every entry answers "what would a person say happened here?" Return null to keep it out of the
// curated view (still visible in raw). Order is irrelevant; this is a lookup, not a sequence.
const EXPLAINERS: Record<string, Explainer> = {
  session_started: (p) => ({ icon: '▶️', text: `Session ${n(p.index)} begins`, severity: 'info' }),
  // Full text, not a preview: the Logs tab is the bug-review surface and the whole DM narration
  // is what a reader needs to judge repetition, contradictions, and off-tone prose.
  narration_published: (p) => ({ icon: '📖', text: `DM narrates: "${s(p.text)}"`, severity: 'info' }),

  // --- the per-reply pipeline the user most wants to read ---
  check_prompted: (p) => ({
    icon: '🎲',
    text: `Calls for a ${s(p.skill)} check${p.dc ? ` (DC ${n(p.dc)})` : ''}${p.escalated ? ' — harder, same approach repeated' : ''}`,
    severity: 'info',
  }),
  check_rolled: (p) => ({
    icon: '🎲',
    text: `${s(p.skill)} check: rolled ${n(p.total)} vs DC ${n(p.dc)} → ${p.success ? 'SUCCESS' : 'FAILURE'}`,
    severity: p.success ? 'good' : 'info',
  }),
  npc_reply: (p, ctx) => {
    const revealed = list(p.revealed).map((id) => `"${cut(ctx.ingredients[s(id)] ?? s(id), 40)}"`)
    return {
      icon: '💬',
      text: `${nameOf(ctx.npcs, p.npc_id)} replies${revealed.length ? `, reveals ${revealed.join(', ')}` : ''} (tone: ${cut(p.tone, 40)})`,
      severity: revealed.length ? 'good' : 'info',
    }
  },
  disposition_changed: (p, ctx) => ({
    icon: '❤️',
    text: `${nameOf(ctx.npcs, p.npc_id)} warms/cools ${n(p.from)} → ${n(p.to)} (${cut(p.reason, 50)})`,
    severity: 'info',
  }),
  ingredient_revealed: (p, ctx) => ({
    icon: '🔑',
    text: `Clue found: "${cut(ctx.ingredients[s(p.ingredient_id)] ?? 'a clue', 70)}"`,
    severity: 'good',
  }),
  reveal_blocked: (p) => ({ icon: '🔒', text: `A clue stayed hidden — ${cut(p.reason, 80)}`, severity: 'issue' }),
  opening_emitted: (p, ctx) => ({ icon: '💡', text: `${nameOf(ctx.npcs, p.npc_id)} let something slip (${s(p.skill)} eased)`, severity: 'good' }),
  encounter_attempt: (p) => {
    // Social attempts are just exchange-counting; the challenge variant carries the useful tally.
    if (p.kind === 'social') return null
    return {
      icon: '🎯',
      text: `Challenge attempt (${s(p.skill)}): ${p.success ? 'success' : 'no progress'} — ${n(p.successes)} passed, ${n(p.failures)} failed so far`,
      severity: p.success ? 'good' : 'info',
    }
  },

  // --- scene / world ---
  scene_travel: (p) => ({ icon: '🚶', text: `Party travels to ${s(p.name)}`, severity: 'info' }),
  location_allocated: (p) => ({ icon: '🆕', text: `New location created on the fly: ${s(p.name)}`, severity: 'info' }),
  scene_effect_rejected: (p) =>
    p.effect === 'travel'
      ? { icon: '⛔', text: `Could not travel to "${cut(p.proposed, 40)}" — no such place exists`, severity: 'issue' }
      : { icon: '·', text: `Scene effect dropped (${s(p.effect)})${p.reason ? ` — ${cut(p.reason, 50)}` : ''}`, severity: 'info' },
  day_advanced: (p) => ({ icon: '🌙', text: `A day passes — now day ${n(p.day)}`, severity: 'info' }),
  antagonist_advanced: (p) => ({ icon: '🕷️', text: `Antagonist acts off-screen: ${cut(p.off_screen_event, 90)}`, severity: 'info' }),
  antagonist_defeated: () => ({ icon: '🏆', text: `Antagonist is defeated — its off-screen plan halts`, severity: 'good' }),
  social_started: (p, ctx) => ({ icon: '🗣️', text: `Conversation begins with ${list(p.npc_ids).map((id) => nameOf(ctx.npcs, id)).join(', ')}`, severity: 'info' }),
  social_ended: () => ({ icon: '🤝', text: `Conversation ends`, severity: 'info' }),
  npc_left_scene: (p, ctx) => ({ icon: '🚪', text: `${nameOf(ctx.npcs, p.npc_id)} leaves the scene`, severity: 'info' }),
  npc_state_recorded: (p) => ({ icon: p.state === 'dead' ? '💀' : '🩹', text: `${s(p.name)} is now ${s(p.state)}`, severity: p.state === 'dead' ? 'warn' : 'info' }),

  // --- encounters / combat ---
  encounter_opened: (p) => ({
    icon: p.kind === 'combat' ? '⚔️' : p.kind === 'social' ? '🗣️' : '🧩',
    text: `Encounter opens: "${s(p.label)}" [${s(p.kind ?? p.type)}]${p.stakes ? ` — at stake: ${cut(p.stakes, 70)}` : ''}`,
    severity: 'info',
  }),
  encounter_resolved: (p) => ({
    icon: '🏁',
    text: `Encounter "${s(p.label)}" ends — ${s(p.tier ?? p.outcome ?? 'resolved')}`,
    severity: p.tier === 'failed' || p.outcome === 'inconclusive' ? 'warn' : 'good',
  }),
  encounter_abandoned: (p) => ({ icon: '⚠️', text: `Encounter "${s(p.label)}" abandoned (${s(p.trigger)})`, severity: 'issue' }),
  combat_resolved: (p) => ({
    icon: '⚔️',
    text: `Combat "${s(p.label)}": ${s(p.outcome ?? (p.victory ? 'victory' : '?'))} [${s(p.resolver)}]${p.boss_killed ? ` — ${s(p.boss_killed)} slain` : ''}`,
    severity: p.resolver === 'placeholder' ? 'warn' : p.outcome === 'defeat' ? 'warn' : 'good',
  }),

  // --- story spine ---
  objective_completed: (p) => ({ icon: '✅', text: `Objective complete: "${s(p.title)}"`, severity: 'good' }),
  objective_revealed: (p) => ({ icon: '🎯', text: `New objective revealed: "${s(p.title)}"`, severity: 'info' }),
  objective_recognized: (p) => ({
    icon: '🔎',
    text: `Judge: objective "${s(p.title)}" ${p.completed ? 'completed' : 'progressing'}${p.evidence ? ` — "${cut(p.evidence, 60)}"` : ''}`,
    severity: 'info',
  }),
  beat_opened: (p) => ({ icon: '📌', text: `New beat: "${s(p.name)}"`, severity: 'info' }),
  beat_npcs_created: (p) => ({ icon: '🧑', text: `New NPC(s) introduced: ${list(p.npcs).map(String).join(', ')}`, severity: 'info' }),
  beat_npcs_capped: (p) => ({
    icon: '⚠️',
    text: `NPC creation capped — wanted ${list(p.requested).join(', ')}, made ${list(p.created).join(', ') || 'none'}`,
    severity: 'warn',
  }),
  dial_nudged: (p) => ({ icon: '🎚️', text: `Story dial "${s(p.dial)}" → ${n(p.to)} (${cut(p.why, 55)})`, severity: 'info' }),
  ending_leading_changed: () => ({ icon: '🎬', text: `Leading ending shifts`, severity: 'info' }),
  ending_committed: (p) => ({ icon: '🎬', text: `Ending committed: "${s(p.title)}"`, severity: 'good' }),
  suspicion_noted: (p) => ({ icon: '🕵️', text: `Suspicion on ${s(p.name)} → ${n(p.tally)}`, severity: 'info' }),
  bbeg_committed: (p) => ({ icon: '😈', text: `${s(p.name)} committed as the antagonist's agent`, severity: 'info' }),

  // --- quest offers ---
  offer_staged: (p) => ({ icon: '📜', text: `Quest offered — ${n(p.gold)} gold`, severity: 'info' }),
  offer_response: (p) => ({ icon: '💬', text: `Player responds to the offer: ${s(p.response)}`, severity: 'info' }),
  offer_accepted: (p) => ({ icon: '🤝', text: `Quest accepted (${n(p.gold)} gold)`, severity: 'good' }),
  quest_completed: (p) => ({ icon: '🏆', text: `Quest complete${p.paid ? ` — paid ${n(p.gold ?? '')} gold` : ''}`, severity: 'good' }),
  deadline_started: () => ({ icon: '⏳', text: `A deadline is now ticking`, severity: 'info' }),

  // --- pacing director ---
  director_action: (p) => ({
    icon: '🎭',
    text: `Director: ${s(p.action)} (rung ${n(p.rung)}) — ${cut(p.reason, 55)}`,
    severity: p.action === 'replan_beat' || p.action === 'guaranteed_route' || p.action === 'fail_forward' ? 'warn' : 'info',
  }),
  idle_nudge: () => ({ icon: '💤', text: `Nudge — the table went quiet`, severity: 'info' }),
  stall_promoted: () => ({ icon: '⚠️', text: `Story stalled — the director had to step in`, severity: 'warn' }),
  atom_forced: (p) => ({ icon: '⚠️', text: `Progress force-credited: "${s(p.atom)}" (${s(p.command)}) — a rescue, not natural play`, severity: 'warn' }),

  // --- red flags ---
  incident: (p) => ({
    icon: '🔴',
    text: `Incident [${s(p.kind)}]${p.name ? `: ${s(p.name)}` : ''}${p.evidence ? ` — ${cut(p.evidence, 60)}` : ''}`,
    severity: 'issue',
  }),
  agent_output_unparsed: (p) => ({
    icon: '🔴',
    text: `An agent's output could not be parsed (${s(p.role)}, ${s(p.finish_reason)}, ${n(p.chars)} chars) — likely a broken/garbled reply`,
    severity: 'issue',
  }),
  consistency_blocked: (p) => ({ icon: '🔴', text: `Narration blocked as contradictory: ${cut(p.violations, 80)}`, severity: 'issue' }),
  claim_check_shadow: (p) => {
    const v = list(p.violations).map((x) => {
      const o = (x ?? {}) as Record<string, unknown>
      return `${s(o.name)} ${s(o.role)} while ${s(o.state)}`
    })
    return { icon: p.enforced ? '🛑' : '👻', text: `Departed NPC in the prose${p.enforced ? ' (blocked)' : ' (shadow-logged)'}: ${v.join(', ')}`, severity: 'warn' }
  },
  ledger_contradiction: () => ({ icon: '⚠️', text: `The scene ledger contradicted itself`, severity: 'warn' }),

  // --- generation phase ---
  guide_repair: (p) => ({ icon: '🔧', text: `Guide auto-repaired [${s(p.handle)}]: ${cut(p.warning, 70)}`, severity: 'info' }),
  guide_repair_summary: (p) => ({ icon: '🔧', text: `Guide repairs done${p.note ? `: ${cut(p.note, 70)}` : ''}`, severity: 'info' }),
  reachability_lint: (p) => ({ icon: '🧭', text: `Reachability check ran${p.message ? `: ${cut(p.message, 70)}` : ''}`, severity: 'info' }),
  entity_reclassified: (p) => ({ icon: '♻️', text: `Reclassified ${list(p.names).join(', ')} (${s(p.from)} → ${s(p.to)})`, severity: 'info' }),
  group_npc_reclassified: (p) => ({ icon: '♻️', text: `Reclassified as a creature-group, not a person: ${list(p.removed).join(', ')}`, severity: 'info' }),
}

// Plumbing that carries no reader value on its own - visible only in the raw toggle.
const SKIP = new Set([
  'say', 'entry_mapped', 'story_event', 'milestone_reached', 'scene_ledger', 'ledger_credited',
  'claim_check_clean', 'beat_ingredient_reused', 'beat_exit_met', 'random_encounter_roll',
  'narrative_marker', 'opening_consumed', 'prop_created', 'ingredient_generated', 'encounter_talk',
  'encounter_exit', 'group_check_resolved', 'negotiation_prompted', 'offer_negotiated',
  'npc_state_skipped', 'dm_override',
])

/** One raw event -> one layman row, or null to keep it out of the curated view. */
export function explainEvent(event: PlayEvent, ctx: ExplainContext): LaymanRow | null {
  if (SKIP.has(event.type)) return null
  const base = { eventId: event.id, at: event.created_at, type: event.type, detail: event.payload }
  const fn = EXPLAINERS[event.type]
  if (fn) {
    const out = fn(event.payload ?? {}, ctx)
    if (!out) return null
    return { ...base, ...out }
  }
  // Unknown type: never drop it - show a generic line so new events stay visible.
  return { ...base, icon: '·', text: `${event.type.replace(/_/g, ' ')}`, severity: 'info' }
}
