// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// The Adventure Guide tab: the authored guide with a LIVE overlay, so "authored but never
// reached" content is obvious - objectives still hidden at the end, clues never discovered, an
// NPC that died, the ending the story drifted toward. Pure shaping over rows the endpoint fetches
// + the live GameState (npc states, current location). Unit-tested; the endpoint just supplies data.

export interface GuideInput {
  chapters: { index: number; title: string; status: string }[]
  objectives: { index: number; title: string; reveal_state: string }[]
  npcs: { id: string; name: string; role: string; initial_state: string | null }[]
  locations: { id: string; name: string }[]
  encounters: { type: string; spec: Record<string, unknown> | null }[]
  endings: { index: number; title: string; tone: string; status: string }[]
  ingredients: { type: string; reveals: string; content: Record<string, unknown> | null; discovered: boolean }[]
  npcStates: Record<string, string>
  currentLocationId: string | null
}

export interface GuideView {
  chapters: { index: number; title: string; status: string }[]
  objectives: { index: number; title: string; state: string }[]
  npcs: { name: string; role: string; state: string }[]
  locations: { name: string; current: boolean }[]
  encounters: { kind: string; label: string }[]
  endings: { title: string; tone: string; status: string }[]
  clues: { text: string; type: string; discovered: boolean }[]
  counts: { objectivesDone: number; objectivesTotal: number; cluesFound: number; cluesTotal: number }
}

// Info toys worth surfacing as "clues" (vs mechanical items); each shows discovered-or-not.
const CLUE_TYPES = new Set(['clue', 'secret', 'rumor'])
const byIndex = <T extends { index: number }>(rows: T[]): T[] => [...rows].sort((a, b) => a.index - b.index)

export function buildGuideView(input: GuideInput): GuideView {
  const npcs = input.npcs.map((npc) => ({
    name: npc.name,
    role: npc.role,
    state: input.npcStates[npc.id] ?? npc.initial_state ?? 'alive',
  }))
  const objectives = byIndex(input.objectives).map((o) => ({ index: o.index, title: o.title, state: o.reveal_state }))
  const clues = input.ingredients
    .filter((i) => CLUE_TYPES.has(i.type))
    .map((i) => ({ text: i.reveals || String((i.content ?? {}).text ?? '(unnamed clue)'), type: i.type, discovered: i.discovered }))

  return {
    chapters: byIndex(input.chapters),
    objectives,
    npcs,
    locations: input.locations.map((l) => ({ name: l.name, current: l.id === input.currentLocationId })),
    encounters: input.encounters.map((e) => ({ kind: e.type, label: String((e.spec ?? {}).label ?? e.type) })),
    endings: byIndex(input.endings).map((e) => ({ title: e.title, tone: e.tone, status: e.status })),
    clues,
    counts: {
      objectivesDone: objectives.filter((o) => o.state === 'completed').length,
      objectivesTotal: objectives.length,
      cluesFound: clues.filter((c) => c.discovered).length,
      cluesTotal: clues.length,
    },
  }
}
