import { describe, expect, it } from 'vitest'

import { addressedNpcId, isStageable, npcStateOf, resolveAddressed, resolveNpcNames, stagedElsewhere, stageableNpcs } from './staging'
import type { NpcStageRow } from './staging'

const cast: NpcStageRow[] = [
  { id: 'a', name: 'Borin Stonehand' },
  { id: 'b', name: 'Lost Expedition', initialState: 'dead' },
  { id: 'c', name: 'The Murkheart', initialState: 'absent' },
  { id: 'd', name: 'Elara', initialState: 'alive' },
  { id: 'e', name: 'nervous barkeep', generated: true },
  { id: 'f', name: '   ' },
]

describe('npcStateOf / isStageable', () => {
  it('live state overrides the authored one, both ways', () => {
    expect(npcStateOf({ id: 'a', initialState: 'alive' }, { a: 'dead' })).toBe('dead')
    expect(npcStateOf({ id: 'c', initialState: 'absent' }, { c: 'alive' })).toBe('alive')
  })
  it('defaults to alive when nothing is recorded', () => {
    expect(isStageable({ id: 'z' }, {})).toBe(true)
  })
  it('dead and absent are both unstageable', () => {
    expect(isStageable({ id: 'b', initialState: 'dead' }, {})).toBe(false)
    expect(isStageable({ id: 'c', initialState: 'absent' }, {})).toBe(false)
  })
})

describe('stageableNpcs', () => {
  it('drops the dead, the absent, and the nameless', () => {
    expect(stageableNpcs(cast, {}).map((n) => n.id)).toEqual(['a', 'd', 'e'])
  })
  it('the Sunken Chapel roster has NOBODY stageable', () => {
    // The live failure: 2 NPCs, one dead collective and one absent boss.
    const chapel = cast.filter((n) => n.id === 'b' || n.id === 'c')
    expect(stageableNpcs(chapel, {})).toEqual([])
  })
  it('namedOnly drops generated bystanders', () => {
    expect(stageableNpcs(cast, {}, { namedOnly: true }).map((n) => n.id)).toEqual(['a', 'd'])
  })
  it('excludeIds drops NPCs already staged', () => {
    expect(stageableNpcs(cast, {}, { excludeIds: ['a'] }).map((n) => n.id)).toEqual(['d', 'e'])
  })
  it('a live death removes someone the guide authored alive', () => {
    expect(stageableNpcs(cast, { a: 'dead' }).map((n) => n.id)).toEqual(['d', 'e'])
  })
})

describe('resolveNpcNames', () => {
  const living = stageableNpcs(cast, {})

  it('resolves exact and substring names, deduped and ordered', () => {
    const { ids, unresolved } = resolveNpcNames(['Borin', 'Elara', 'Borin Stonehand'], living)
    expect(ids).toEqual(['a', 'd'])
    expect(unresolved).toEqual([])
  })
  it('cannot resolve onto a corpse when candidates are pre-filtered', () => {
    const { ids, unresolved } = resolveNpcNames(['Lost Expedition'], living)
    expect(ids).toEqual([])
    expect(unresolved).toEqual(['Lost Expedition'])
  })
  it('reports names with no row at all (the "Elara in prose only" case)', () => {
    const { unresolved } = resolveNpcNames(['Sister Vaine'], living)
    expect(unresolved).toEqual(['Sister Vaine'])
  })
  it('caps at the limit', () => {
    const { ids } = resolveNpcNames(['Borin', 'Elara', 'nervous barkeep'], living, 2)
    expect(ids).toHaveLength(2)
  })
})

describe('addressedNpcId - who the party is talking to (2026-07-23)', () => {
  const staged = [
    { npcId: 'thorne', name: 'Elias Thorne' },
    { npcId: 'contact', name: "Thorne's Contact" },
  ]

  it('routes a named question to the person named, not to speakers[0]', () => {
    // The live failure: the party asked Elias Thorne four questions and Thorne's Contact
    // answered all of them, then slid from "get HIM to the Assizes" into "get ME to the Assizes".
    expect(addressedNpcId('I ask Elias Thorne what he needs.', staged)).toBe('thorne')
  })

  it('leaves the default alone when nobody is named', () => {
    expect(addressedNpcId('I look around the room.', staged)).toBeNull()
  })

  it('leaves the default alone when the utterance names both', () => {
    expect(addressedNpcId("I ask Elias Thorne and Thorne's Contact to explain.", staged)).toBeNull()
  })

  it('does not disambiguate a one-speaker stage', () => {
    expect(addressedNpcId('I ask Elias Thorne what he needs.', [staged[0]])).toBeNull()
  })

  it('matches whole names only - a prefix is a different person', () => {
    const two = [{ npcId: 'sil', name: 'Sil' }, { npcId: 'silas', name: 'Silas' }]
    expect(addressedNpcId('I greet Silas warmly.', two)).toBe('silas')
  })

  it('resolves a name at the end of a sentence', () => {
    expect(addressedNpcId('I turn to Elias Thorne.', staged)).toBe('thorne')
  })

  it('survives punctuation in a name without exploding the regex', () => {
    const odd = [{ npcId: 'a', name: 'Mr. O(1)' }, { npcId: 'b', name: 'Kestrel' }]
    expect(addressedNpcId('I nod at Kestrel.', odd)).toBe('b')
    expect(() => addressedNpcId('anything', odd)).not.toThrow()
  })
})

describe('resolveAddressed - naming someone who is not here (2026-07-27)', () => {
  const staged = [{ npcId: 'k', name: 'Warden Sef Karthen' }]
  const offstage = [{ name: 'Dessa Mol' }, { name: 'Cael Vesht' }]

  it('reports the named NPC as offstage instead of substituting whoever is present', () => {
    // The live failure: this exact utterance was answered by Karthen, twice.
    expect(resolveAddressed('I ask Dessa Mol what she thinks is moving on the ships', staged, offstage))
      .toEqual({ kind: 'offstage', name: 'Dessa Mol' })
  })

  it('resolves a staged NPC even when only one is on stage', () => {
    // addressedNpcId returns null below two staged NPCs, so naming the one present person never
    // resolved - it only ever worked by falling through to speakers[0].
    expect(resolveAddressed('Karthen, what is in the office?', staged, offstage))
      .toEqual({ kind: 'staged', npcId: 'k' })
  })

  it('treats a mention of an absent person as talk ABOUT them, not TO them', () => {
    expect(resolveAddressed('I ask Karthen where Dessa Mol went', staged, offstage))
      .toEqual({ kind: 'staged', npcId: 'k' })
  })

  it('stays unclear when two offstage names appear', () => {
    expect(resolveAddressed('what happened to Dessa Mol and Cael Vesht', staged, offstage))
      .toEqual({ kind: 'unclear' })
  })

  it('stays unclear when nobody is named', () => {
    expect(resolveAddressed('I look around', staged, offstage)).toEqual({ kind: 'unclear' })
  })

  it('does not match a name inside a longer word', () => {
    expect(resolveAddressed('I check the vestibule', staged, [{ name: 'Vest' }]))
      .toEqual({ kind: 'unclear' })
  })
})

describe('stagedElsewhere', () => {
  it('blocks a known mismatch - the Mira-at-Lock-3 case', () => {
    expect(stagedElsewhere('hoss-cottage', 'lock-3')).toBe(true)
  })

  it('allows an NPC standing where the party is', () => {
    expect(stagedElsewhere('lock-3', 'lock-3')).toBe(false)
  })

  it('allows every uncertainty - a false refusal costs more than the bug', () => {
    // No authored stop yet (npcLocationAt returns null before an NPC's first stop), an empty
    // itinerary like Edren Hoss's, or a party whose location is unknown.
    expect(stagedElsewhere(null, 'lock-3')).toBe(false)
    expect(stagedElsewhere(undefined, 'lock-3')).toBe(false)
    expect(stagedElsewhere('hoss-cottage', null)).toBe(false)
    expect(stagedElsewhere(null, null)).toBe(false)
    expect(stagedElsewhere('', 'lock-3')).toBe(false)
  })
})
