// Who can actually take the stage (overhaul Phase 2). Liveness used to be checked only at
// OPEN time, deep inside openSocialEncounter - so a beat could be planned around a dead
// collective ("Lost Expedition") or an NPC that exists only in prose ("Elara"), and the
// encounter simply failed to open forever after. Live 2026-07-22, Below the Sunken Chapel:
// the adventure shipped with two NPCs, one dead and one absent, and the social route to the
// active objective could never open - a permanently unwinnable story.
//
// Plan time is the right time: an encounter that cannot be staged NOW must not be persisted.

export type NpcLiveState = 'alive' | 'dead' | 'absent' | string

export interface NpcStageRow {
  id: string
  name: string
  /** Guide-authored starting state; live state overrides it. */
  initialState?: NpcLiveState | null
  /** Throwaway background NPCs (F10 SS4) - real cast only for staging candidates. */
  generated?: boolean | null
}

/** Live npcStates wins over the authored initial_state; absent from both means alive. */
export function npcStateOf(
  npc: Pick<NpcStageRow, 'id' | 'initialState'>,
  liveStates: Readonly<Record<string, string>>,
): NpcLiveState {
  return liveStates[npc.id] ?? npc.initialState ?? 'alive'
}

export function isStageable(
  npc: Pick<NpcStageRow, 'id' | 'initialState'>,
  liveStates: Readonly<Record<string, string>>,
): boolean {
  const state = npcStateOf(npc, liveStates)
  return state !== 'dead' && state !== 'absent'
}

/**
 * Everyone who could be staged right now. `excludeIds` drops NPCs already on stage;
 * `namedOnly` drops generated bystanders (the stall promoter and the beat planner both want
 * real cast, not the barkeep invented three turns ago).
 */
export function stageableNpcs(
  rows: readonly NpcStageRow[],
  liveStates: Readonly<Record<string, string>>,
  opts?: { excludeIds?: readonly string[]; namedOnly?: boolean },
): NpcStageRow[] {
  const excluded = new Set(opts?.excludeIds ?? [])
  return rows.filter((n) =>
    n.name.trim().length > 0 &&
    !excluded.has(n.id) &&
    !(opts?.namedOnly && n.generated) &&
    isStageable(n, liveStates))
}

/**
 * Which staged NPC the party just addressed by name, when that is unambiguous.
 *
 * `handleSay` has always answered as `speakers[0]` - its `targetNpcId` parameter exists but no
 * caller has ever passed it - so the first NPC staged replies to everything. Live 2026-07-23,
 * The Long Road to Emberfall: the party asked Elias Thorne four questions and Thorne's Contact
 * answered every one of them on his behalf, then slid into first person ("Just get HIM to the
 * Assizes" became "just get ME to the Assizes"). That pronoun collapse is what tripped the
 * consistency checker.
 *
 * This is entity resolution against a closed, code-owned roster - matching a proper name, not
 * interpreting meaning - so it stays deterministic. Ambiguity (nobody named, or two staged NPCs
 * both named) returns null and the caller keeps its existing default: a wrong confident guess
 * is worse than the status quo.
 */
export function addressedNpcId(
  utterance: string,
  staged: readonly { npcId: string; name: string }[],
): string | null {
  if (staged.length < 2) return null // one speaker on stage - nothing to disambiguate
  const named = namedIn(utterance, staged)
  return named.length === 1 ? named[0].npcId : null
}

const NAME_STOPWORDS = new Set(['the', 'of', 'and', 'lady', 'lord', 'sir'])

/**
 * The forms a player might plausibly type for one roster name: the whole thing, plus each
 * distinctive word in it.
 *
 * Matching only the full authored string is why this almost never resolved. Rosters carry titles
 * ("Warden Sef Karthen", "Captain Idris Thane") and nobody types those - they type "Karthen".
 * Tokens under three letters and bare honorifics are dropped so "of" and "sir" cannot match, and
 * a token two NPCs share simply matches both, which the callers already read as ambiguous.
 */
function nameKeys(name: string): string[] {
  const full = name.toLowerCase().trim()
  if (!full) return []
  const tokens = full.split(/\s+/).filter((t) => t.length >= 3 && !NAME_STOPWORDS.has(t))
  return [...new Set([full, ...tokens])]
}

/** Whole-word name matching, so "Sil" does not match "Silas" and "...ask Silas." still resolves. */
function namedIn<T extends { name: string }>(utterance: string, roster: readonly T[]): T[] {
  const haystack = ` ${utterance.toLowerCase()} `
  return roster.filter((r) =>
    nameKeys(r.name).some((key) =>
      new RegExp(`(^|[^a-z])${key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}([^a-z]|$)`).test(haystack)))
}

export type AddressedNpc =
  | { kind: 'staged'; npcId: string }
  | { kind: 'offstage'; name: string }
  | { kind: 'unclear' }

/**
 * Who the party just spoke to - including the case where that person is not here.
 *
 * `addressedNpcId` only ever searched the STAGED roster, and its caller fell back to
 * `speakers[0]` for everything else. So naming someone who had walked off did not read as "she
 * is gone" - it silently handed her line to whoever happened to be standing there. Live
 * 2026-07-27, Miregate: the player typed "I ask Dessa Mol what she thinks is moving on the
 * ships" and Warden Sef Karthen answered, twice, having never been part of that conversation.
 * Eight lines later Karthen said "Dessa's not here" - the system knew, and had said nothing.
 *
 * `offstage` gives the caller the one fact it needs to answer honestly in fiction instead of
 * substituting a body. Still pure name resolution against a closed roster, never interpretation.
 */
export function resolveAddressed(
  utterance: string,
  staged: readonly { npcId: string; name: string }[],
  offstage: readonly { name: string }[],
): AddressedNpc {
  const here = namedIn(utterance, staged)
  if (here.length === 1) return { kind: 'staged', npcId: here[0].npcId }
  // Only when NO staged NPC was named - "ask Karthen about Dessa" is addressed to Karthen, and
  // mentioning someone absent in the third person is not addressing them.
  if (here.length === 0) {
    const away = namedIn(utterance, offstage)
    if (away.length === 1) return { kind: 'offstage', name: away[0].name }
  }
  return { kind: 'unclear' }
}

/**
 * Resolves LLM-provided NPC names to rows, exact-then-substring (the historical matcher),
 * restricted to the candidates given - so a caller that passes only stageable NPCs cannot
 * resolve a name onto a corpse. Returns ids in the order the names were provided, deduped.
 */
export function resolveNpcNames(
  names: readonly string[],
  candidates: readonly NpcStageRow[],
  limit = 3,
): { ids: string[]; unresolved: string[] } {
  const norm = (s: string) => s.toLowerCase().trim()
  const ids: string[] = []
  const unresolved: string[] = []
  for (const name of names) {
    const target = norm(name)
    if (!target) continue
    const match = candidates.find((c) => norm(c.name) === target)
      ?? candidates.find((c) => norm(c.name).includes(target) || target.includes(norm(c.name)))
    if (!match) unresolved.push(name)
    else if (!ids.includes(match.id)) ids.push(match.id)
  }
  return { ids: ids.slice(0, limit), unresolved }
}

/**
 * Is this NPC authored to be somewhere OTHER than where the party is standing? (2026-07-30)
 *
 * Run d3f20788: Mira Hoss is authored `obj0 = Hoss cottage` with no Lock 3 stop. The party finished
 * at the cottage, travelled to Lock 3, and the SAME npc_id was immediately re-staged there -
 *
 *     t26  social_ended    npc_ids:[Mira]
 *     t26  scene_travel -> Lock 3
 *     t26  social_started  npc_ids:[Mira]
 *     t28  npc_action {type:'join_combat'} npc_id:Mira
 *
 * She then spoke twice at Lock 3, giving tactical orders in a scene she is not in, four entries
 * after the narration had explicitly left her at the cottage packing a trunk. Both LLMs behaved
 * correctly: state said she was present, so the NPC agent voiced her and the narrator described her.
 * `startSocial` guards the DM, the count, groups and the dead - and never asked where anyone was.
 *
 * DELIBERATELY CONSERVATIVE, because a false refusal is worse than the bug this fixes: refusing to
 * stage is what killed the Maren beat, and the party paid a setback for a scene nobody saw. So the
 * answer is "no" on every uncertainty -
 *   - no authored stop yet for this objective (`npcLocationAt` returns null): unconstrained, allow.
 *     Edren Hoss has an empty itinerary and must never be blocked by this.
 *   - the party's location is unknown: nothing to compare, allow.
 * Only a KNOWN mismatch of two known places blocks, and callers drop that one NPC rather than
 * failing the whole staging call.
 */
export function stagedElsewhere(
  authoredLocationId: string | null | undefined,
  partyLocationId: string | null | undefined,
): boolean {
  if (!authoredLocationId || !partyLocationId) return false
  return authoredLocationId !== partyLocationId
}
