// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Does a cutscene reply SEEK INFORMATION? (2026-07-29)
//
// Measured across six runs (102 mapped intents, 78 folds): 37% of `fold_in` entries are questions
// about the fiction and 35% are examinations of something in it - "What did Edric mean by 'She
// took her pound'?", "I examine the ring that Edric gave me", "What does the wave-glyph signify?".
//
// The mapper files these CORRECTLY. They genuinely are not engagement and genuinely do not change
// where the party stands, which is the definition `fold_in` was written to. The defect is one
// layer up: the entry taxonomy has three buckets - engage the offered encounter, go off-script,
// or colour - and investigation is none of them, so the commonest thing players do during a
// cutscene lands in the bucket built for banter and writes nothing. In `599d34e7` the party asked
// and looked eight turns running while the Progress Director climbed to `replan_beat`; the story
// moved, but nothing the players did moved it.
//
// This predicate is what lets the fold path answer with an AUTHORED clue placed in the room the
// party is standing in, instead of free narration.
//
// It is a HEURISTIC and is deliberately allowed to be one, because it gates nothing. A true
// answer only means the location reveal gate is CONSULTED - and that gate still refuses clues
// placed elsewhere, already-discovered clues, affinity-bound clues, and anything past one per
// turn. So a false positive costs an authored clue in the party's own room surfacing a turn
// early, and a false negative is exactly today's behaviour. Both are the safe direction, which is
// the bar `runConsistency` and `namesRemovedBy` failed by blocking prose on a guess.

/**
 * Asking the GAME what to do, rather than asking about the world.
 *
 * Excluded because this predicate means "the reply points attention at something in the fiction",
 * and "what do i do" points at nothing - there is no object to find a clue on. A genuinely stuck
 * party is the Progress Director's job, and its `reveal` rung already covers exactly this.
 */
const STUCK = /^\s*(?:(?:what|where)\s+(?:do|should)\s+(?:i|we)\b|what\s+(?:now|next)\b|what\s+should\b|idk\b|i\s+don'?t\s+know\s+what\b)/i

/** An interrogative opener - the question mark is optional, because players rarely type one. */
const INTERROGATIVE = /^\s*(?:who|what|where|when|why|how|which|whose|did|does|do|is|are|was|were|can|could|has|have|tell)\b/i

/** Directed attention at a thing: the verbs of a search, not of a move. */
const EXAMINE = /\b(?:look|looks|looked|looking|examine|examines|examined|examining|inspect|inspects|inspecting|study|studies|studying|check|checks|checking|search|searches|searching|read|reads|reading|glance|glances|peer|peers|watch|watches|observe|observes|scan|scans|survey|surveys)\b/i

/**
 * True when a folded reply asks about the fiction or examines something in it.
 *
 * Only ever called on replies the mapper has ALREADY classified `fold_in`, so it does not need to
 * separate investigation from engagement - the mapper did that.
 */
export function seeksInformation(text: string): boolean {
  const trimmed = (text ?? '').trim()
  if (trimmed.length === 0) return false
  if (STUCK.test(trimmed)) return false
  return trimmed.includes('?') || INTERROGATIVE.test(trimmed) || EXAMINE.test(trimmed)
}
