// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Canonical atom authority (story-engine overhaul Phase 1). Milestone atoms - the flag/event
// strings predicates complete through - used to be invented as free text in five places and
// matched only by exact lowercase string. This module is the ONE place that canonicalizes,
// resolves, and registers atom names.
//
// AUTO-REPAIR IS CANONICAL EQUALITY ONLY (case/punctuation/apostrophes/separators). Fuzzy
// matching is strictly suggestion material: adversarial review (2026-07-22) proved edit
// distance <= 2 merges ANTONYMS (guards_averted->guards_alerted is distance 1; the whole un-
// prefix class - door_unlocked/door_locked, sealed/unsealed - is distance 2, and the planner
// is INSTRUCTED to declare success/setback pairs, manufacturing exactly such neighbors), and
// token reorder merges subject/object reversals (party_betrayed_varga is not
// varga_betrayed_party). Menus at generation time are the real typo defense.

export type AtomKind = 'flag' | 'event' | 'fact'
export type AtomScope = 'spine' | 'local'

export interface RegistryAtom {
  /** Canonical identity: unique per adventure. */
  slug: string
  kind: AtomKind
  scope: AtomScope
  /** The exact authored text as it appears in predicates - what evaluation matches on. */
  label: string
}

/** Case, apostrophes, punctuation, separators - deterministic, meaning-preserving only. */
export function canonicalizeAtomSlug(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
}

function tokensOf(slug: string): string[] {
  return slug.split('_').filter(Boolean)
}

function tokenMultisetEqual(a: string, b: string): boolean {
  const ta = tokensOf(a).sort()
  const tb = tokensOf(b).sort()
  return ta.length === tb.length && ta.every((t, i) => t === tb[i])
}

/** Bounded Levenshtein - bails at max+1 so long strings stay cheap. */
export function editDistance(a: string, b: string, max: number): number {
  if (Math.abs(a.length - b.length) > max) return max + 1
  let previous = Array.from({ length: b.length + 1 }, (_, i) => i)
  for (let i = 1; i <= a.length; i++) {
    const current = [i]
    let rowMin = i
    for (let j = 1; j <= b.length; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1
      current[j] = Math.min(previous[j] + 1, current[j - 1] + 1, previous[j - 1] + cost)
      rowMin = Math.min(rowMin, current[j])
    }
    if (rowMin > max) return max + 1
    previous = current
  }
  return previous[b.length]
}

/**
 * Fuzzy neighborhood - SUGGESTIONS ONLY, never auto-merge. Same words reordered or within 2
 * edits: exactly the transforms that flip meaning in D&D atom names (antonyms, subject/object
 * swaps, ward_1 vs ward_2), which is why no resolution path is allowed to act on this.
 */
export function isNearMiss(canonicalA: string, canonicalB: string): boolean {
  if (canonicalA === canonicalB) return false
  return tokenMultisetEqual(canonicalA, canonicalB) || editDistance(canonicalA, canonicalB, 2) <= 2
}

export type AtomResolution =
  | { ok: true; text: string; via: 'exact' | 'canonical' }
  | { ok: false; canonical: string; suggestions: string[] }

/**
 * Resolves a proposed atom against a list of authored atom texts. Exact match first (free),
 * then canonical-form equality (case/punctuation/apostrophe repair). Nothing fuzzier ever
 * resolves - near-misses surface as suggestions on the rejection.
 */
export function resolveAtomText(proposed: string, authored: readonly string[]): AtomResolution {
  const trimmed = proposed.trim()
  const exact = authored.find((a) => a === trimmed)
    ?? authored.find((a) => a.toLowerCase() === trimmed.toLowerCase())
  if (exact !== undefined) return { ok: true, text: exact, via: 'exact' }
  const canonical = canonicalizeAtomSlug(trimmed)
  if (!canonical) return { ok: false, canonical: '', suggestions: [] }
  const byCanonical = authored.filter((a) => canonicalizeAtomSlug(a) === canonical)
  if (byCanonical.length === 1) return { ok: true, text: byCanonical[0], via: 'canonical' }
  if (byCanonical.length > 1) return { ok: false, canonical, suggestions: byCanonical.slice(0, 3) }
  return { ok: false, canonical, suggestions: suggestAtomTexts(canonical, authored) }
}

/** Ranked by shared-token count - for DM error responses and rejection logs. */
export function suggestAtomTexts(canonical: string, authored: readonly string[], max = 3): string[] {
  const proposedTokens = new Set(tokensOf(canonical))
  if (proposedTokens.size === 0) return []
  return authored
    .map((a) => ({
      a,
      shared: tokensOf(canonicalizeAtomSlug(a)).filter((t) => proposedTokens.has(t)).length,
    }))
    .filter((x) => x.shared > 0)
    .sort((x, y) => y.shared - x.shared)
    .slice(0, max)
    .map((x) => x.a)
}

export const MAX_LOCAL_ATOMS_PER_BEAT = 4

export interface AtomProposal {
  name: string
  kind: AtomKind
}

export interface RegisterResult {
  /** Brand-new local atoms to insert - label IS the canonical slug (code-normalized identity). */
  created: RegistryAtom[]
  /** Proposals that collide (canonically or near-miss) with an existing atom: reuse it. */
  reused: { proposed: string; atom: RegistryAtom }[]
  rejected: { proposed: string; reason: string }[]
  /** proposed name -> the label to use in predicates (created slug or reused label). */
  mapping: Map<string, string>
}

/**
 * Registers a beat's declared local atoms against the adventure's registry. A canonical-slug
 * collision with an existing SAME-KIND atom is a REUSE, not an error - the planner reaching
 * for a name that already exists should land on the authored atom. A collision across kinds
 * is a rejection (a flag and an event live in different evaluation namespaces; silently
 * fusing them mis-routes crediting). Nothing fuzzier than slug equality ever merges - see
 * the module header for why.
 */
export function registerLocalAtoms(proposals: AtomProposal[], existing: readonly RegistryAtom[]): RegisterResult {
  const result: RegisterResult = { created: [], reused: [], rejected: [], mapping: new Map() }
  const taken = new Map(existing.map((a) => [a.slug, a]))
  for (const proposal of proposals.slice(0, MAX_LOCAL_ATOMS_PER_BEAT)) {
    const slug = canonicalizeAtomSlug(proposal.name)
    if (!slug) {
      result.rejected.push({ proposed: proposal.name, reason: 'empty after canonicalization' })
      continue
    }
    if (result.mapping.has(proposal.name)) continue
    const collision = taken.get(slug)
    if (collision && collision.kind !== proposal.kind) {
      result.rejected.push({
        proposed: proposal.name,
        reason: `collides with existing ${collision.kind} atom "${collision.label}" - pick a distinct name`,
      })
      continue
    }
    if (collision) {
      result.reused.push({ proposed: proposal.name, atom: collision })
      result.mapping.set(proposal.name, collision.label)
      continue
    }
    // Label = the DECLARED name, verbatim. The slug is identity for uniqueness; the label is
    // what predicates and exact-string matching see. Canonicalizing the label broke shadow
    // mode's "legacy behavior exactly" contract: stored predicates held underscored variants
    // the legacy matcher could no longer hit ($0 suite, first deploy 2026-07-22).
    const atom: RegistryAtom = { slug, kind: proposal.kind, scope: 'local', label: proposal.name.trim() }
    result.created.push(atom)
    result.mapping.set(proposal.name, atom.label)
    taken.set(slug, atom)
  }
  for (const proposal of proposals.slice(MAX_LOCAL_ATOMS_PER_BEAT)) {
    result.rejected.push({ proposed: proposal.name, reason: `over the ${MAX_LOCAL_ATOMS_PER_BEAT}-atom cap` })
  }
  return result
}

/**
 * Rewrites every flag/event/fact atom in a predicate through the mapping (proposed -> resolved
 * label), so stored predicates only ever contain registry labels. Unknown atoms pass through -
 * validation upstream decides whether that is an error.
 */
export function rewritePredicateAtoms(predicate: unknown, mapping: ReadonlyMap<string, string>): unknown {
  if (typeof predicate !== 'object' || predicate === null || Array.isArray(predicate)) return predicate
  const p = predicate as Record<string, unknown>
  if (Array.isArray(p.any)) return { any: p.any.map((branch) => rewritePredicateAtoms(branch, mapping)) }
  if (Array.isArray(p.all)) return { all: p.all.map((branch) => rewritePredicateAtoms(branch, mapping)) }
  const rewrite = (key: 'flag' | 'event' | 'fact') => {
    const value = p[key]
    if (typeof value !== 'string') return p
    const mapped = mapping.get(value)
    return mapped === undefined || mapped === value ? p : { ...p, [key]: mapped }
  }
  if (typeof p.flag === 'string') return rewrite('flag')
  if (typeof p.event === 'string') return rewrite('event')
  if (typeof p.fact === 'string') return rewrite('fact')
  return predicate
}
