// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Beat Planner boundary parser (F08 SS4 + encounter-states Slice 3, two-call since the
// overhaul Phase 1): call 1 plans the beat and DECLARES its local atoms explicitly (the only
// door runtime atom creation has left); call 2 maps encounter outcome tiers onto a closed
// menu of registry atoms (parseOutcomeMaps). Exit conditions may only reference declared or
// objective atoms - free invention no longer parses.

import { validatePredicate } from '../guide/predicates.ts'
import type { Json } from '../state/types.ts'
import { canonicalizeAtomSlug, MAX_LOCAL_ATOMS_PER_BEAT, resolveAtomText } from './atoms.ts'
import type { AtomProposal } from './atoms.ts'

export interface IngredientRequest {
  type: 'clue' | 'secret' | 'event' | 'item' | 'rumor'
  purpose: string
  pillarTags: string[]
}

export interface BraidedPair {
  goalPair: [number, number]
  link: { kind: 'dc_mod' }
  /** Skills the two halves lean on - both must exist in the party for the pair to survive. */
  skills: [string, string]
}

export const ENCOUNTER_KINDS = ['skill_challenge', 'puzzle', 'social', 'combat'] as const
export type BeatEncounterKind = (typeof ENCOUNTER_KINDS)[number]

/** The beat's typed encounter (encounter-states Slice 3). `params` is designed later by the
 *  Encounter Designer; outcome-map entries are exact copies of authored milestone atoms. */
export interface BeatEncounterSpec {
  kind: BeatEncounterKind
  label: string
  stakes: string
  rationale: string
  params: Json
  onSuccess: string[]
  onPartial: string[]
  onFailure: string[]
}

/** A cast member the planner needs but the roster lacks (Phase 2 - the "Elara" fix). */
export interface NpcProposal {
  name: string
  personality: string
  role: 'npc'
}

export interface BeatPlan {
  name: string
  goals: string[]
  exitConditions: Json
  ingredientRequests: IngredientRequest[]
  braided: BraidedPair[]
  narrationSeed: string
  /** Null only via the deterministic fallback - the beat degrades to ad-hoc entries. */
  encounter: BeatEncounterSpec | null
  /** Local atoms this beat declares (Phase 1) - registered by code before anything stores them. */
  localAtoms: AtomProposal[]
  /** NPCs to create before staging (Phase 2); only honoured for social encounters. */
  createNpcs: NpcProposal[]
}

export const MAX_CREATED_NPCS_PER_BEAT = 2

export interface BeatPlanContext {
  partySize: number
  partySkills: string[]
  /** Authored milestone vocabulary (objective atoms) outcome maps may draw from, exact text. */
  milestones?: string[]
}

const INGREDIENT_TYPES = ['clue', 'secret', 'event', 'item', 'rumor'] as const
const PILLARS = new Set(['combat', 'social', 'exploration'])

export type BeatParseResult =
  | { ok: true; plan: BeatPlan; dropped: string[] }
  | { ok: false; errors: string[] }

/**
 * Braided pairs degrade softly (dropped + noted) - a beat with a bad pair is still a beat.
 * Everything else that fails validation is a hard error so the planner retries.
 */
export function parseBeatPlan(raw: unknown, ctx: BeatPlanContext): BeatParseResult {
  const errors: string[] = []
  const dropped: string[] = []
  if (typeof raw !== 'object' || raw === null) return { ok: false, errors: ['beat plan is not an object'] }
  const obj = raw as Record<string, unknown>
  const beat = (typeof obj.beat === 'object' && obj.beat !== null ? obj.beat : obj) as Record<string, unknown>

  const name = typeof beat.name === 'string' && beat.name.trim() ? beat.name.trim() : ''
  if (!name) errors.push('beat.name: expected a non-empty string')

  const goalsRaw = Array.isArray(beat.goals) ? beat.goals : []
  const goals = goalsRaw.filter((g): g is string => typeof g === 'string' && g.trim().length > 0).slice(0, 4)
  if (goals.length === 0) errors.push('beat.goals: expected 1-4 player-facing situations')

  // Declared local atoms (Phase 1): the planner names every new atom it wants, code registers
  // them. Same cap as registration - a parse that accepts more than registration will keep
  // lets exit validation bless an atom registration then rejects (review, 2026-07-22).
  const ATOM_KINDS = ['flag', 'event'] as const
  const localAtoms: AtomProposal[] = (Array.isArray(beat.new_local_atoms) ? beat.new_local_atoms : [])
    .slice(0, MAX_LOCAL_ATOMS_PER_BEAT)
    .flatMap((a) => {
      if (typeof a !== 'object' || a === null) return []
      const atom = a as Record<string, unknown>
      const kind = ATOM_KINDS.find((k) => k === atom.kind)
      if (!kind || typeof atom.name !== 'string' || !atom.name.trim()) return []
      return [{ name: atom.name.trim(), kind }]
    })

  let exitConditions: Json = null
  if (beat.exit_conditions != null) {
    // Coerce before validating. A bare {"flag":"x"} is unambiguous in a beat exit - eq:false
    // is unsatisfiable by writing atoms, so "true" is the only reading that means anything -
    // yet hard-failing it cost the WHOLE beat, which then degraded to a null-encounter
    // fallback the party cannot play (live 2026-07-23: 2 beat_planner_failures in one run,
    // both "a flag atom needs eq"). The guardrails repair what they can and only fail on what
    // they genuinely cannot read.
    const coerced = coercePredicateEq(beat.exit_conditions)
    const problems = validatePredicate(coerced)
    if (problems.length > 0) errors.push(...problems.map((p) => `beat.exit_conditions: ${p}`))
    else exitConditions = coerced as Json
  }
  // Exit atoms must be declared or authored - undeclared invention is the drift that produced
  // "found_expedition_journal" vs the objective's "lost_expedition_journal_found" (live
  // 2026-07-22). Canonical comparison, so case/punctuation variants of a declared name pass.
  if (exitConditions != null) {
    const known = new Set([
      ...(ctx.milestones ?? []).map((m) => canonicalizeAtomSlug(m)),
      ...localAtoms.map((a) => canonicalizeAtomSlug(a.name)),
    ])
    const undeclared = listPredicateAtomNames(exitConditions)
      .filter((name) => !known.has(canonicalizeAtomSlug(name)))
    if (undeclared.length > 0) {
      errors.push(
        `beat.exit_conditions: atoms neither declared in new_local_atoms nor from the objective ` +
          `milestones: ${undeclared.join(', ')} - declare every local atom you exit on`,
      )
    }
  }

  const ingredientRequests: IngredientRequest[] = (Array.isArray(beat.ingredient_requests) ? beat.ingredient_requests : [])
    .slice(0, 5)
    .flatMap((r) => {
      if (typeof r !== 'object' || r === null) return []
      const req = r as Record<string, unknown>
      const type = INGREDIENT_TYPES.find((t) => t === req.type)
      if (!type || typeof req.purpose !== 'string' || !req.purpose.trim()) return []
      const pillarTags = Array.isArray(req.pillar_tags)
        ? req.pillar_tags.filter((p): p is string => typeof p === 'string' && PILLARS.has(p))
        : []
      return [{ type, purpose: req.purpose.trim(), pillarTags }]
    })

  const partySkills = new Set(ctx.partySkills.map((s) => s.toLowerCase()))
  const braided: BraidedPair[] = []
  for (const b of Array.isArray(beat.braided) ? beat.braided : []) {
    if (typeof b !== 'object' || b === null) continue
    const pair = b as Record<string, unknown>
    const goalPair = Array.isArray(pair.goal_pair) ? pair.goal_pair.map(Number) : []
    const skills = Array.isArray(pair.skills) ? pair.skills.filter((s): s is string => typeof s === 'string') : []
    if (goalPair.length !== 2 || goalPair.some((i) => !Number.isInteger(i) || i < 0 || i >= goals.length) || goalPair[0] === goalPair[1]) {
      dropped.push('braided pair with invalid goal indexes')
      continue
    }
    if (ctx.partySize < 2) {
      dropped.push('braided pair (solo party)')
      continue
    }
    if (skills.length !== 2 || skills.some((s) => !partySkills.has(s.toLowerCase()))) {
      dropped.push(`braided pair needing skills the party lacks (${skills.join(', ') || 'unspecified'})`)
      continue
    }
    braided.push({ goalPair: [goalPair[0], goalPair[1]], link: { kind: 'dc_mod' }, skills: [skills[0], skills[1]] })
  }

  const narrationSeed = typeof beat.narration_seed === 'string' && beat.narration_seed.trim()
    ? beat.narration_seed.trim()
    : ''
  if (!narrationSeed) errors.push('beat.narration_seed: expected a non-empty string')

  const encounter = parseEncounterShell(beat.encounter, errors)

  // Requested cast (Phase 2). Only meaningful for social beats; the caller enforces that and
  // the flag. Dropped softly - a missing personality is not worth failing a whole beat over.
  const createNpcs: NpcProposal[] = (Array.isArray(beat.create_npcs) ? beat.create_npcs : [])
    .slice(0, MAX_CREATED_NPCS_PER_BEAT)
    .flatMap((n) => {
      if (typeof n !== 'object' || n === null) return []
      const npc = n as Record<string, unknown>
      const name = typeof npc.name === 'string' ? npc.name.trim() : ''
      if (!name) return []
      const personality = typeof npc.personality === 'string' ? npc.personality.trim() : ''
      return [{ name, personality, role: 'npc' as const }]
    })

  if (errors.length > 0) return { ok: false, errors }
  return {
    ok: true,
    plan: { name, goals, exitConditions, ingredientRequests, braided, narrationSeed, encounter, localAtoms, createNpcs },
    dropped,
  }
}

/**
 * Call 1 parses the encounter SHELL only (kind/label/stakes/rationale). Outcome maps moved to
 * call 2 (parseOutcomeMaps) so they can be schema-enum'd against a menu that includes the
 * atoms this very plan declared - the circularity that used to force free-text generation.
 */
function parseEncounterShell(raw: unknown, errors: string[]): BeatEncounterSpec | null {
  if (raw == null) {
    errors.push('beat.encounter: expected an encounter spec (kind, label, stakes, rationale)')
    return null
  }
  if (typeof raw !== 'object') {
    errors.push('beat.encounter: expected an object')
    return null
  }
  const enc = raw as Record<string, unknown>
  const kind = ENCOUNTER_KINDS.find((k) => k === enc.kind)
  if (!kind) errors.push(`beat.encounter.kind: expected one of ${ENCOUNTER_KINDS.join('|')}`)
  const label = typeof enc.label === 'string' && enc.label.trim() ? enc.label.trim() : ''
  if (!label) errors.push('beat.encounter.label: expected a non-empty string')
  if (errors.length > 0) return null
  return {
    kind: kind!,
    label,
    stakes: typeof enc.stakes === 'string' ? enc.stakes.trim() : '',
    rationale: typeof enc.rationale === 'string' ? enc.rationale.trim() : '',
    params: (enc.params ?? {}) as Json,
    onSuccess: [],
    onPartial: [],
    onFailure: [],
  }
}

/**
 * Fills in the omitted `eq: true` on bare flag/fact atoms, recursively. Purely additive: an
 * atom that already states its `eq` (either value) is untouched, so this can never flip a
 * deliberate eq:false into its opposite.
 */
export function coercePredicateEq(predicate: unknown): unknown {
  if (typeof predicate !== 'object' || predicate === null || Array.isArray(predicate)) return predicate
  const p = predicate as Record<string, unknown>
  if (Array.isArray(p.any)) return { any: p.any.map(coercePredicateEq) }
  if (Array.isArray(p.all)) return { all: p.all.map(coercePredicateEq) }
  const needsEq = (typeof p.flag === 'string' || typeof p.fact === 'string') &&
    p.eq === undefined && p.in === undefined
  return needsEq ? { ...p, eq: true } : predicate
}

/** Every atom NAME a predicate references, regardless of claimability (eq value). */
export function listPredicateAtomNames(predicate: unknown): string[] {
  const names = new Set<string>()
  const walk = (node: unknown): void => {
    if (typeof node !== 'object' || node === null || Array.isArray(node)) return
    const p = node as Record<string, unknown>
    if (Array.isArray(p.any)) return p.any.forEach(walk)
    if (Array.isArray(p.all)) return p.all.forEach(walk)
    for (const key of ['flag', 'event', 'fact'] as const) {
      if (typeof p[key] === 'string' && p[key]) names.add(p[key] as string)
    }
  }
  walk(predicate)
  return [...names]
}

export interface OutcomeMaps {
  onSuccess: string[]
  onPartial: string[]
  onFailure: string[]
  dropped: string[]
}

/**
 * Call 2's boundary: outcome-map entries resolve against the closed menu (registry labels).
 * The schema enum already constrains generation; this is the belt to that suspender - and the
 * canonical resolver means a case variant of a menu atom lands instead of dropping. Off-menu
 * entries are DROPPED, never fatal (a beat with a thin map still beats no beat); the caller
 * applies the deterministic spine fallback when on_success comes back empty.
 */
export function parseOutcomeMaps(raw: unknown, menu: readonly string[]): OutcomeMaps {
  const result: OutcomeMaps = { onSuccess: [], onPartial: [], onFailure: [], dropped: [] }
  if (typeof raw !== 'object' || raw === null) return result
  const obj = raw as Record<string, unknown>
  const read = (key: 'on_success' | 'on_partial' | 'on_failure', into: string[]) => {
    const list = Array.isArray(obj[key]) ? (obj[key] as unknown[]) : []
    for (const entry of list) {
      if (typeof entry !== 'string' || !entry.trim()) continue
      const resolution = resolveAtomText(entry, menu)
      if (resolution.ok && !into.includes(resolution.text)) into.push(resolution.text)
      else if (!resolution.ok) result.dropped.push(`${key} milestone "${entry}" (not on the menu)`)
    }
  }
  read('on_success', result.onSuccess)
  read('on_partial', result.onPartial)
  read('on_failure', result.onFailure)
  return result
}
