// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// The narrator echoing its own briefing back at the player (2026-07-29).
//
// publishNarration hands the model a LABELLED block - SCENE / GOAL / CAST / PARTY / SOFAR / LAST /
// KNOWN / EARLIER - because labelled data beats prose that re-teaches the rules every call. The
// risk that buys is that a weak model treats the labels as part of the document and continues it.
//
// Measured across 348 published narrations: 3 did exactly that (0.9%). One player was shown
//
//   CAST Dorya Salk - female Mirefleet resident, shopkeeper. // Hessik Var - male ...
//   PARTY Bram - human adventurer, level 1. // Kestrel - human adventurer, level 1.
//   SOFAR Bram and Kestrel arrive in Mirefleet. Dorya Salk offers them a job ...
//
// and later a bare `GOAL Uncover the harbour's hidden rot`. Rare, and the single most
// immersion-breaking thing in any transcript read this session - it shows the player the machine.
//
// CODE JUDGES, and it judges SHAPE, not meaning. No model is asked whether a line looks like
// scaffolding; the check is that the line opens with one of the exact tokens we emit. Two
// safeguards against eating real prose:
//
//   1. `LAST` and `EARLIER` are ordinary English words that can legitimately open a sentence
//      ("EARLIER, the tide had..."), so a lone one is kept. The others are not words a narrator
//      starts a paragraph with.
//   2. Two or more labelled lines is the block being continued wholesale, which no prose does.
//
// The observed leak had the labels padded to ONE space, not the two-to-three the block emits, so
// matching on alignment would have missed the very case this exists for. Match the token instead.

/** Labels that are never how a narrator opens a line of prose. */
const HARD_LABELS = ['SCENE', 'GOAL', 'CAST', 'PARTY', 'SOFAR', 'KNOWN']
/** Labels that are also ordinary words - only stripped as part of a run. */
const SOFT_LABELS = ['LAST', 'EARLIER']

const labelOf = (line: string): string | null => {
  const match = /^\s*([A-Z]{4,7})\s+\S/.exec(line)
  if (!match) return null
  const token = match[1]
  return HARD_LABELS.includes(token) || SOFT_LABELS.includes(token) ? token : null
}

export interface ContextEchoResult {
  /** The narration with any scaffolding lines removed. */
  text: string
  /** The labels that were stripped, for the incident payload. Empty when nothing was. */
  stripped: string[]
}

/**
 * Remove briefing lines the narrator copied into its own output.
 *
 * Never returns empty when the input was non-empty: if stripping would leave nothing at all, the
 * original is kept. A leaked label is ugly; a blank turn is the failure mode that has already cost
 * this codebase nine silent player actions, and it is strictly worse.
 */
export function stripContextEcho(text: string): ContextEchoResult {
  const lines = text.split('\n')
  const labelled = lines.map(labelOf)
  const hits = labelled.filter((l): l is string => l !== null)
  if (hits.length === 0) return { text, stripped: [] }

  const dropRun = hits.length >= 2
  const stripped: string[] = []
  const kept = lines.filter((_line, i) => {
    const label = labelled[i]
    if (!label) return true
    if (!dropRun && !HARD_LABELS.includes(label)) return true
    stripped.push(label)
    return false
  })
  if (stripped.length === 0) return { text, stripped: [] }

  const cleaned = kept.join('\n').replace(/\n{3,}/g, '\n\n').trim()
  if (cleaned.length === 0) return { text, stripped: [] }
  return { text: cleaned, stripped }
}
