// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Off-spine conversation limiting (owner-directed, 2026-07-27).
//
// THE PROBLEM. A party can talk indefinitely without the story moving, and nothing in the loop
// pushed back. Live: 23 turns, 14 `say` events, 11 social encounters opened, ONE beat, ZERO
// objectives. The spine was reachable the whole time and play simply never reached it - the
// conversation was more inviting than the task, so the run drained into it.
//
// WHY THE NPC IS THE RIGHT VEHICLE. The alternatives are all worse for the player: a system
// message breaks fiction, forcing the scene closed confiscates their turn, and the Progress
// Director's rungs are heavy machinery aimed at a party that is STUCK - this party is not stuck,
// it is chatting. An NPC declining to follow the tangent is what a real person at the table does,
// and it costs the player nothing but a beat.
//
// THE DIVISION OF LABOUR. Code decides WHEN and HOW HARD from a counter it already keeps
// (`turnsSinceProgress`). The NPC Agent writes the line, from the personality, wants and voice its
// row already carries - so the brush-off sounds like that specific person and not a stock refusal.
// Nothing here inspects what the player SAID; the trigger is structural, never a word signal.

/**
 * How firmly the NPC should steer back. Escalating, because a single deflection that goes
 * unheeded and never hardens is just a speed bump - and because a party that takes the hint on
 * the first nudge must never see the blunt version.
 */
export type DeflectLevel = 'none' | 'soft' | 'firm' | 'shut'

export interface DeflectInput {
  /** Turns since the spine last moved - the Progress Director's own counter. */
  turnsOffSpine: number
  /** Pacing threshold: turns of drift the difficulty allows before an NPC starts steering. */
  threshold: number
  /** Deflections already delivered in THIS stretch of no progress. */
  priorDeflections: number
  /**
   * True when this NPC still holds undiscovered authored content the CURRENT objective needs
   * (2026-07-30).
   *
   * Talking to the person who holds the clue is not drift - it is the spine, being played the only
   * way a mystery can be played. `turnsSinceProgress` cannot tell the difference, because a question
   * answered is not a state change, so the counter climbs while the party gets it exactly right.
   *
   * Run e87b3506: the party asked about the vial, the graves, Voss's instruction and the seal, and
   * learned the real plot from the answers. All seven turns were `fold_in`, none counted, the counter
   * reached 7, and this ladder took the NPC to `shut` for five consecutive turns - while
   * `reveal_blocked` fired twice on a clue gated behind "successful DC 12 persuasion" with that same
   * NPC. The system demanded progress through a door it had just closed.
   *
   * So a route-bearing NPC never hardens past `soft`. That is Rule 2 in one line: if canon says this
   * person holds the way forward, the affordance to talk to them must remain.
   */
  holdsRoute?: boolean
}

/**
 * The counter decides WHEN; how many brush-offs the party has already had decides HOW HARD.
 *
 * Both came off the turn counter at first, and the first live run showed why that is wrong: the
 * counter advances whether or not anyone is speaking, so a party that talks intermittently gets
 * `firm` as its opening contact and may never hear `soft` at all. Observed 2026-07-27 - three
 * deflections, two `firm` and one `shut`, not a single `soft` among them. The escalation is
 * supposed to be a conversation getting shorter, and that only works if the first one is gentle
 * no matter which turn it happens to land on.
 *
 * Deliberately shallow. By the time a party has ignored `shut` the Progress Director's own ladder
 * (reveal, replan, rescue) is already climbing, and a fourth rung would just be the DM nagging.
 *
 * AND `shut` SAYS ITS PIECE ONCE (2026-07-30). It used to be the terminal rung in the literal sense:
 * every deflection from the third onward returned it, for as long as the stretch lasted - and the
 * stretch can only end when the spine moves, which `shut` is the main thing preventing. In
 * e87b3506 that produced five consecutive turns of an NPC saying almost nothing. A nudge with no
 * ceiling is not a nudge, it is a wall, so after `shut` has landed the ladder settles back to `firm`:
 * still refusing the tangent, no longer refusing to speak.
 */
export function deflectLevel(input: DeflectInput): DeflectLevel {
  if (input.turnsOffSpine < Math.max(input.threshold, 1)) return 'none'
  if (input.priorDeflections <= 0) return 'soft'
  // Never harden the one channel the story runs through - see `holdsRoute`.
  if (input.holdsRoute) return 'soft'
  if (input.priorDeflections === 1) return 'firm'
  return input.priorDeflections === 2 ? 'shut' : 'firm'
}

/**
 * The directive handed to the NPC Agent. It says what to DO, never what to say - the words are the
 * NPC's, drawn from the personality and wants already in its context, so a gruff smuggler and a
 * grieving tavernkeeper brush the party off in recognisably different ways.
 */
export function deflectDirective(level: DeflectLevel, goal: string): string {
  if (level === 'none') return ''
  const task = goal.trim() ? `what actually needs doing: ${goal.trim()}` : 'what actually needs doing'
  if (level === 'soft') {
    return 'STEER BACK. This has drifted off what matters. Give the tangent no more than a passing ' +
      `word - you do not know, you would rather not, it is not the moment - and turn to ${task}. ` +
      'Stay warm and in character; you are redirecting, not scolding.'
  }
  if (level === 'firm') {
    return 'STEER BACK, PLAINLY. The drift has gone on. Decline the tangent outright in your own ' +
      `manner and say what you want to happen next, naming ${task}. One or two sentences. Do not ` +
      'answer the question they asked.'
  }
  return 'YOU ARE DONE TALKING. Say almost nothing - a few words, a look, a gesture, a trailing ' +
    `"..." - and put ${task} in front of them. No explanation, no new information, no invitation ` +
    'to keep the conversation going. This must read as the moment for talk closing, in your voice.'
}
