// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

export { ENCOUNTER_KINDS, parseBeatPlan } from './beats.ts'
export type {
  BeatEncounterKind, BeatEncounterSpec, BeatParseResult, BeatPlan, BeatPlanContext, BraidedPair,
  IngredientRequest,
} from './beats.ts'
export {
  MISMATCH_THRESHOLD, nextStreak, parsePivot, PIVOT_AUTO_CONFIDENCE, PIVOT_PROPOSE_CONFIDENCE,
  PIVOT_REEVALUATE_EVENTS, pivotHandling, streakTriggersClassifier,
} from './classifier.ts'
export type { PivotAssessment, PivotHandling } from './classifier.ts'
export {
  applyDialNudge, COMMIT_MIN_EVENTS, COMMIT_MIN_MARGIN, commitmentReady, DIAL_MAX, DIAL_MIN,
  ladderReady, parseEndingSignals, scoreEndings, SHORT_LADDER_MAX,
} from './endings.ts'
export type {
  EndingCandidate, EndingScores, EndingSignal, EndingSignalWhen, EndingWorld, ObjectiveLadder,
} from './endings.ts'
export { evaluatePredicate, listMilestoneAtoms } from './evaluate.ts'
export type { MilestoneAtoms, WorldFacts } from './evaluate.ts'
export {
  activeLoop, advanceBeat, completeLoop, pushLoop, resumeLoop, suspendLoop,
} from './loops.ts'
export type { LoopOpResult, LoopSeed } from './loops.ts'
export {
  canReweave, canStageOffer, MAX_OPEN_OFFERS, MAX_REWEAVES, negotiatedGold, offerBanner,
  openingTerms, parseOfferResponse, parseRewardBounds,
} from './offers.ts'
export { intentPillar, isOffLoop, LOOP_TEMPLATES } from './templates.ts'
export type { LoopTemplate, Pillar } from './templates.ts'
export { LOOP_TYPES } from './types.ts'
export type {
  BeatStatus, CoreLoop, LoopStatus, LoopType, OfferResponseKind, OfferStatus, OfferTerms,
  RewardBounds,
} from './types.ts'
export {
  COOP_FATIGUE_STREAK, computeVarietyFlags, dominantPillar, LOOP_TYPE_WINDOW, SAME_TYPE_LIMIT,
  SPOTLIGHT_MIN_INTENTS, SPOTLIGHT_SHARE, varietyGuidance,
} from './variety.ts'
export type { VarietyFlags, VarietyInput } from './variety.ts'
