// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Game machinery leaking into player-facing prose (2026-07-29).
//
// NARRATOR_BASE has said "Never mention dice, rolls, checks, or game mechanics" since it was
// written, and it still reaches the player:
//
//   "The failure clings to you like the foundry dust"                    (bac9f4b9 #5)
//   "The first setback already cost you... Now the second settles in"    (bc918319 #13)
//   "We need to earn your trust"  - the encounter LABEL, in an NPC's mouth (abd318e1)
//
// An instruction a model can quietly ignore is not a limit, so the guards that use this do what
// claimGuard and outcomeGuard do: detect deterministically, regenerate once, keep the prose if the
// retry is no better.
//
// DELIBERATELY NARROW. The first draft of this list included `encounter`, `objective`, `tier` and a
// bare `roll` - and "a chance encounter", "her objective was clear" and "the fog rolled in" are all
// good prose. It also lost its word boundaries in transit, so `roll` matched "rolled" inside
// "the mist rolled in", which would have fired a regeneration on innocent text constantly. Every
// term here has essentially no innocent use in second-person fantasy narration; anything arguable
// is left out, because a false positive costs a model call and a probably-worse second draft.
//
// `fail` and `failed` are NOT here: "you fail to shift it" is fine. It is `the failure` as a noun
// the player possesses that gives the game away.

const MECHANICAL_VOCAB = new RegExp(
  '\\b(?:' + [
    'the failure', 'a failure', 'setbacks?',
    'the check', 'a check', 'skill checks?',
    'dice', 'die roll', 'd20',
    'hit points?', 'HP', 'DC',
  ].join('|') + ')\\b',
  'i',
)

/** The offending term, or null when the passage is clean. */
export function mechanicalVocab(text: string): string | null {
  const hit = MECHANICAL_VOCAB.exec(text ?? '')
  return hit ? hit[0] : null
}

/**
 * A machine-facing label pasted into prose - the dynamic sibling of the above.
 *
 * `stripContextEcho` catches fixed tokens (CAST, PARTY, SOFAR). It cannot catch an encounter label
 * or an objective title, because those are different strings every adventure - and three narrations
 * in run abd318e1 ended with the literal sentence "Earn Netta Vasch's trust." We know every one of
 * these strings at call time, so the check is free.
 *
 * Only flags a label that is the passage's OWN closing sentence. A label mentioned mid-prose is
 * usually the scene being described legitimately ("she wants your help auditing the weighbridge");
 * one standing alone at the end is the machine's goal pasted on.
 */
export function trailingLabel(text: string, labels: readonly string[]): string | null {
  const body = (text ?? '').trim()
  if (body.length === 0) return null
  // Smart punctuation is normalised on BOTH sides. Caught by the test that mattered: the narrator
  // wrote "Earn Netta Vasch’s trust" with a curly apostrophe where the stored label has a
  // straight one, and a literal comparison missed the very leak this exists to catch.
  const flatten = (s: string) => s
    .replace(/[‘’ʼ]/g, "'")
    .replace(/[“”]/g, '"')
    .toLowerCase()
  const flatBody = flatten(body)
  for (const raw of labels) {
    const label = (raw ?? '').trim()
    if (label.length < 8) continue
    const tail = flatBody.slice(-(label.length + 2)).replace(/[.!?"'\s]+$/, '')
    if (tail.endsWith(flatten(label))) return label
  }
  return null
}
