// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Story-graph navigation (overhaul 2026-07-26). The runtime half of the authored graph: given
// the node just resolved (or none), which authored node plays next?
//
// This REPLACES per-turn beat planning. Everything here is a lookup over content the guide
// pipeline already authored and the reachability gate already proved finishable - no LLM, no
// invention, no repair. The director still decides WHEN to intervene (its rung ladder is
// unchanged); this decides WHERE that intervention lands.

/**
 * Pass or fail (owner decision, 2026-07-27). `partial` is gone: the guide authored zero partial
 * outcome maps and zero partial edges, so the tier only ever meant "credit nothing and route on".
 * Stored rows from before the change may still carry `partial` edges; they are simply never
 * matched, and the fall-through below handles them exactly as an unauthored tier.
 */
export type NavTier = 'full' | 'failed'

export interface NavTransition {
  on: NavTier
  toNodeKey: string | null
  arrivalContext: string
}

export interface NavNode {
  id: string
  key: string
  objectiveId: string
  index: number
  role: 'route' | 'rescue'
  transitions: NavTransition[]
}

export interface NavigateInput {
  /** Every authored node for the ACTIVE objective. */
  nodes: readonly NavNode[]
  /** The node that just resolved, if any (null when opening the objective's first node). */
  fromKey: string | null
  /** The tier `fromKey` resolved on. */
  tier: NavTier | null
  /** Node keys already played this objective - never replay one unless a transition says to. */
  usedKeys: readonly string[]
  /** Director escalation, when it is asking for a specific kind of move. */
  rung?: 'replan_beat' | 'guaranteed_route' | null
}

/**
 * `resolve` retires the objective. Two tiers, both of which ADVANCE the story (2026-07-27):
 * `completed` is the clean win, `failed` is "they got through it, and it cost them" - the
 * Adventurers League failure box, where the party proceeds to Part 2 with the alarm raised.
 *
 * Modelled as a distinct action rather than an optional field on `none` so no call site can read
 * the decision and forget the outcome.
 */
export type NavigateResult =
  | { action: 'open'; node: NavNode; arrivalContext: string; reason: NavReason }
  | { action: 'resolve'; outcome: 'completed' | 'failed'; reason: NavReason }

export type NavReason =
  | 'transition'      // the resolved node's authored edge
  | 'first'           // the objective's opening node
  | 'alternate'       // director rung 3: a different authored route
  | 'rescue'          // director rung 4: the guaranteed route
  | 'exhausted'       // every authored scene is spent - the objective resolves the hard way
  | 'objective_done'  // the authored edge says the objective resolves here

const byIndex = (a: NavNode, b: NavNode) => a.index - b.index

/**
 * Deterministic: same inputs, same node. Order of precedence -
 * 1. A director rescue request goes straight to the rescue node.
 * 2. A director replan request takes the cheapest UNUSED route node.
 * 3. Otherwise follow the resolved node's authored transition for its tier.
 * 4. With nothing resolved yet, open the objective's first route node.
 *
 * THE TERMINATION GUARANTEE (2026-07-27). Every branch below ends in either `open` or `resolve` -
 * there is no third answer, so an objective cannot be left hanging. A party that fails everything
 * runs out of scenes and the objective resolves `failed`, which advances the story exactly like a
 * win does. This is what makes the main spine unstallable BY CONSTRUCTION rather than by a lint
 * rule, and it is why the prover no longer needs to ask whether an objective is winnable.
 */
export function nextNode(input: NavigateInput): NavigateResult {
  const routes = input.nodes.filter((n) => n.role === 'route').sort(byIndex)
  const rescue = input.nodes.find((n) => n.role === 'rescue') ?? null
  const used = new Set(input.usedKeys)

  if (input.rung === 'guaranteed_route') {
    // `!used` matters: without it the director's last rung re-opens a rescue the party already
    // played and lost, forever. Re-running a scene they have seen is not a way through.
    return rescue && !used.has(rescue.key)
      ? { action: 'open', node: rescue, arrivalContext: '', reason: 'rescue' }
      : { action: 'resolve', outcome: 'failed', reason: 'exhausted' }
  }

  if (input.rung === 'replan_beat') {
    const fresh = routes.find((n) => !used.has(n.key))
    if (fresh) return { action: 'open', node: fresh, arrivalContext: '', reason: 'alternate' }
    // Every authored route has been played; the rescue is what is left.
    return rescue && !used.has(rescue.key)
      ? { action: 'open', node: rescue, arrivalContext: '', reason: 'rescue' }
      : { action: 'resolve', outcome: 'failed', reason: 'exhausted' }
  }

  if (input.fromKey && input.tier) {
    const from = input.nodes.find((n) => n.key === input.fromKey)
    const edge = from?.transitions.find((t) => t.on === input.tier)
    if (edge) {
      if (edge.toNodeKey === null) {
        // A null target on the SUCCESS tier is the authored graph saying "the objective resolves
        // here". Passing ANY authored scene wins the objective - the routes are alternative ways
        // through, not steps to accumulate (BG3's persuade/intimidate/bribe converging on one
        // state transition).
        //
        // On a FAILURE tier it says nothing of the sort, and reading it as "resolved" would end
        // the objective on the party's first flub while two unplayed routes sat there. Live
        // 2026-07-26, three of five resolutions came in failed, every one of them awarded zero
        // milestones, and one objective arrived at this same dead end THREE times - identical
        // `used` list each time. A failure routes somewhere else while somewhere else exists;
        // only when nothing is left does it resolve, and the fall-through below owns that.
        if (input.tier === 'full') return { action: 'resolve', outcome: 'completed', reason: 'objective_done' }
      } else {
        const target = input.nodes.find((n) => n.key === edge.toNodeKey)
        // Never send them back to a scene they have already played. Authored edges routinely form
        // 2-cycles (n0 fails -> n1, n1 fails -> n0), and following them blindly traps the party:
        // live 2026-07-26 one node resolved FOURTEEN times, 14 of 21 resolutions were failures, and
        // the run took 75 turns to finish a single objective. Ad-hoc drift used to hide this; once
        // the director held the party to the spine, the spine itself became the cage. A replayed
        // scene is not a route - fall through to something they have not seen.
        if (target && !used.has(target.key)) {
          return { action: 'open', node: target, arrivalContext: edge.arrivalContext, reason: 'transition' }
        }
      }
    }
    // No authored edge for this tier, a failure tier whose edge went nowhere, a target the gate
    // should have caught, or an edge pointing back at a scene already played: fall through to the
    // next unplayed route rather than stranding the party - or looping them.
    const fresh = routes.find((n) => !used.has(n.key))
    if (fresh) return { action: 'open', node: fresh, arrivalContext: '', reason: 'alternate' }
    // Every authored route is spent. The rescue exists for exactly this moment - reaching for it
    // here is what stops a failing party circling instead of being handed a way through.
    return rescue && !used.has(rescue.key)
      ? { action: 'open', node: rescue, arrivalContext: '', reason: 'rescue' }
      // Nothing authored is left. The objective resolves the hard way and the story moves on -
      // never a stall. This is the terminal the whole ladder funnels into.
      : { action: 'resolve', outcome: 'failed', reason: 'exhausted' }
  }

  const first = routes.find((n) => !used.has(n.key))
  if (first) return { action: 'open', node: first, arrivalContext: '', reason: 'first' }
  // Nothing resolved yet, but every route has been played - reach for the rescue before giving up
  // on the objective. This branch used to return `exhausted` and stop, which was harmless when
  // `exhausted` opened nothing; now that it RETIRES the objective, skipping an unplayed rescue
  // here would throw away the ladder's terminal scene.
  if (rescue && !used.has(rescue.key)) {
    return { action: 'open', node: rescue, arrivalContext: '', reason: 'rescue' }
  }
  return { action: 'resolve', outcome: 'failed', reason: 'exhausted' }
}

/** Has this objective any authored node left to play? Feeds route-health's `spent` verdict. */
export function hasPlayableNode(nodes: readonly NavNode[], usedKeys: readonly string[]): boolean {
  const used = new Set(usedKeys)
  return nodes.some((n) => !used.has(n.key))
}
