// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Who can actually take the stage (overhaul Phase 2). Liveness used to be checked only at
// OPEN time, deep inside openSocialEncounter - so a beat could be planned around a dead
// collective ("Lost Expedition") or an NPC that exists only in prose ("Elara"), and the
// encounter simply failed to open forever after. Live 2026-07-22, Below the Sunken Chapel:
// the adventure shipped with two NPCs, one dead and one absent, and the social route to the
// active objective could never open - a permanently unwinnable story.
//
// Plan time is the right time: an encounter that cannot be staged NOW must not be persisted.

export type NpcLiveState = 'alive' | 'dead' | 'absent' | string

export interface NpcStageRow {
  id: string
  name: string
  /** Guide-authored starting state; live state overrides it. */
  initialState?: NpcLiveState | null
  /** Throwaway background NPCs (F10 SS4) - real cast only for staging candidates. */
  generated?: boolean | null
}

/** Live npcStates wins over the authored initial_state; absent from both means alive. */
export function npcStateOf(
  npc: Pick<NpcStageRow, 'id' | 'initialState'>,
  liveStates: Readonly<Record<string, string>>,
): NpcLiveState {
  return liveStates[npc.id] ?? npc.initialState ?? 'alive'
}

export function isStageable(
  npc: Pick<NpcStageRow, 'id' | 'initialState'>,
  liveStates: Readonly<Record<string, string>>,
): boolean {
  const state = npcStateOf(npc, liveStates)
  return state !== 'dead' && state !== 'absent'
}

/**
 * Everyone who could be staged right now. `excludeIds` drops NPCs already on stage;
 * `namedOnly` drops generated bystanders (the stall promoter and the beat planner both want
 * real cast, not the barkeep invented three turns ago).
 */
export function stageableNpcs(
  rows: readonly NpcStageRow[],
  liveStates: Readonly<Record<string, string>>,
  opts?: { excludeIds?: readonly string[]; namedOnly?: boolean },
): NpcStageRow[] {
  const excluded = new Set(opts?.excludeIds ?? [])
  return rows.filter((n) =>
    n.name.trim().length > 0 &&
    !excluded.has(n.id) &&
    !(opts?.namedOnly && n.generated) &&
    isStageable(n, liveStates))
}

/**
 * Which staged NPC the party just addressed by name, when that is unambiguous.
 *
 * `handleSay` has always answered as `speakers[0]` - its `targetNpcId` parameter exists but no
 * caller has ever passed it - so the first NPC staged replies to everything. Live 2026-07-23,
 * The Long Road to Emberfall: the party asked Elias Thorne four questions and Thorne's Contact
 * answered every one of them on his behalf, then slid into first person ("Just get HIM to the
 * Assizes" became "just get ME to the Assizes"). That pronoun collapse is what tripped the
 * consistency checker.
 *
 * This is entity resolution against a closed, code-owned roster - matching a proper name, not
 * interpreting meaning - so it stays deterministic. Ambiguity (nobody named, or two staged NPCs
 * both named) returns null and the caller keeps its existing default: a wrong confident guess
 * is worse than the status quo.
 */
export function addressedNpcId(
  utterance: string,
  staged: readonly { npcId: string; name: string }[],
): string | null {
  if (staged.length < 2) return null // one speaker on stage - nothing to disambiguate
  const haystack = ` ${utterance.toLowerCase()} `
  const named = staged.filter((s) => {
    const name = s.name.toLowerCase().trim()
    if (!name) return false
    // Whole-word containment, so "Sil" does not match "Silas" and a name at the end of a
    // sentence ("...ask Silas.") still resolves.
    return new RegExp(`(^|[^a-z])${name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}([^a-z]|$)`).test(haystack)
  })
  return named.length === 1 ? named[0].npcId : null
}

/**
 * Resolves LLM-provided NPC names to rows, exact-then-substring (the historical matcher),
 * restricted to the candidates given - so a caller that passes only stageable NPCs cannot
 * resolve a name onto a corpse. Returns ids in the order the names were provided, deduped.
 */
export function resolveNpcNames(
  names: readonly string[],
  candidates: readonly NpcStageRow[],
  limit = 3,
): { ids: string[]; unresolved: string[] } {
  const norm = (s: string) => s.toLowerCase().trim()
  const ids: string[] = []
  const unresolved: string[] = []
  for (const name of names) {
    const target = norm(name)
    if (!target) continue
    const match = candidates.find((c) => norm(c.name) === target)
      ?? candidates.find((c) => norm(c.name).includes(target) || target.includes(norm(c.name)))
    if (!match) unresolved.push(name)
    else if (!ids.includes(match.id)) ids.push(match.id)
  }
  return { ids: ids.slice(0, limit), unresolved }
}
