// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// F08 story-loop contracts (SS2 + SS2.1): loop stack rows and quest-offer shapes. Plain data
// only - these modules run under Vitest, the frontend bundle, and the Deno edge runtime
// (relative imports with explicit .ts extensions, no platform APIs).

export const LOOP_TYPES = [
  'mystery', 'monster_hunt', 'dungeon_crawl', 'siege_defense', 'infiltration',
  'intrigue', 'rebellion', 'survival', 'escort', 'heist', 'custom',
] as const

export type LoopType = (typeof LOOP_TYPES)[number]

export type LoopStatus = 'active' | 'suspended' | 'completed'

/** One core loop on the stack (F08 SS2). Suspensions preserve currentBeatId. */
export interface CoreLoop {
  id: string
  type: LoopType
  status: LoopStatus
  stackPosition: number
  currentBeatId: string | null
  customLabel: string | null
}

export type BeatStatus = 'planned' | 'active' | 'completed'

/** Offer terms as currently offered/accepted (F08 SS2.1) - gold is the negotiated value. */
export interface OfferTerms {
  gold: number
  extras: string[]
  stakes: string
  deadlineDays: number | null
}

export type OfferStatus = 'offered' | 'accepted' | 'declined' | 'expired'

/** Authored negotiation bounds from the quest contract (F04 SS4.3). */
export interface RewardBounds {
  goldFloor: number
  goldCeiling: number
  extras: string[]
}

/** How the party's free-text response to an open offer classifies (F08 SS2.1). */
export type OfferResponseKind = 'accept' | 'decline' | 'negotiate' | 'unrelated'
