// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Stage 7 - Consistency pass, whole guide: plot-hole scan across the hidden descriptions.
// Since 2026-07-22 the pass also REPAIRS what it can: each row-targeted warning gets one
// constrained rewrite of that row's text fields, then the check re-runs and only the residue
// ships as warnings. This amends F04 SS2's "never silent rewrites" on its own terms - rewrites
// are LOUD (every repair logs a guide_repair event with before/after), human_edited rows are
// never touched, and anything unresolved still warns. An empty warning list is a valid result.

import { Check, countWords, extractJsonObject } from '../json.ts'
import { entityNameMatches } from './stage4.ts'
import { OBJECTIVE_TITLE_MAX_WORDS } from './stage3.ts'
import type { GuideDigest } from './stage6.ts'
import type { EntityRef, ParseResult, WarningDraft } from '../types.ts'

/**
 * F04 SS2.1: deterministic (non-LLM) check run alongside the consistency pass - flags every
 * GLOBAL registry entity that never landed in any chapter's entity list nor as a content row.
 * Warnings, not failures: chapter coverage is stage 4's hard check; this catches globals the
 * chapter lists dropped.
 */
export function validateRegistryCoverage(
  globalEntities: EntityRef[],
  chapterEntities: EntityRef[],
  npcNames: string[],
  locationNames: string[],
): string[] {
  const warnings: string[] = []
  for (const entity of globalEntities) {
    const rowPool = entity.kind === 'npc' ? npcNames : locationNames
    const covered =
      rowPool.some((name) => entityNameMatches(name, entity.name)) ||
      chapterEntities.some((e) => e.kind === entity.kind && entityNameMatches(e.name, entity.name))
    if (!covered) {
      warnings.push(
        `Registry ${entity.kind} "${entity.name}" (${entity.note}) is named in the story spine but never appears in any chapter or content row.`,
      )
    }
  }
  return warnings
}

export function buildStage7Prompt(
  digest: GuideDigest,
  metaLoopArc: string,
): { system: string; user: string; maxTokens: number } {
  const system = `You are the Consistency Checker for a tabletop RPG platform. Scan an adventure guide's hidden scaffolding for plot holes and contradictions. You NEVER rewrite content - you only flag problems.

Look for:
- Contradictions between chapter arcs, objective hidden descriptions, and the meta loop.
- Objectives whose completion predicates reference NPCs/locations/flags that nothing establishes.
- Dead-end knowledge: information the players can never plausibly reach.
- Timeline impossibilities (an NPC in two places, an event before its cause).
- Spoiling titles: objective titles that give away a twist their hidden description relies on.

Report each problem against the most specific handle you can. If the guide is coherent, return an empty list - do not invent problems.

Respond with ONLY a JSON object, no prose, in exactly this shape:
{ "warnings": [ { "target": "obj#3" | "npc#1" | null, "message": "one-sentence problem statement" } ] }`

  const lines = (m: Map<string, string>) => [...m.entries()].map(([h, l]) => `${h}: ${l}`).join('\n')
  const user = `Meta loop arc: ${metaLoopArc}

Objectives:
${lines(digest.objectives)}

NPCs:
${lines(digest.npcs)}

Locations:
${lines(digest.locations)}

Ingredients:
${lines(digest.ingredients)}`

  return { system, user, maxTokens: 2500 }
}

export function parseStage7(raw: string, digest: GuideDigest): ParseResult<WarningDraft[]> {
  const extracted = extractJsonObject(raw)
  if (!extracted.ok) return extracted

  const c = new Check()
  const known = new Set([
    ...digest.objectives.keys(),
    ...digest.npcs.keys(),
    ...digest.locations.keys(),
    ...digest.ingredients.keys(),
  ])

  const warnings: WarningDraft[] = c.arr(extracted.data.warnings ?? [], '$.warnings', 0, 40).map((raw, i) => {
    const path = `$.warnings[${i}]`
    const w = c.obj(raw, path)
    let targetHandle: string | null = null
    if (w.target != null) {
      targetHandle = c.str(w.target, `${path}.target`)
      // An unknown handle degrades to a guide-level warning rather than failing the stage - the
      // message is still useful even when the model fumbles the pointer.
      if (targetHandle && !known.has(targetHandle)) targetHandle = null
    }
    return { targetHandle, message: c.str(w.message, `${path}.message`) }
  })

  return c.result(warnings)
}

/**
 * The fields the repair pass may rewrite, per table - the whole repair vocabulary. Mostly
 * text; `chapter` is the one STRUCTURAL move (2026-07-22, user-directed): placement findings
 * ("the boss belongs at the end, not chapter 1") were the most common residue and their fix
 * is mechanical - a chapter_id update - not a judgment call. Anything beyond these (new rows,
 * merges, predicate surgery) stays a warning. `text` on ingredients is logical: the edge maps
 * it onto content.text, where rumor/clue prose actually lives.
 */
export const REPAIRABLE_FIELDS: Record<string, string[]> = {
  objectives: ['title', 'hidden_description', 'chapter'],
  npcs: ['description', 'chapter'],
  locations: ['description', 'chapter'],
  ingredients: ['text', 'reveals'],
}

export interface Stage7Repair {
  resolvable: boolean
  patch: Record<string, string>
  note: string
}

export function buildStage7RepairPrompt(ctx: {
  handle: string
  table: string
  /** EVERY warning targeting this row - one repair reconciles them all, so parallel repairs
   *  never race on the same row (two same-row repairs clobbered each other, live 2026-07-22). */
  warnings: string[]
  /** The offending row's current repairable fields, verbatim. */
  fields: Record<string, string>
  digest: GuideDigest
  metaLoopArc: string
  /** The adventure's chapters, in order - the legal targets for a chapter move. */
  chapters: { number: number; title: string }[]
}): { system: string; user: string; maxTokens: number } {
  const canMoveChapter = (REPAIRABLE_FIELDS[ctx.table] ?? []).includes('chapter')
  const system = `You repair the flagged inconsistencies of ONE row in a tabletop RPG adventure guide by rewriting only that row's fields. Resolve ALL the listed warnings in a single coherent rewrite. You are the same consistency discipline that guards live play, applied at authoring time: reconcile the words with established canon, never invent around it.

Resolve in the direction of the BETTER STORY:
- Keep twists hidden. An objective title must stay open and spoiler-free (AT MOST ${OBJECTIVE_TITLE_MAX_WORDS} words) - move the secret into hidden_description, never the other way.
- Re-point dangling references at entities and places that EXIST in the canon below. Never invent a new named person, place, or faction.
- Keep the row's flavor, tone, and specificity - a repair that flattens the writing is a failure.
- Keep each field roughly its original length, and NEVER leave a sentence unfinished - a cut-off word is worse than the warning it fixed.
- Never contradict any other line of the canon while fixing this one.${canMoveChapter ? `
- When a warning is about TIMING or PLACEMENT (a boss surfacing too early, a climax listed in chapter 1, content belonging later), the right fix is usually the "chapter" field: the chapter NUMBER this row belongs in${ctx.table === 'objectives' ? '' : ', or "global" for a presence that spans the whole adventure'}. Pair a move with any text edits the new placement needs.` : ''}

If rewriting these fields alone cannot resolve the warnings (they need new rows, merges, or predicate changes), say so honestly.

Respond with ONLY a JSON object, no prose, in exactly this shape:
{ "resolvable": true|false, "patch": { "<field>": "new text" }, "note": "one line: what changed and why" }
patch may only use these fields: ${(REPAIRABLE_FIELDS[ctx.table] ?? []).join(', ')}. When resolvable is false, patch is {}.`

  const lines = (m: Map<string, string>) => [...m.entries()].map(([h, l]) => `${h}: ${l}`).join('\n')
  const user = `Warnings to resolve (all about ${ctx.handle}):
${ctx.warnings.map((w) => `- ${w}`).join('\n')}

Current content of ${ctx.handle} (${ctx.table}):
${Object.entries(ctx.fields).map(([f, v]) => `${f}: ${v}`).join('\n')}

Chapters: ${ctx.chapters.map((c) => `${c.number}: ${c.title}`).join(' | ') || 'one-shot (single chapter)'}

Meta loop arc: ${ctx.metaLoopArc}

Established canon (repairs must fit ALL of this):
Objectives:
${lines(ctx.digest.objectives)}

NPCs:
${lines(ctx.digest.npcs)}

Locations:
${lines(ctx.digest.locations)}

Ingredients:
${lines(ctx.digest.ingredients)}`

  return { system, user, maxTokens: 900 }
}

export function parseStage7Repair(raw: string, table: string, chapterCount: number): ParseResult<Stage7Repair> {
  const extracted = extractJsonObject(raw)
  if (!extracted.ok) return extracted

  const c = new Check()
  const resolvable = extracted.data.resolvable === true
  const allowed = new Set(REPAIRABLE_FIELDS[table] ?? [])
  const patch: Record<string, string> = {}
  const rawPatch = extracted.data.patch
  if (resolvable) {
    if (typeof rawPatch !== 'object' || rawPatch === null || Array.isArray(rawPatch)) {
      c.errors.push('$.patch: expected an object of field -> new text')
    } else {
      for (const [field, value] of Object.entries(rawPatch as Record<string, unknown>)) {
        if (!allowed.has(field)) {
          c.errors.push(`$.patch.${field}: not a repairable field of ${table} (allowed: ${[...allowed].join(', ')})`)
          continue
        }
        // A chapter move: a number ("3") or, for cast that spans the story, "global". Models
        // sometimes emit bare numbers - accept those too before the string checks reject them.
        if (field === 'chapter') {
          const text = typeof value === 'number' ? String(value) : typeof value === 'string' ? value.trim().toLowerCase() : ''
          const number = Number(text)
          if (text === 'global' && table !== 'objectives') {
            patch.chapter = 'global'
          } else if (Number.isInteger(number) && number >= 1 && number <= chapterCount) {
            patch.chapter = String(number)
          } else {
            c.errors.push(
              `$.patch.chapter: expected a chapter number 1-${chapterCount}${table !== 'objectives' ? ' or "global"' : ' (objectives always belong to a chapter)'}, got "${String(value)}"`,
            )
          }
          continue
        }
        if (typeof value !== 'string' || !value.trim()) {
          c.errors.push(`$.patch.${field}: expected non-empty replacement text`)
          continue
        }
        if (table === 'objectives' && field === 'title' && countWords(value) > OBJECTIVE_TITLE_MAX_WORDS) {
          c.errors.push(`$.patch.title: "${value}" is over ${OBJECTIVE_TITLE_MAX_WORDS} words - titles stay short and open`)
          continue
        }
        patch[field] = value.trim()
      }
    }
    if (c.errors.length === 0 && Object.keys(patch).length === 0) {
      c.errors.push('$.patch: resolvable is true but no valid field was patched - repair something or say resolvable: false')
    }
  }

  const note = typeof extracted.data.note === 'string' ? extracted.data.note.slice(0, 200) : ''
  return c.result({ resolvable: resolvable && Object.keys(patch).length > 0, patch, note })
}
