// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Stage 7 - Consistency pass, whole guide: plot-hole scan across the hidden descriptions.
// Since 2026-07-22 the pass also REPAIRS what it can: each row-targeted warning gets one
// constrained rewrite of that row's text fields, then the check re-runs and only the residue
// ships as warnings. This amends F04 SS2's "never silent rewrites" on its own terms - rewrites
// are LOUD (every repair logs a guide_repair event with before/after), human_edited rows are
// never touched, and anything unresolved still warns. An empty warning list is a valid result.

import { Check, countWords, extractJsonObject, looksCutOff } from '../json.ts'
import { validatePredicate } from '../predicates.ts'
import { entityNameMatches } from './stage4.ts'
import { containsFactAtom, hasClaimableAtom, OBJECTIVE_TITLE_MAX_WORDS } from './stage3.ts'
import type { GuideDigest } from './stage6.ts'
import type { EntityRef, ParseResult, WarningDraft } from '../types.ts'

/**
 * F04 SS2.1: deterministic (non-LLM) check run alongside the consistency pass - flags every
 * GLOBAL registry entity that never landed in any chapter's entity list nor as a content row.
 * Warnings, not failures: chapter coverage is stage 4's hard check; this catches globals the
 * chapter lists dropped.
 */
export function validateRegistryCoverage(
  globalEntities: EntityRef[],
  chapterEntities: EntityRef[],
  npcNames: string[],
  locationNames: string[],
): string[] {
  const warnings: string[] = []
  for (const entity of globalEntities) {
    const rowPool = entity.kind === 'npc' ? npcNames : locationNames
    const covered =
      rowPool.some((name) => entityNameMatches(name, entity.name)) ||
      chapterEntities.some((e) => e.kind === entity.kind && entityNameMatches(e.name, entity.name))
    if (!covered) {
      warnings.push(
        `Registry ${entity.kind} "${entity.name}" (${entity.note}) is named in the story spine but never appears in any chapter or content row.`,
      )
    }
  }
  return warnings
}

export function buildStage7Prompt(
  digest: GuideDigest,
  metaLoopArc: string,
): { system: string; user: string; maxTokens: number } {
  const system = `You are the Consistency Checker for a tabletop RPG platform. Scan an adventure guide's hidden scaffolding for plot holes and contradictions. You NEVER rewrite content - you only flag problems.

Look for:
- Contradictions between chapter arcs, objective hidden descriptions, and the meta loop.
- Objectives whose completion predicates reference NPCs/locations/flags that nothing establishes.
- Dead-end knowledge: information the players can never plausibly reach.
- Timeline impossibilities (an NPC in two places, an event before its cause).
- Spoiling titles: objective titles that give away a twist their hidden description relies on.

Report each problem against the most specific handle you can. If the guide is coherent, return an empty list - do not invent problems.

Rate each finding's severity honestly:
- "major": a contradiction, an impossibility, unreachable content, or something that would break play - a creator MUST look at it.
- "minor": clarity, polish, or could-be-tighter observations - worth recording, not worth interrupting anyone.

Respond with ONLY a JSON object, no prose, in exactly this shape:
{ "warnings": [ { "target": "obj#3" | "npc#1" | null, "severity": "major"|"minor", "message": "one-sentence problem statement" } ] }`

  const lines = (m: Map<string, string>) => [...m.entries()].map(([h, l]) => `${h}: ${l}`).join('\n')
  const user = `Meta loop arc: ${metaLoopArc}

Objectives:
${lines(digest.objectives)}

NPCs:
${lines(digest.npcs)}

Locations:
${lines(digest.locations)}

Ingredients:
${lines(digest.ingredients)}`

  return { system, user, maxTokens: 2500 }
}

export function parseStage7(raw: string, digest: GuideDigest): ParseResult<WarningDraft[]> {
  const extracted = extractJsonObject(raw)
  if (!extracted.ok) return extracted

  const c = new Check()
  const known = new Set([
    ...digest.objectives.keys(),
    ...digest.npcs.keys(),
    ...digest.locations.keys(),
    ...digest.ingredients.keys(),
  ])

  const warnings: WarningDraft[] = c.arr(extracted.data.warnings ?? [], '$.warnings', 0, 40).map((raw, i) => {
    const path = `$.warnings[${i}]`
    const w = c.obj(raw, path)
    let targetHandle: string | null = null
    if (w.target != null) {
      targetHandle = c.str(w.target, `${path}.target`)
      // An unknown handle degrades to a guide-level warning rather than failing the stage - the
      // message is still useful even when the model fumbles the pointer.
      if (targetHandle && !known.has(targetHandle)) targetHandle = null
    }
    // Unrated findings count as major - the popup over-asking beats a contradiction hiding
    // in the collapsed list.
    const severity = w.severity === 'minor' ? 'minor' as const : 'major' as const
    return { targetHandle, message: c.str(w.message, `${path}.message`), severity }
  })

  return c.result(warnings)
}

/**
 * The fields the repair pass may rewrite, per table - the whole repair vocabulary. Mostly
 * text; `chapter` is the one STRUCTURAL move (2026-07-22, user-directed): placement findings
 * ("the boss belongs at the end, not chapter 1") were the most common residue and their fix
 * is mechanical - a chapter_id update - not a judgment call. Anything beyond these (new rows,
 * merges, predicate surgery) stays a warning. `text` on ingredients is logical: the edge maps
 * it onto content.text, where rumor/clue prose actually lives.
 */
export const REPAIRABLE_FIELDS: Record<string, string[]> = {
  objectives: ['title', 'hidden_description', 'chapter', 'completion_predicates'],
  npcs: ['description', 'chapter'],
  locations: ['description', 'chapter'],
  ingredients: ['text', 'reveals'],
}

export interface Stage7Edit {
  /** Present on EDIT entries: the digest handle of the row being changed. */
  handle?: string
  patch: Record<string, string>
  /** Present on CREATE entries: a missing spine entity authored into existence (registry
   *  coverage findings - the most common residue - are fixed by creation, not editing). */
  create?: { kind: 'npc' | 'location'; name: string; description: string; chapter: string }
  note: string
}

/** Handle grammar is the digest's own (obj#1, npc#2, ...) - the table is derivable, so the
 *  edit plan needs no separate table field the model could get wrong. */
export function handleTable(handle: string): string | null {
  if (/^obj#\d+$/.test(handle)) return 'objectives'
  if (/^npc#\d+$/.test(handle)) return 'npcs'
  if (/^loc#\d+$/.test(handle)) return 'locations'
  if (/^ing#\d+$/.test(handle)) return 'ingredients'
  return null
}

/** Edits per plan - enough to align a whole contradiction cluster, bounded for the worker. */
export const EDIT_PLAN_CAP = 12

/**
 * ONE call per repair round, planning typed edits across EVERY flagged row (user-directed
 * 2026-07-22, "function calling"): per-row repairs could not fix contradiction CLUSTERS - five
 * findings that were all facets of one meta-loop conflict needed every affected row aligned to
 * one interpretation - and fanning per-row calls out in parallel tripped the edge runtime's
 * concurrent-fetch ceiling (7 parallel repairs, 0 completed, live 2026-07-22). The plan is
 * function calling semantically: typed operations, schema-validated here, executed server-side
 * through the guarded apply path.
 */
export function buildStage7EditPlanPrompt(ctx: {
  /** Row-targeted findings, each with the handle it is about. */
  warnings: { handle: string; message: string }[]
  /** Findings with no row (registry coverage, guide-level) - fixable only by creation. */
  rowlessWarnings: string[]
  /** Current contents of every flagged row, keyed by handle. */
  rows: { handle: string; table: string; fields: Record<string, string> }[]
  digest: GuideDigest
  metaLoopArc: string
  chapters: { number: number; title: string }[]
}): { system: string; user: string; maxTokens: number } {
  const system = `You are the guide editor for a tabletop RPG platform. Consistency findings are listed against an adventure guide; fix them by EDITING the flagged rows' fields. Plan ALL edits together - you may edit multiple rows, and findings often share one ROOT contradiction: choose ONE coherent interpretation (prefer the meta loop's framing) and edit EVERY affected row to match it. A partial alignment leaves the contradiction alive.

Rules, in the direction of the BETTER STORY:
- Keep twists hidden. An objective title stays open and spoiler-free (AT MOST ${OBJECTIVE_TITLE_MAX_WORDS} words) - secrets move into hidden_description, never the other way.
- Re-point dangling references at entities and places that EXIST in the canon below. Never invent a new named person, place, or faction.
- Keep each row's flavor, tone, and specificity - a flattening edit is a failure.
- Keep fields roughly their original length and NEVER leave a sentence unfinished.
- When a finding is about TIMING or PLACEMENT, use the "chapter" field: the chapter NUMBER the row belongs in (npc/loc rows may instead use "global" for an adventure-wide presence; objectives always take a number). Pair a move with whatever text edits the new placement needs.
- Editable fields per row type: obj# -> title, hidden_description, chapter; npc# -> description, chapter; loc# -> description, chapter; ing# -> text, reveals.
- When a finding is about an objective's COMPLETION PREDICATE (it references its own result, an unestablished flag, the wrong shape), patch "completion_predicates" with the corrected predicate AS A JSON STRING. Grammar: atoms {"flag": "<snake_case_milestone>", "eq": true} or {"event": "short past-tense marker"}, combined with {"any": [...]}/{"all": [...]}; NEVER "fact" atoms; at least one flag/event must be claimable; prefer an "any" honoring multiple resolutions. This decides WHEN players complete the objective - keep it achievable by ordinary play.
- When a finding says a spine entity NEVER APPEARS (registry coverage), fix it by CREATING that row: { "create": { "kind": "npc"|"location", "name": "<the exact name the finding cites>", "description": "1-3 sentences grounded in the canon below", "chapter": "<number>"|"global" }, "note": "..." }. Place it in the chapter where the story needs it; never rename it.
- A finding these operations cannot fix (merges, predicate changes) is simply left alone - it stays a warning for the creator.

Respond with ONLY a JSON object, no prose, in exactly this shape:
{ "edits": [ { "handle": "obj#2", "patch": { "<field>": "new text" }, "note": "one line: what changed and why" }, { "create": { "kind": "location", "name": "Boundary Stone", "description": "...", "chapter": "2" }, "note": "..." } ] }
At most ${EDIT_PLAN_CAP} entries; an edit entry has "handle"+"patch", a create entry has "create", never both. An empty edits list is a valid answer when nothing here is fixable.`

  const lines = (m: Map<string, string>) => [...m.entries()].map(([h, l]) => `${h}: ${l}`).join('\n')
  const user = `Findings to resolve:
${ctx.warnings.map((w) => `- [${w.handle}] ${w.message}`).join('\n')}

Current content of the flagged rows:
${ctx.rows.map((r) => `${r.handle} (${r.table}):\n${Object.entries(r.fields).map(([f, v]) => `  ${f}: ${v}`).join('\n')}`).join('\n')}

Chapters: ${ctx.chapters.map((c) => `${c.number}: ${c.title}`).join(' | ') || 'one-shot (single chapter)'}

Meta loop arc: ${ctx.metaLoopArc}

Established canon (edits must fit ALL of this):
Objectives:
${lines(ctx.digest.objectives)}

NPCs:
${lines(ctx.digest.npcs)}

Locations:
${lines(ctx.digest.locations)}

Ingredients:
${lines(ctx.digest.ingredients)}`

  return { system, user, maxTokens: 2500 }
}

export function parseStage7EditPlan(
  raw: string,
  knownHandles: Set<string>,
  chapterCount: number,
  /** Existing npc/location names (lowercased) - a create must never duplicate the cast. */
  existingNames: Set<string> = new Set(),
): ParseResult<Stage7Edit[]> {
  const extracted = extractJsonObject(raw)
  if (!extracted.ok) return extracted

  const c = new Check()
  const seen = new Set<string>()
  const edits: Stage7Edit[] = c.arr(extracted.data.edits ?? [], '$.edits', 0, EDIT_PLAN_CAP).flatMap((rawEdit, i): Stage7Edit[] => {
    const path = `$.edits[${i}]`
    const e = c.obj(rawEdit, path)
    if (e.create != null) {
      if (e.handle != null) {
        c.errors.push(`${path}: an entry is an edit (handle+patch) OR a create, never both`)
        return []
      }
      const cr = c.obj(e.create, `${path}.create`)
      const kind = c.oneOf(cr.kind, `${path}.create.kind`, ['npc', 'location'] as const)
      const name = c.str(cr.name, `${path}.create.name`)
      if (name && existingNames.has(name.trim().toLowerCase())) {
        c.errors.push(`${path}.create.name: "${name}" already exists - edit that row instead of creating a duplicate`)
        return []
      }
      const description = c.str(cr.description, `${path}.create.description`)
      if (description && looksCutOff(description)) {
        c.errors.push(`${path}.create.description: ends mid-thought - finish the sentence`)
        return []
      }
      const chapterText = typeof cr.chapter === 'number' ? String(cr.chapter) : typeof cr.chapter === 'string' ? cr.chapter.trim().toLowerCase() : ''
      const chapterNumber = Number(chapterText)
      let chapter = ''
      if (chapterText === 'global') chapter = 'global'
      else if (Number.isInteger(chapterNumber) && chapterNumber >= 1 && chapterNumber <= chapterCount) chapter = String(chapterNumber)
      else {
        c.errors.push(`${path}.create.chapter: expected a chapter number 1-${chapterCount} or "global", got "${String(cr.chapter)}"`)
        return []
      }
      const note = typeof e.note === 'string' ? e.note.slice(0, 200) : ''
      return [{ patch: {}, create: { kind, name: name.trim(), description: description.trim(), chapter }, note }]
    }
    const handle = c.str(e.handle, `${path}.handle`)
    const table = handleTable(handle)
    if (!table || !knownHandles.has(handle)) {
      c.errors.push(`${path}.handle: unknown handle "${handle}"`)
      return []
    }
    if (seen.has(handle)) {
      c.errors.push(`${path}.handle: "${handle}" appears twice - one entry per row, merge the patches`)
      return []
    }
    seen.add(handle)
    const allowed = new Set(REPAIRABLE_FIELDS[table] ?? [])
    const patch: Record<string, string> = {}
    const rawPatch = e.patch
    if (typeof rawPatch !== 'object' || rawPatch === null || Array.isArray(rawPatch)) {
      c.errors.push(`${path}.patch: expected an object of field -> new text`)
      return []
    }
    for (const [field, value] of Object.entries(rawPatch as Record<string, unknown>)) {
      if (!allowed.has(field)) {
        c.errors.push(`${path}.patch.${field}: not an editable field of ${table} (allowed: ${[...allowed].join(', ')})`)
        continue
      }
      if (field === 'chapter') {
        const text = typeof value === 'number' ? String(value) : typeof value === 'string' ? value.trim().toLowerCase() : ''
        const number = Number(text)
        if (text === 'global' && table !== 'objectives') {
          patch.chapter = 'global'
        } else if (Number.isInteger(number) && number >= 1 && number <= chapterCount) {
          patch.chapter = String(number)
        } else {
          c.errors.push(
            `${path}.patch.chapter: expected a chapter number 1-${chapterCount}${table !== 'objectives' ? ' or "global"' : ' (objectives always belong to a chapter)'}, got "${String(value)}"`,
          )
        }
        continue
      }
      if (typeof value !== 'string' || !value.trim()) {
        c.errors.push(`${path}.patch.${field}: expected non-empty replacement text`)
        continue
      }
      // Predicate patches are machine data: full structural validation (same gates stage 3
      // authors under), and the recognition judge remains the runtime net if semantics drift.
      if (field === 'completion_predicates') {
        let parsed: unknown
        try {
          parsed = JSON.parse(value)
        } catch {
          c.errors.push(`${path}.patch.completion_predicates: not valid JSON`)
          continue
        }
        const problems = validatePredicate(parsed, `${path}.patch.completion_predicates`)
        if (problems.length > 0) {
          c.errors.push(...problems)
          continue
        }
        if (containsFactAtom(parsed)) {
          c.errors.push(`${path}.patch.completion_predicates: "fact" atoms are not completable by live play - use flags or events`)
          continue
        }
        if (!hasClaimableAtom(parsed)) {
          c.errors.push(`${path}.patch.completion_predicates: has no claimable milestone - needs at least one {flag,eq:true} or {event}`)
          continue
        }
        patch[field] = JSON.stringify(parsed)
        continue
      }
      if (table === 'objectives' && field === 'title' && countWords(value) > OBJECTIVE_TITLE_MAX_WORDS) {
        c.errors.push(`${path}.patch.title: "${value}" is over ${OBJECTIVE_TITLE_MAX_WORDS} words - titles stay short and open`)
        continue
      }
      if (field !== 'title' && looksCutOff(value)) {
        c.errors.push(`${path}.patch.${field}: ends mid-thought ("...${value.trim().slice(-30)}") - finish the sentence`)
        continue
      }
      patch[field] = value.trim()
    }
    if (c.errors.length === 0 && Object.keys(patch).length === 0) {
      c.errors.push(`${path}.patch: no valid field was patched - edit something or drop this entry`)
    }
    const note = typeof e.note === 'string' ? e.note.slice(0, 200) : ''
    return [{ handle, patch, note }]
  })

  return c.result(edits)
}
