// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Stage 5 - Encounter Designer, per chapter: boss specs + candidate encounters per objective,
// Budget-Engine-validated against the expected party level (F04 SS2). Encounters are candidate
// routes, never gates - objectives still complete only via predicates.

import {
  crToXp, LETHAL_BUDGET_MULTIPLE, partyXpBudget, validateEncounterBudget,
  type BudgetVerdict, type DifficultyPreset,
} from '../budget.ts'
import { Check, extractJsonObject } from '../json.ts'
import type {
  BossUpdateDraft,
  ChapterSketch,
  EncounterDraft,
  ObjectiveDraft,
  ParseResult,
} from '../types.ts'

export interface Stage5Context {
  chapter: ChapterSketch
  chapterNumber: number
  objectives: ObjectiveDraft[]
  npcs: { key: string; name: string; role: 'npc' | 'boss' }[]
  locations: { key: string; name: string }[]
  difficultyPreset: DifficultyPreset
  partyLevel: number
  partySize: number
}

export interface Stage5Output {
  encounters: (EncounterDraft & { budget: BudgetVerdict | null })[]
  bossUpdates: BossUpdateDraft[]
  /** Deterministic repairs made here (trimmed encounters); surfaced as stage-5 guide_warnings. */
  warnings: string[]
}

/** SRD CR rungs, low to high - enough range for any party this pipeline builds guides for. */
const CR_LADDER = ['0', '1/8', '1/4', '1/2', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

export function buildStage5Prompt(ctx: Stage5Context): { system: string; user: string; maxTokens: number } {
  // Told the NUMBER, not an adjective. "an encounter the party can handle" produced 1800 XP
  // fights for a level-1 party against a 50 XP budget (36x, live 2026-07-22, multi-chapter
  // chapter 1) - the model has no way to know what "handle" costs unless the sum is on the page.
  const budgetXp = partyXpBudget(ctx.partyLevel, ctx.partySize, ctx.difficultyPreset)
  const lethalCeiling = budgetXp * LETHAL_BUDGET_MULTIPLE
  const usableCrs = CR_LADDER.filter((cr) => (crToXp(cr) ?? Infinity) <= lethalCeiling)
  const maxUsableCr = usableCrs[usableCrs.length - 1] ?? '0'
  const crExamples = usableCrs.slice(-4).map((cr) => `CR ${cr} = ${crToXp(cr)} XP`).join(', ') || 'CR 0 = 10 XP'
  const system = `You are the Encounter Designer for a tabletop RPG platform. For one chapter, design candidate encounters per objective, plus tactics and phases for any boss NPCs.

Rules:
- Encounters are CANDIDATE routes to an objective, not mandatory gates. Cover different pillars where sensible: "battle", "social", "environment".
- 1-2 encounters per objective. Reference objectives by number and locations/NPCs by their key.
- Battle encounters list enemies with SRD-style CR strings ("1/4", "3"). Party of ${ctx.partySize}, level ${ctx.partyLevel}, difficulty ${ctx.difficultyPreset}.
- BUDGET IS ARITHMETIC, NOT ATMOSPHERE. This party's encounter budget is ${budgetXp} XP. Total adjusted XP must land near it and MUST NOT exceed ${lethalCeiling}. The strongest single creature available to you is CR ${maxUsableCr} (${crToXp(maxUsableCr)} XP) - a higher CR cannot be fought at this level however well it suits the scene, and will be cut from the guide. Do the sum before you answer: ${crExamples}. More weak creatures reads as dangerous and stays winnable; one oversized monster is just a dead party.
- For each boss NPC give a tactics_profile (opening move, priorities, retreat condition) and 2-3 boss_phases (HP-threshold behavior shifts).

Respond with ONLY a JSON object, no prose, in exactly this shape:
{
  "encounters": [ { "type": "battle"|"social"|"environment", "objective_number": 1, "location_key": "loc:..." | null, "summary": "one-paragraph spec", "enemies": [ { "name": "...", "cr": "1/2", "count": 2 } ] } ],
  "boss_updates": [ { "npc_key": "npc:...", "tactics_profile": { "opening": "...", "priorities": "...", "retreat": "..." }, "boss_phases": [ { "threshold": 0.5, "behavior": "..." } ] } ]
}`

  const objectiveList = ctx.objectives.map((o, i) => `${i + 1}. ${o.title} - ${o.hiddenDescription}`).join('\n')
  const npcList = ctx.npcs.map((n) => `${n.key} (${n.name}${n.role === 'boss' ? ', BOSS' : ''})`).join(', ')
  const locationList = ctx.locations.map((l) => `${l.key} (${l.name})`).join(', ')

  const user = `Chapter ${ctx.chapterNumber}: ${ctx.chapter.title}
Arc summary: ${ctx.chapter.arcSummary}

Objectives:
${objectiveList}

NPCs: ${npcList || 'none'}
Locations: ${locationList || 'none'}`

  return { system, user, maxTokens: 3500 }
}

export function parseStage5(raw: string, ctx: Stage5Context): ParseResult<Stage5Output> {
  const extracted = extractJsonObject(raw)
  if (!extracted.ok) return extracted

  const c = new Check()
  const warnings: string[] = []
  const root = extracted.data
  const npcKeys = new Map(ctx.npcs.map((n) => [n.key, n.role]))
  const locationKeys = new Set(ctx.locations.map((l) => l.key))

  const encounters = c.arr(root.encounters, '$.encounters', 1, ctx.objectives.length * 2 + 2).map((raw, i) => {
    const path = `$.encounters[${i}]`
    const e = c.obj(raw, path)
    const type = c.oneOf(e.type, `${path}.type`, ['battle', 'social', 'environment'] as const)
    const objectiveIndex = c.int(e.objective_number, `${path}.objective_number`, 1, ctx.objectives.length) - 1

    let locationKey: string | null = null
    if (e.location_key != null) {
      locationKey = c.str(e.location_key, `${path}.location_key`)
      if (locationKey && !locationKeys.has(locationKey)) {
        c.errors.push(`${path}.location_key: unknown key "${locationKey}"`)
      }
    }

    let enemies: { name: string; cr: string; count: number }[] | undefined
    if (type === 'battle') {
      enemies = c.arr(e.enemies, `${path}.enemies`, 1, 20).map((raw, j) => {
        const en = c.obj(raw, `${path}.enemies[${j}]`)
        return {
          name: c.str(en.name, `${path}.enemies[${j}].name`),
          cr: c.str(en.cr, `${path}.enemies[${j}].cr`),
          count: c.int(en.count, `${path}.enemies[${j}].count`, 1, 30),
        }
      })
    }

    let budget =
      type === 'battle' && enemies
        ? validateEncounterBudget(enemies, ctx.partyLevel, ctx.partySize, ctx.difficultyPreset)
        : null
    // Wildly over-budget encounters get TRIMMED, not rejected. Rejecting them was a hard parse
    // error, and on a dungeon_crawl - where the combat pillar means the model keeps authoring
    // big fights - the repair loop exhausted every attempt and the WHOLE ADVENTURE failed to
    // generate (live 2026-07-21). A guaranteed TPK is bad; a guide that cannot be created is
    // worse. Dropping duplicate bodies is deterministic, keeps the authored cast, and always
    // terminates.
    if (enemies && budget && budget.adjustedXp > budget.xpBudget * LETHAL_BUDGET_MULTIPLE) {
      const before = budget.adjustedXp
      while (
        budget.adjustedXp > budget.xpBudget * LETHAL_BUDGET_MULTIPLE &&
        enemies.some((e) => e.count > 1)
      ) {
        const fattest = enemies.filter((e) => e.count > 1).sort((a, b) => b.count - a.count)[0]
        fattest.count -= 1
        budget = validateEncounterBudget(enemies, ctx.partyLevel, ctx.partySize, ctx.difficultyPreset)
      }
      // Dropping bodies cannot touch a single high-CR creature, so say what actually happened
      // rather than reporting a no-op as a fix ("trimmed from 700 to 700", live 2026-07-21).
      const stillOver = budget.adjustedXp > budget.xpBudget * LETHAL_BUDGET_MULTIPLE
      const scale = `(target ${budget.xpBudget} for ${ctx.partySize} level-${ctx.partyLevel})`
      warnings.push(
        before === budget.adjustedXp
          ? `${path}: ${budget.adjustedXp} adjusted XP ${scale} is over ${LETHAL_BUDGET_MULTIPLE}x ` +
            'and COULD NOT be trimmed - every enemy is already a single creature. Swap it for a ' +
            'weaker one by hand; as authored it is a near-certain party kill.'
          : `${path}: trimmed from ${before} to ${budget.adjustedXp} adjusted XP ${scale} by ` +
            `dropping duplicate bodies${stillOver ? ', but it is STILL over ' + LETHAL_BUDGET_MULTIPLE + 'x - the remaining single creatures are too strong to fight' : ''}.`,
      )
    }

    return {
      type,
      objectiveIndex,
      locationKey,
      spec: { summary: c.str(e.summary, `${path}.summary`), ...(enemies ? { enemies } : {}) },
      budget,
    }
  })

  // Tactics authored for a NON-boss are DROPPED, not fatal. This killed a whole adventure live
  // (escort, 2026-07-21: "npc:kaelen" is not a boss NPC, four retries, no guide) - and the repair
  // loop could never win it, because the model keeps offering tactics for the lieutenant it just
  // wrote a whole chapter about. Extra tactics for a supporting character are surplus, not
  // corruption; the boss coverage check below is what actually matters and still runs.
  const bossUpdates: BossUpdateDraft[] = c.arr(root.boss_updates ?? [], '$.boss_updates', 0, 10)
    .map((raw, i) => {
      const path = `$.boss_updates[${i}]`
      const b = c.obj(raw, path)
      const npcKey = c.str(b.npc_key, `${path}.npc_key`)
      if (npcKey && npcKeys.get(npcKey) !== 'boss') {
        warnings.push(`${path}: dropped tactics for "${npcKey}" - it is not a boss NPC.`)
        return null
      }
      return {
        npcKey,
        tacticsProfile: c.obj(b.tactics_profile, `${path}.tactics_profile`) as BossUpdateDraft['tacticsProfile'],
        bossPhases: c.arr(b.boss_phases, `${path}.boss_phases`, 1, 5) as BossUpdateDraft['bossPhases'],
      }
    })
    .filter((b): b is BossUpdateDraft => b !== null)

  const bossKeys = ctx.npcs.filter((n) => n.role === 'boss').map((n) => n.key)
  const updatedKeys = new Set(bossUpdates.map((b) => b.npcKey))
  for (const key of bossKeys) {
    if (!updatedKeys.has(key)) {
      c.errors.push(`$.boss_updates: missing entry for boss NPC "${key}"`)
    }
  }

  return c.result({ encounters, bossUpdates, warnings })
}
