// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Stage 3 - Story Director, per chapter: scenes -> ordered objectives (F04 SS2). Objectives are
// short open phrases (<= 6 words, enforced here AND by prompt), with hidden descriptions and
// structured completion predicates (SS4).

import { Check, countWords, extractJsonObject } from '../json.ts'
import { validatePredicate } from '../predicates.ts'
import type { ChapterSketch, MetaLoop, ObjectiveDraft, ParseResult, SceneSketch } from '../types.ts'

export interface Stage3Context {
  metaLoop: MetaLoop
  chapter: ChapterSketch
  chapterNumber: number
  scenes: SceneSketch[]
  /** 'one_shot' keeps the objective ladder short; longer forms may use the full range. */
  adventureType?: string
}

export const OBJECTIVE_TITLE_MAX_WORDS = 6
export const OBJECTIVES_PER_CHAPTER = { min: 1, max: 6 }

export function buildStage3Prompt(ctx: Stage3Context): { system: string; user: string; maxTokens: number } {
  const system = `You are the Story Director for a tabletop RPG platform. Turn a chapter's scene sketches into an ORDERED list of ${OBJECTIVES_PER_CHAPTER.min}-${OBJECTIVES_PER_CHAPTER.max} player-facing objectives.

Rules:
- Objective titles are AT MOST ${OBJECTIVE_TITLE_MAX_WORDS} words, phrased short and OPEN ("Defeat Volgarth", "Find the missing caravan") - they must not spoil twists or prescribe a method.
- hidden_description is DM-only: what this objective is really about, which scenes ground it, and what the party does not yet know. It exists to catch plot holes.
- completion_predicates is a JSON predicate over world state, NEVER a reference to a specific encounter. The live engine can ONLY satisfy atoms from this exact vocabulary - anything else never completes. Grammar:
  atom: {"flag": "<snake_case_milestone>", "eq": true} - a concrete accomplishment live play can recognize ("lantern_relit", "keeper_freed"). PREFER flags.
  atom: {"event": "<short past-tense marker>"} - e.g. "party entered the sunken crypt", "the ritual was interrupted".
  combinators: {"any": [<predicate>...]}, {"all": [<predicate>...]}
- NEVER use "fact" atoms - live play does not write them (NPC status is tracked by internal id, not by name).
- Prefer "any" combinators that honor multiple resolutions (kill OR ally OR outwit); keep any "all" chain to at most 2 atoms.${''}

${ctx.adventureType === 'one_shot' ? '- This is a ONE-SHOT adventure: author AT MOST 2-3 objectives, each completable within a few scenes of live play.\n' : ''}
Respond with ONLY a JSON object, no prose, in exactly this shape:
{ "objectives": [ { "title": "...", "hidden_description": "...", "completion_predicates": { ... } } ] }`

  const sceneList = ctx.scenes.map((s, i) => `Scene ${i + 1}: ${s.sketch}`).join('\n')
  const user = `Meta loop antagonist: ${ctx.metaLoop.antagonist}
Stakes: ${ctx.metaLoop.stakes}

Chapter ${ctx.chapterNumber}: ${ctx.chapter.title}
Arc summary: ${ctx.chapter.arcSummary}

Scene sketches:
${sceneList}`

  return { system, user, maxTokens: 3000 }
}

function containsFactAtom(predicate: unknown): boolean {
  if (typeof predicate !== 'object' || predicate === null || Array.isArray(predicate)) return false
  const p = predicate as Record<string, unknown>
  if (typeof p.fact === 'string') return true
  if (Array.isArray(p.any)) return p.any.some(containsFactAtom)
  if (Array.isArray(p.all)) return p.all.some(containsFactAtom)
  return false
}

export function parseStage3(raw: string): ParseResult<ObjectiveDraft[]> {
  const extracted = extractJsonObject(raw)
  if (!extracted.ok) return extracted

  const c = new Check()
  const objectives = c
    .arr(extracted.data.objectives, '$.objectives', OBJECTIVES_PER_CHAPTER.min, OBJECTIVES_PER_CHAPTER.max)
    .map((raw, i) => {
      const path = `$.objectives[${i}]`
      const o = c.obj(raw, path)
      const title = c.str(o.title, `${path}.title`)
      if (title && countWords(title) > OBJECTIVE_TITLE_MAX_WORDS) {
        c.errors.push(`${path}.title: "${title}" is over ${OBJECTIVE_TITLE_MAX_WORDS} words`)
      }
      const predicateErrors = validatePredicate(o.completion_predicates, `${path}.completion_predicates`)
      c.errors.push(...predicateErrors)
      if (predicateErrors.length === 0 && containsFactAtom(o.completion_predicates)) {
        // Live play can never write fact atoms (F14 milestone vocabulary is flags + events),
        // so a fact-based objective would be uncompletable - hard-fail into regeneration.
        c.errors.push(`${path}.completion_predicates: "fact" atoms are not completable by live play - use flags or events`)
      }
      return {
        title,
        hiddenDescription: c.str(o.hidden_description, `${path}.hidden_description`),
        completionPredicates: (o.completion_predicates ?? null) as ObjectiveDraft['completionPredicates'],
      }
    })

  return c.result(objectives)
}
