export type CampaignType = 'one-shot' | 'multi-chapter'

export type CampaignSummary = {
  id: number
  userId: string
  title: string | null
  plot: string
  model: string
  campaignType: CampaignType
  createdAt: string
}

export type TurnAuthor = 'dm' | 'player'

export type AudioChunk = {
  url: string
  isNewParagraph: boolean
}

export type Turn = {
  id: number
  turnIndex: number
  content: string
  author: TurnAuthor
  audioChunks: AudioChunk[] | null
  createdAt: string
}

// Realtime response payloads (each carries jobId + optional error, added by the backend)
export type CampaignsListedResponse = {
  jobId: string
  error?: string
  userId: string
  campaigns: CampaignSummary[]
}

export type CampaignFetchedResponse = {
  jobId: string
  error?: string
  campaignId: number
  campaign: CampaignSummary | null
}

export type TurnsListedResponse = {
  jobId: string
  error?: string
  campaignId: number
  turns: Turn[]
}

export type TurnDraftedResponse = {
  jobId: string
  error?: string
  campaignId: number
  content: string
}

export type BranchOptionsResponse = {
  jobId: string
  error?: string
  campaignId: number
  options: string[]
}

export type TurnPublishedAckResponse = {
  jobId: string
  error?: string
  campaignId: number
  turn: Turn
}

export type PublishTurnPayload = {
  campaignId: number
  content: string
  author: TurnAuthor
}

// Broadcasts on the campaign-live topic (no jobId — every subscriber receives them, not just a requester)
export type TurnPublishedEvent = {
  campaignId: number
  turn: Turn
}

// Pushed after a player's turn auto-triggers a fresh batch of branch-option suggestions on the
// backend (see make_handle_publish_turn) — distinct from BranchOptionsResponse, which is the ack
// for the DM's own manual generate-branch-options request.
export type BranchOptionsEvent = {
  campaignId: number
  options?: string[]
  error?: string
}

// Live narration audio, pushed while the DM is generating/deciding on the next turn (not tied to
// publish-turn's ack) — see use-live-narration-audio.ts. jobId scopes chunks to one generation
// request; narration-generation-started resets any in-progress playback before chunks arrive.
// hasTransition tells the frontend whether to expect a narration-transition-ended signal at all —
// narrate-plot has no transition step, so it sets this false (see make_handle_narrate_plot).
export type NarrationGenerationStartedEvent = {
  campaignId: number
  jobId: string
  hasTransition: boolean
}

export type NarrationAudioChunkEvent = {
  campaignId: number
  jobId: string
  kind: 'transition' | 'narration' | 'plot'
  sentenceIndex: number
  isNewParagraph: boolean
  audioUrl: string
}

// The transition narration's full text, broadcast once up front (before its audio chunks) so the
// turn feed can show it right away. totalChunks is how many "narration-audio-chunk" (kind
// "transition") broadcasts to expect for this jobId — lets the frontend know precisely when the
// transition is fully queued, rather than guessing from arrival order. See backend's
// _stream_transition_narration.
export type TransitionNarrationTextEvent = {
  campaignId: number
  jobId: string
  text: string
  totalChunks: number
}

// Fired once the transition-narration stream is done (success, failure, or zero chunks) — the
// signal that lets the frontend safely start playing buffered main-narration chunks after it,
// since the two streams are generated by concurrent backend tasks and can otherwise interleave.
export type NarrationTransitionEndedEvent = {
  campaignId: number
  jobId: string
}

// Ack for narrate-plot — only confirms the plot read-through started; the audio itself arrives
// as kind "plot" narration-audio-chunk broadcasts on campaign-live.
export type PlotNarrationStartedResponse = {
  jobId: string
  error?: string
  campaignId: number
}

// Pushed once a published turn's replayable audio finishes generating in the background (see
// backend/campaign/session_handlers.py's _persist_narration_audio) — turn-published fires before
// this is ready, so clients update the matching turn in place when this arrives.
export type TurnAudioReadyEvent = {
  campaignId: number
  turnId: number
  audioChunks: AudioChunk[]
}
