// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Minimal SRD encounter-budget math for Stage 5 validation (F04 SS2: "Budget-Engine-validated
// against expected party level"). The full Encounter Budget engine (allied NPCs as CR-weighted
// party members, difficulty re-scaling) lands with F09; this covers XP thresholds, CR->XP, and
// the encounter-size multiplier so generated encounters get a sanity verdict at guide time.

import type { AdventureSeed } from './types.ts'

/** SRD/DMG XP thresholds per character level: [easy, medium, hard, deadly]. */
const XP_THRESHOLDS: Record<number, [number, number, number, number]> = {
  1: [25, 50, 75, 100],
  2: [50, 100, 150, 200],
  3: [75, 150, 225, 400],
  4: [125, 250, 375, 500],
  5: [250, 500, 750, 1100],
  6: [300, 600, 900, 1400],
  7: [350, 750, 1100, 1700],
  8: [450, 900, 1400, 2100],
  9: [550, 1100, 1600, 2400],
  10: [600, 1200, 1900, 2800],
  11: [800, 1600, 2400, 3600],
  12: [1000, 2000, 3000, 4500],
  13: [1100, 2200, 3400, 5100],
  14: [1250, 2500, 3800, 5700],
  15: [1400, 2800, 4300, 6400],
  16: [1600, 3200, 4800, 7200],
  17: [2000, 3900, 5900, 8800],
  18: [2100, 4200, 6300, 9500],
  19: [2400, 4900, 7300, 10900],
  20: [2800, 5700, 8500, 12700],
}

const CR_XP: Record<string, number> = {
  '0': 10, '1/8': 25, '1/4': 50, '1/2': 100,
  '1': 200, '2': 450, '3': 700, '4': 1100, '5': 1800,
  '6': 2300, '7': 2900, '8': 3900, '9': 5000, '10': 5900,
  '11': 7200, '12': 8400, '13': 10000, '14': 11500, '15': 13000,
  '16': 15000, '17': 18000, '18': 20000, '19': 22000, '20': 25000,
  '21': 33000, '22': 41000, '23': 50000, '24': 62000, '25': 75000,
  '26': 90000, '27': 105000, '28': 120000, '29': 135000, '30': 155000,
}

export type DifficultyPreset = 'easy' | 'standard' | 'hard' | 'deadly'

const PRESET_INDEX: Record<DifficultyPreset, number> = { easy: 0, standard: 1, hard: 2, deadly: 3 }

export function crToXp(cr: string): number | null {
  return CR_XP[cr.trim()] ?? null
}

/** DMG encounter multiplier by total monster count. */
export function encounterMultiplier(monsterCount: number): number {
  if (monsterCount <= 1) return 1
  if (monsterCount === 2) return 1.5
  if (monsterCount <= 6) return 2
  if (monsterCount <= 10) return 2.5
  if (monsterCount <= 14) return 3
  return 4
}

export function partyXpBudget(partyLevel: number, partySize: number, preset: DifficultyPreset): number {
  const level = Math.min(Math.max(Math.round(partyLevel), 1), 20)
  return XP_THRESHOLDS[level][PRESET_INDEX[preset]] * Math.max(partySize, 1)
}

export interface BudgetVerdict {
  xpBudget: number
  rawXp: number
  adjustedXp: number
  unknownCrs: string[]
  verdict: 'under' | 'within' | 'over'
}

/**
 * Past this multiple of the target the fight is not "hard", it is unsurvivable, and shipping it
 * is worse than regenerating the stage. Stage 5 authored 3700 adjusted XP against a 150 XP
 * target for one level-3 PC (live 2026-07-20) and only warned.
 */
export const LETHAL_BUDGET_MULTIPLE = 3

/** "within" is a generous band (60%-140% of target) - outside it becomes an editor warning. */
export function validateEncounterBudget(
  enemies: { cr: string; count: number }[],
  partyLevel: number,
  partySize: number,
  preset: DifficultyPreset,
): BudgetVerdict {
  const xpBudget = partyXpBudget(partyLevel, partySize, preset)
  const unknownCrs: string[] = []
  let rawXp = 0
  let monsterCount = 0
  for (const enemy of enemies) {
    const xp = crToXp(enemy.cr)
    if (xp === null) {
      unknownCrs.push(enemy.cr)
      continue
    }
    rawXp += xp * enemy.count
    monsterCount += enemy.count
  }
  const adjustedXp = Math.round(rawXp * encounterMultiplier(monsterCount))
  const verdict: BudgetVerdict['verdict'] =
    adjustedXp < xpBudget * 0.6 ? 'under' : adjustedXp > xpBudget * 1.4 ? 'over' : 'within'
  return { xpBudget, rawXp, adjustedXp, unknownCrs, verdict }
}

/**
 * Guide-time party assumptions (flagged on the Phase 3b checkpoint): party level advances one
 * level per chapter from 1 (one-shots assume level 3); party size is the wizard range midpoint.
 */
export function expectedPartyLevel(seed: Pick<AdventureSeed, 'type'>, chapterIndex: number): number {
  if (seed.type === 'one_shot') return 3
  return Math.min(1 + chapterIndex, 20)
}

export function expectedPartySize(seed: Pick<AdventureSeed, 'minPlayers' | 'maxPlayers'>): number {
  return Math.max(1, Math.round((seed.minPlayers + seed.maxPlayers) / 2))
}
