// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Authored prose must be readable (2026-07-28).
//
// A generated guide shipped an ending whose climax_summary read "not the官方 story" - two Chinese
// characters spliced mid-sentence by the model. `climax_summary` is the guaranteed floor published
// verbatim when the live climax author fails, so that reaches the player exactly as written.
//
// Nothing checked. Every stage validator asks whether the SHAPE is right; none asks whether the
// text is in the language the adventure is written in.

/**
 * What a guide may legitimately contain: tab/newline, printable ASCII, Latin-1 Supplement and
 * Latin Extended-A (accented names - Fen Tollen is fine, so is Ysolde Ó Braonáin), and the
 * punctuation models actually reach for (curly quotes, dashes, ellipsis, euro sign).
 *
 * Deliberately a WHITELIST. A blacklist of scripts would need extending every time a new one
 * appeared, and the failure mode of missing one is shipping it to the player.
 */
const ALLOWED = /[\t\n\r\x20-\x7E -ɏ‐-›€]/

/** The distinct out-of-range characters in `text`, in first-seen order. Empty when clean. */
export function foreignCharacters(text: string): string[] {
  const seen: string[] = []
  for (const ch of String(text ?? '')) {
    if (ALLOWED.test(ch) || seen.includes(ch)) continue
    seen.push(ch)
  }
  return seen
}

/**
 * `text` with every out-of-range character removed, and the gap it leaves closed up.
 *
 * The last resort, for the paths that cannot ask again: the live climax publishes without an LLM
 * re-narration on purpose (so the ending always lands), and a narrator that reached for a Han
 * character twice will reach for one a third time. Deleting them is always readable - "*Drift彤*"
 * becomes "*Drift*", "The堵塞 channels" becomes "The channels" - and never worse than shipping them.
 */
export function stripForeign(text: string): string {
  const source = String(text ?? '')
  const bad = new Set(foreignCharacters(source))
  if (bad.size === 0) return source
  return [...source].filter((ch) => !bad.has(ch)).join('').replace(/[ \t]{2,}/g, ' ').trim()
}

/**
 * A validator error line for a stage reply, or null when the text is clean.
 *
 * Phrased as an instruction the model can act on: naming the characters is what lets the retry
 * find and remove them, rather than regenerating blind and rolling the same dice again.
 */
export function charsetError(text: string): string | null {
  const bad = foreignCharacters(text)
  if (bad.length === 0) return null
  const shown = bad.slice(0, 8).join(' ')
  return (
    `response contains characters outside the adventure's language (${shown}) - ` +
    'rewrite those words in English; do not transliterate or leave placeholders'
  )
}
