// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Guaranteed routes (overhaul Phase 4): every objective gets a code-authored rescue
// encounter whose success provably completes it.
//
// The invariant this buys: the spine can ALWAYS be advanced by something the party can play.
// Authored routes may be mis-planned, unstageable, or simply refused; the director's rung 4
// opens this instead. Its outcome map is generated from the objective's own predicate - never
// LLM-authored - so "does succeeding here actually complete the objective?" is a property we
// can prove in a test rather than hope for.
//
// The Encounter Designer may skin the fiction (template + twist + prose); the atoms are ours.

import { pickTemplate, templateGuidance } from '../story/templates-encounter.ts'
import type { TwistAxis } from '../story/templates-encounter.ts'
import { evaluatePredicate } from '../story/evaluate.ts'
import type { Json } from '../state/types.ts'

export interface GuaranteedRoute {
  kind: 'skill_challenge'
  template: string
  twist: TwistAxis
  label: string
  stakes: string
  guidance: string
  params: Record<string, unknown>
  /** The minimal atom set that satisfies the objective's predicate. Code-authored. */
  onSuccess: string[]
  onPartial: string[]
  onFailure: string[]
}

/**
 * The cheapest atom set that makes a predicate true.
 *
 * - `any`  -> the cheapest branch (fewest atoms): one route through is enough.
 * - `all`  -> every branch, unioned: all of them are required.
 * - flag/fact atoms with `eq: true` cost one atom; with `eq: false` they cost NONE, because an
 *   unset flag already reads false - "the deadline has not passed" is true until it passes.
 * - `event` atoms are always claimable.
 *
 * Returns null when no branch is satisfiable by writing atoms (an `eq` against a string or
 * number, say) - the caller then has no guaranteed route, which the Phase-5 reachability lint
 * flags as an authoring bug rather than paper over here.
 */
export function minimalSatisfyingAtoms(predicate: unknown): string[] | null {
  if (typeof predicate !== 'object' || predicate === null || Array.isArray(predicate)) return null
  const p = predicate as Record<string, unknown>

  if (Array.isArray(p.any)) {
    let best: string[] | null = null
    for (const branch of p.any) {
      const atoms = minimalSatisfyingAtoms(branch)
      if (atoms && (best === null || atoms.length < best.length)) best = atoms
    }
    return best
  }
  if (Array.isArray(p.all)) {
    const union: string[] = []
    for (const branch of p.all) {
      const atoms = minimalSatisfyingAtoms(branch)
      if (!atoms) return null // one unsatisfiable branch makes the whole chain unsatisfiable
      for (const a of atoms) if (!union.includes(a)) union.push(a)
    }
    return union
  }
  // `eq: false` is satisfied by ABSENCE (story/evaluate.ts): "the deadline has not passed" is
  // true until something passes it, so it costs zero atoms rather than being unsatisfiable.
  // Treating it as unsatisfiable is what left "Reach Oakhaven" with guaranteed_route: null and
  // no backstop at all (live 2026-07-23).
  if (typeof p.flag === 'string' && p.flag) return p.eq === true ? [p.flag] : p.eq === false ? [] : null
  if (typeof p.fact === 'string' && p.fact) return p.eq === true ? [p.fact] : p.eq === false ? [] : null
  if (typeof p.event === 'string' && p.event) return [p.event]
  return null
}

/** Proof helper (used by tests AND stage 3): do these atoms actually satisfy the predicate? */
export function atomsSatisfy(predicate: unknown, atoms: readonly string[]): boolean {
  const flags: Record<string, Json> = {}
  const facts: Record<string, Json> = {}
  for (const a of atoms) { flags[a] = true; facts[a] = true }
  return evaluatePredicate(predicate, { facts, flags, events: new Set(atoms) })
}

export interface GuaranteedRouteInput {
  objectiveId: string
  title: string
  hiddenDescription?: string
  completionPredicates: unknown
}

/**
 * Builds the rescue route for one objective. Deterministic: same objective -> same shape, so a
 * guide regeneration does not reshuffle every rescue, and different objectives differ.
 */
export function buildGuaranteedRoute(input: GuaranteedRouteInput): GuaranteedRoute | null {
  const atoms = minimalSatisfyingAtoms(input.completionPredicates)
  if (!atoms || atoms.length === 0) return null
  // Belt and braces: never ship a route that does not actually complete the thing.
  if (!atomsSatisfy(input.completionPredicates, atoms)) return null

  const template = pickTemplate('skill_challenge', input.objectiveId)
  if (!template) return null
  const twist = template.twists[Math.abs(hash(input.objectiveId)) % template.twists.length]

  return {
    kind: 'skill_challenge',
    template: template.key,
    twist,
    label: input.title,
    stakes: input.hiddenDescription?.trim()
      ? input.hiddenDescription.trim().slice(0, 200)
      : `Whether the party achieves: ${input.title}`,
    guidance: templateGuidance(template, twist),
    params: { ...template.params },
    onSuccess: atoms,
    // Partial/failure stay EMPTY on purpose. This is the safety net, not a giveaway: a rescue
    // that credited the objective on a partial would hand out the spine for showing up.
    onPartial: [],
    onFailure: [],
  }
}

function hash(seed: string): number {
  let h = 0
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) | 0
  return h
}
