// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Playability prover (2026-07-27): an exhaustive, deterministic, $0 model check of the authored
// graph, run at stage 8 before `guide_ready`.
//
// WHY THIS EXISTS. Every structural bug this month was found by a player, then fixed by adding a
// lint rule for that exact shape - dead-end transitions, free failures, non-escalating self-loops.
// A linter only catches what somebody already thought to write a rule about, so the cycle repeats
// with the next shape nobody predicted. This asks the question the rules were all approximating:
// walk EVERY path through the graph and check that it behaves.
//
// HOW IT CANNOT DRIFT. It drives the real `nextNode` rather than reimplementing navigation, so the
// graph is proved against the same function the session runs. A change to the navigator's
// fall-through, replay-blocking or rescue behaviour is immediately reflected here - a
// reimplementation would have silently gone stale the moment either side moved.
//
// WHAT IT NO LONGER ASKS (owner decision, 2026-07-27). It used to carry the atoms each outcome
// awards and test the objective's completion predicate at every terminal, because completion was
// INFERRED from an accumulated bag of flags. Objectives now resolve because a scene resolved -
// the Adventurers League model, where finishing Part 1 advances you whether it went well or
// badly - so "do the awarded atoms satisfy the predicate?" is not a question that exists. Two
// findings died with it (`objective_unwinnable`, `resolves_without_completing`), and with them
// the entire class of guide-killing failures where stage 3 authored a predicate stage 5 could not
// match. What remains is structural, and the state space lost a whole dimension.

import { nextNode } from '../story/navigate.ts'
import type { NavNode, NavTier } from '../story/navigate.ts'

/** Both outcome tiers a resolved node can produce (pass/fail, 2026-07-27). */
const TIERS: readonly NavTier[] = ['full', 'failed']

/** Hard ceiling on explored states - a runaway means a navigator bug, and hanging the guide
 *  pipeline is worse than reporting one. */
const MAX_STATES = 20_000

export type ProofCode =
  /** Every path through the graph ends in failure - the objective can be lost but never won. */
  | 'objective_never_completable'
  /** A reachable state from which the navigator returns neither a scene nor a resolution. */
  | 'objective_can_hang'
  /** Authored content no path can ever open. */
  | 'node_unreachable'
  /** The walk hit the state ceiling - report rather than hang. */
  | 'proof_incomplete'

export interface ProofFinding {
  code: ProofCode
  objectiveId: string
  message: string
  /** The outcome sequence that demonstrates it, e.g. ["n0:failed", "n1:failed"]. */
  path?: string[]
}

interface WalkState {
  fromKey: string | null
  tier: NavTier | null
  used: readonly string[]
  path: readonly string[]
}

const stateKey = (s: WalkState) => `${s.fromKey ?? '-'}|${s.tier ?? '-'}|${[...s.used].sort().join(',')}`

export interface ProveObjectiveInput {
  objectiveId: string
  title: string
  nodes: readonly NavNode[]
}

/**
 * Exhaustively walk one objective's graph and report every way it can fail a player.
 *
 * Two properties, both structural:
 *  - SOME path resolves `completed` (the objective is winnable at all), and
 *  - EVERY path terminates (the navigator always answers `open` or `resolve`).
 *
 * The second is guaranteed by `nextNode`'s own construction, which is exactly why it is worth
 * asserting here: this is the regression test that notices if that guarantee is ever broken.
 */
export function proveObjective(input: ProveObjectiveInput): ProofFinding[] {
  const { objectiveId, title, nodes } = input
  const findings: ProofFinding[] = []
  if (nodes.length === 0) return findings

  const reached = new Set<string>()
  const winnable = new Map<string, boolean>()
  const hangs: string[][] = []
  let states = 0
  let overflowed = false

  /** Can the party still WIN from here? Memoized; `used` only grows, so the state graph is a DAG. */
  function canWin(s: WalkState): boolean {
    const key = stateKey(s)
    const memo = winnable.get(key)
    if (memo !== undefined) return memo
    if (++states > MAX_STATES) { overflowed = true; return true }
    // Provisional false guards against re-entry; the state graph is acyclic, so this is only
    // reached if the navigator itself starts cycling - which the ceiling above catches.
    winnable.set(key, false)

    const decision = nextNode({
      nodes, fromKey: s.fromKey, tier: s.tier, usedKeys: [...s.used],
    })

    let ok = false
    if (decision.action === 'open') {
      reached.add(decision.node.key)
      for (const tier of TIERS) {
        const child: WalkState = {
          fromKey: decision.node.key,
          tier,
          used: [...s.used, decision.node.key],
          path: [...s.path, `${decision.node.key}:${tier}`],
        }
        if (canWin(child)) ok = true
      }
    } else if (decision.action === 'resolve') {
      // A `failed` resolution is a legitimate, story-advancing end - it just is not a win, so it
      // contributes nothing to `ok`. Only a path that can reach `completed` counts.
      ok = decision.outcome === 'completed'
    } else {
      // Unreachable while `nextNode` returns only `open` or `resolve`. Recorded rather than
      // assumed away: if a future navigator branch ever falls off the end, this is the finding
      // that says so instead of a player sitting in a scene that never continues.
      hangs.push([...s.path])
    }

    winnable.set(key, ok)
    return ok
  }

  const start: WalkState = { fromKey: null, tier: null, used: [], path: [] }
  const anyWin = canWin(start)

  if (overflowed) {
    findings.push({
      code: 'proof_incomplete', objectiveId,
      message: `"${title}": the playability walk exceeded ${MAX_STATES} states and was abandoned. ` +
        'That points at a navigator cycle, not a large graph - every objective here has at most a ' +
        'handful of nodes.',
    })
    return findings
  }

  if (!anyWin) {
    findings.push({
      code: 'objective_never_completable', objectiveId,
      message: `"${title}" can be lost but never won: no sequence of outcomes resolves it as ` +
        'completed. Every authored scene routes onward instead of finishing the objective, so the ' +
        'party can only ever be handed the failure ending of this thread.',
    })
  }

  for (const path of hangs) {
    findings.push({
      code: 'objective_can_hang', objectiveId,
      path,
      message: `"${title}" reaches a state after ${path.join(' -> ') || 'no scenes'} where ` +
        'navigation returns neither a scene to play nor a resolution. The party would be left with ' +
        'the objective open and nothing to do.',
    })
  }

  for (const node of nodes) {
    if (!reached.has(node.key)) {
      findings.push({
        code: 'node_unreachable', objectiveId,
        message: `Node "${node.key}" can never open: no sequence of outcomes reaches it. It is ` +
          'authored content the party will never see.',
      })
    }
  }

  return findings
}

export interface ProveGraphInput {
  objectives: readonly { id: string; title: string }[]
  nodes: readonly NavNode[]
}

/** Proves every objective that has authored nodes. Legacy objectives (no nodes) are skipped. */
export function proveGraph(input: ProveGraphInput): ProofFinding[] {
  return input.objectives.flatMap((o) =>
    proveObjective({
      objectiveId: o.id,
      title: o.title,
      nodes: input.nodes.filter((n) => n.objectiveId === o.id),
    }))
}
