import { useEffect, useRef, useState } from 'react'
import { subscribeToBroadcast } from '@/lib/realtime-channel'
import { CAMPAIGN_LIVE_TOPIC } from '../constants'
import type {
  NarrationAudioChunkEvent,
  NarrationGenerationStartedEvent,
  NarrationTransitionEndedEvent,
  TransitionNarrationTextEvent,
  TurnPublishedEvent,
} from '../types'
import { useAudioChunkPlayer } from './use-audio-chunk-player'

/** Plays narration audio live as it's generated: a transition-narration preview first (filling
 * the wait while the DM works), then the real narration sentences, autoplaying as soon as the
 * first chunk arrives. See backend/campaign/session_handlers.py's make_handle_generate_turn.
 *
 * Transition and main-narration audio are generated by two concurrent backend tasks, so their
 * narration-audio-chunk broadcasts can arrive interleaved rather than transition-then-main. Main
 * chunks (kind "narration"/"plot") are held in `pendingMainRef` until the transition is known to
 * be fully queued, which is determined by counting: transition-narration-text announces
 * `totalChunks` up front, and once that many "transition" chunks have arrived, the buffered main
 * chunks are flushed in order. narration-transition-ended is a fallback for jobs that never reach
 * the promised count (TTS error mid-stream) so playback can't get stuck waiting forever. Jobs with
 * no transition at all (e.g. plot narration, see hasTransition) skip buffering entirely.
 */
export function useLiveNarrationAudio(campaignId: number) {
  const { audioRef, enqueue, reset } = useAudioChunkPlayer()
  const [transitionText, setTransitionText] = useState<string | null>(null)

  const currentJobIdRef = useRef<string | null>(null)
  const transitionDoneRef = useRef(true)
  const expectedTransitionChunksRef = useRef<number | null>(null)
  const receivedTransitionChunksRef = useRef(0)
  const pendingMainRef = useRef<NarrationAudioChunkEvent[]>([])

  useEffect(() => {
    const flushPendingMain = () => {
      transitionDoneRef.current = true
      pendingMainRef.current.forEach((chunk) =>
        enqueue({ url: chunk.audioUrl, isNewParagraph: chunk.isNewParagraph }),
      )
      pendingMainRef.current = []
    }

    const unsubscribeStarted = subscribeToBroadcast<NarrationGenerationStartedEvent>(
      CAMPAIGN_LIVE_TOPIC,
      'narration-generation-started',
      (event) => {
        if (event.campaignId !== campaignId) return
        reset()
        setTransitionText(null)
        currentJobIdRef.current = event.jobId
        transitionDoneRef.current = !event.hasTransition
        expectedTransitionChunksRef.current = null
        receivedTransitionChunksRef.current = 0
        pendingMainRef.current = []
      },
    )

    const unsubscribeTransitionText = subscribeToBroadcast<TransitionNarrationTextEvent>(
      CAMPAIGN_LIVE_TOPIC,
      'transition-narration-text',
      (event) => {
        if (event.campaignId !== campaignId || event.jobId !== currentJobIdRef.current) return
        setTransitionText(event.text)
        expectedTransitionChunksRef.current = event.totalChunks
        // No audio coming at all (TTS disabled or empty text) — nothing to wait on.
        if (event.totalChunks === 0) flushPendingMain()
      },
    )

    const unsubscribeTransitionEnded = subscribeToBroadcast<NarrationTransitionEndedEvent>(
      CAMPAIGN_LIVE_TOPIC,
      'narration-transition-ended',
      (event) => {
        if (event.campaignId !== campaignId || event.jobId !== currentJobIdRef.current) return
        if (!transitionDoneRef.current) flushPendingMain()
      },
    )

    const unsubscribeChunk = subscribeToBroadcast<NarrationAudioChunkEvent>(
      CAMPAIGN_LIVE_TOPIC,
      'narration-audio-chunk',
      (event) => {
        if (event.campaignId !== campaignId) return

        if (event.kind === 'transition') {
          enqueue({ url: event.audioUrl, isNewParagraph: event.isNewParagraph })
          receivedTransitionChunksRef.current += 1
          if (
            expectedTransitionChunksRef.current !== null &&
            receivedTransitionChunksRef.current >= expectedTransitionChunksRef.current
          ) {
            flushPendingMain()
          }
          return
        }

        if (!transitionDoneRef.current) {
          pendingMainRef.current.push(event)
          return
        }
        enqueue({ url: event.audioUrl, isNewParagraph: event.isNewParagraph })
      },
    )

    // The real turn is published once its narration is fully drafted — the transition preview's
    // job is done at that point, so drop its text rather than leaving stale filler in the feed.
    const unsubscribePublished = subscribeToBroadcast<TurnPublishedEvent>(
      CAMPAIGN_LIVE_TOPIC,
      'turn-published',
      (event) => {
        if (event.campaignId === campaignId) setTransitionText(null)
      },
    )

    return () => {
      unsubscribeStarted()
      unsubscribeTransitionText()
      unsubscribeTransitionEnded()
      unsubscribeChunk()
      unsubscribePublished()
      reset()
    }
  }, [campaignId, enqueue, reset])

  return { audioRef, transitionText }
}
