// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Random-encounter danger math (encounter-states Slice 6): pure scoring, thresholds, and
// weighted table picks. The server rolls with a seeded RNG at transition points only
// (travel, day advance, encounter failure, loud actions) and logs every roll - the world
// pushes back, legibly.

import type { Json } from '../state/types.ts'
import type { Rng } from './rng.ts'

export interface EncounterTableEntry {
  weight: number
  kind: 'skill_challenge' | 'combat'
  label: string
  params: Json
}

export interface DangerModifiers {
  night: boolean
  /** Antagonist plan step reached (0 = plan untouched). */
  antagonistStep: number
  /** Recent loud-action events. */
  noiseEvents: number
}

export const DANGER_MAX = 10

/** Base 0-5 authored per location; the world's state layers on top. Clamped 0-10. */
export function dangerScore(base: number, mods: DangerModifiers): number {
  const authored = Math.max(0, Math.min(5, Math.round(base)))
  const score = authored + (mods.night ? 1 : 0) + Math.min(2, Math.max(0, mods.antagonistStep)) +
    Math.min(2, Math.max(0, mods.noiseEvents))
  return Math.max(0, Math.min(DANGER_MAX, score))
}

/** Spawn chance in percent: 8 points per danger, capped at 60 - never a certainty. */
export function spawnThreshold(score: number): number {
  return Math.min(60, Math.max(0, score) * 8)
}

export interface SpawnRoll {
  roll: number
  threshold: number
  spawned: boolean
}

export function rollSpawn(rng: Rng, score: number): SpawnRoll {
  const threshold = spawnThreshold(score)
  const roll = Math.floor(rng() * 100)
  return { roll, threshold, spawned: roll < threshold }
}

export function pickWeighted(rng: Rng, entries: EncounterTableEntry[]): EncounterTableEntry | null {
  const usable = entries.filter((e) => e.weight > 0)
  if (usable.length === 0) return null
  const total = usable.reduce((sum, e) => sum + e.weight, 0)
  let roll = rng() * total
  for (const entry of usable) {
    roll -= entry.weight
    if (roll < 0) return entry
  }
  return usable[usable.length - 1]
}

export function parseEncounterTable(raw: Json | null): EncounterTableEntry[] {
  if (!Array.isArray(raw)) return []
  return raw.flatMap((e): EncounterTableEntry[] => {
    if (typeof e !== 'object' || e === null || Array.isArray(e)) return []
    const entry = e as { [key: string]: Json }
    const kind = entry.kind === 'combat' ? 'combat' : entry.kind === 'skill_challenge' ? 'skill_challenge' : null
    if (!kind || typeof entry.label !== 'string' || !entry.label.trim()) return []
    const weight = typeof entry.weight === 'number' && entry.weight > 0 ? entry.weight : 1
    return [{ weight, kind, label: entry.label.trim(), params: entry.params ?? {} }]
  }).slice(0, 8)
}

/** Generated fallback when a location has no authored table (all pre-slice guides). */
export function fallbackEncounterTable(locationName: string): EncounterTableEntry[] {
  const at = locationName ? ` near ${locationName}` : ''
  return [
    {
      weight: 3,
      kind: 'skill_challenge',
      label: `Sudden hazard${at}`,
      params: { needed_successes: 1, max_failures: 2, suggested_skills: ['athletics', 'perception'] },
    },
    { weight: 2, kind: 'combat', label: `Ambush${at}` },
    {
      weight: 1,
      kind: 'skill_challenge',
      label: `Something stalks the party${at}`,
      params: { needed_successes: 2, max_failures: 2, suggested_skills: ['stealth', 'survival'] },
    },
  ].map((e) => ({ ...e, params: e.params ?? {} })) as EncounterTableEntry[]
}
