// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// Skill-challenge engine (encounter-states Slice 2): X successes before Y failures with
// tiered outcomes. Pure counting - the server feeds it adjudicated attempt results and acts
// on the returned status. Teamwork is participation, not turn order: the full tier requires
// every active PC to have made at least one attempt, and leaning on the same skill again
// escalates its DC.

export type ChallengeStatus = 'ongoing' | 'full' | 'failed'

export interface SkillChallengeState {
  neededSuccesses: number
  maxFailures: number
  /** Approaches the spec telegraphs; attempts are never restricted to them. */
  suggestedSkills: string[]
  /** Attempts per skill so far - drives DC escalation on repeats. */
  perSkillUses: Record<string, number>
  successes: number
  failures: number
  /** Attempts per PC - the participation ledger (mirrored to EncounterState.contributions). */
  contributions: Record<string, number>
  /** Party roster at open time; the full tier requires each to attempt at least once. */
  activePcIds: string[]
}

export interface ChallengeSeed {
  neededSuccesses: number
  maxFailures: number
  suggestedSkills: string[]
  activePcIds: string[]
}

const clampCount = (n: number, min: number, max: number) => Math.max(min, Math.min(max, Math.round(n)))

export function newSkillChallenge(seed: ChallengeSeed): SkillChallengeState {
  return {
    neededSuccesses: clampCount(seed.neededSuccesses, 1, 10),
    maxFailures: clampCount(seed.maxFailures, 1, 10),
    suggestedSkills: seed.suggestedSkills,
    perSkillUses: {},
    successes: 0,
    failures: 0,
    contributions: {},
    activePcIds: seed.activePcIds,
  }
}

/** +2 per prior use of the same skill - variety beats hammering one approach. */
export const DC_ESCALATION_PER_REPEAT = 2

export function escalatedDc(baseDc: number, usesOfSkill: number): number {
  return baseDc + DC_ESCALATION_PER_REPEAT * Math.max(0, usesOfSkill)
}

export interface AttemptOutcome {
  state: SkillChallengeState
  status: ChallengeStatus
}

/**
 * Records one adjudicated attempt. Terminal statuses, encoded precisely:
 * - `failed`: failures reached maxFailures.
 * - `full`: successes reached neededSuccesses.
 * Attempts after a terminal state are a caller bug; the state still counts them.
 */
export function recordAttempt(
  state: SkillChallengeState,
  characterId: string,
  skill: string,
  success: boolean,
): AttemptOutcome {
  const key = skill.toLowerCase()
  const next: SkillChallengeState = {
    ...state,
    perSkillUses: { ...state.perSkillUses, [key]: (state.perSkillUses[key] ?? 0) + 1 },
    successes: state.successes + (success ? 1 : 0),
    failures: state.failures + (success ? 0 : 1),
    contributions: { ...state.contributions, [characterId]: (state.contributions[characterId] ?? 0) + 1 },
  }
  return { state: next, status: challengeStatus(next) }
}

/**
 * Did at least half the active party pitch in? The SRD group-check standard (`groupOutcome` in
 * checks.ts), applied to participation.
 *
 * REPORTING ONLY - this does not gate resolution. See `challengeStatus`.
 */
export function majorityContributed(state: SkillChallengeState): boolean {
  if (state.activePcIds.length === 0) return true
  const contributors = state.activePcIds.filter((id) => (state.contributions[id] ?? 0) > 0).length
  return contributors >= Math.ceil(state.activePcIds.length / 2)
}

/**
 * Pass or fail - there is no middle tier (owner decision, 2026-07-27).
 *
 * `partial` used to fire whenever ANY active PC had not attempted, or the party scraped through at
 * the failure edge. Both downgraded a genuine success, and the tier they downgraded into was worse
 * than either outcome it sat between: the guide authored `on_partial` zero times out of eight
 * nodes, and the navigator had no partial edges at all, so a partial credited nothing and routed
 * the party onward as though they had lost. A tier nobody authors for is not a middle ground, it
 * is a hole.
 *
 * Participation does NOT gate the result, and the attempt to make it do so is instructive. Holding
 * the challenge `ongoing` until a majority pitched in looked like a softer version of the old rule,
 * but failures were the only way out of that hold - and a party that keeps SUCCEEDING never
 * accumulates any. The $0 suite caught it immediately: one PC passed a 1-success challenge four
 * times over while the other never acted, the scene refused to close, and the encounter it had
 * interrupted was never restored. A gate whose only exit is another player choosing to act can
 * block a table indefinitely, which is precisely why the original design made non-participation a
 * soft downgrade rather than a wall. With no middle tier left to downgrade INTO, the gate has
 * nowhere safe to land, so it goes.
 *
 * Spotlight balance stays where it already worked: the Variety Manager flags a dominating player
 * (`SPOTLIGHT_SHARE`) and the planner opens for the others. That nudges the table without ever
 * holding a scene hostage.
 */
export function challengeStatus(state: SkillChallengeState): ChallengeStatus {
  if (state.failures >= state.maxFailures) return 'failed'
  return state.successes >= state.neededSuccesses ? 'full' : 'ongoing'
}
