// GENERATED by scripts/sync-guide-shared.mjs - DO NOT EDIT.
// Canonical source: packages/rules/src/. Edit there, then re-run the script.

// F07/F10 live-orchestration contracts. Plain data only - these modules run under Vitest, the
// frontend bundle, and the Deno edge runtime (relative imports with explicit .ts extensions,
// no platform APIs). The LLM-facing shapes here are the *validated* forms: raw model output
// goes through the parsers in adjudication.ts, which clamp and reject before anything typed
// as these leaves the boundary.

import type { Json } from '../state/types.ts'

export type IntentKind = 'say' | 'do' | 'roll' | 'move' | 'attack' | 'cast' | 'use_item' | 'dm_command'

/** Client -> server intent envelope (F07 SS3.1). */
export interface IntentEnvelope {
  intentId: string
  actorCharacterId: string
  kind: IntentKind
  text: string
  /** NPC the utterance is aimed at (say); token/target for combat kinds (Phase 7). */
  targetId: string | null
  /** Explicit skill for `roll` - what makes it fast-path. */
  skill: string | null
  sceneVersion: number
}

export type IntentRoute =
  | 'fast_path' // move / explicit roll / combat verbs: engines only, never an LLM
  | 'dialogue' // say with NPCs staged -> F10 pipeline
  | 'chat' // say with no NPC in scene: player-to-player flavor, free (F10 SS8)
  | 'adjudicate' // free-text do -> Adjudicator
  | 'dm_command'

export type AdvDis = 'none' | 'advantage' | 'disadvantage'

export interface RequiresAssist {
  skill: string
  effect: 'enable' | 'bonus'
}

/** Validated check spec (F07 SS3.3) - DC already clamped to bounds. */
export interface CheckSpec {
  skill: string
  /** 1-3 applicable skills the player may pick from ("Does Investigation apply?" "Sure!");
   *  always non-empty, `skill` first. */
  skillOptions: string[]
  dc: number
  advDis: AdvDis
  rationale: string
  group: boolean
  requiresAssist: RequiresAssist | null
}

export interface AdjudicationResolution {
  type: 'auto_success' | 'auto_fail' | 'check'
  check: CheckSpec | null
  consequencesHint: string
}

export interface AdjudicationOutput {
  interpretation: string
  resolution: AdjudicationResolution
  /** `talk` = the input addresses the DM (a question, table talk) rather than attempting anything. */
  flags: { impossible: boolean; needsDm: boolean; talk: boolean }
}

export interface CheckResult {
  rolls: number[]
  d20: number
  modifier: number
  total: number
  dc: number
  success: boolean
  /** total - dc; degree-of-success inputs (openings, braided modifiers). */
  margin: number
}

/** Utterance classification for the social pipeline (F10 SS3.2). */
export type SocialMagnitude = 'trivial' | 'reasonable' | 'costly' | 'against_nature'

export type SocialClassification =
  | { kind: 'conversation' }
  | { kind: 'influence'; skill: 'persuasion' | 'deception' | 'intimidation'; magnitude: SocialMagnitude }
  | { kind: 'insight'; skill: 'insight' }
  /** A physical action or maneuver, not talk - the caller re-routes it out of the NPC pipeline. */
  | { kind: 'action' }
  /** A question about the world, aimed at the DM - answered as narration, not NPC speech. */
  | { kind: 'ask_dm' }

/** A social opening (F10 SS3.7): PC A's insight success eases a linked influence attempt by PC B. */
export interface OpeningView {
  id: string
  unlockedBy: string
  npcId: string
  skill: string
  dcMod: -2 | -4
  hint: string
}

/** Pending table prompt, rendered from dialogue.pending (one at a time - rulings block, F07 SS4). */
export type PendingPrompt =
  | {
      kind: 'check'
      id: string
      actorCharacterId: string
      skill: string
      /** Player-pickable skills (1-3, `skill` first); absent = the single skill. */
      skillOptions?: string[]
      advDis: AdvDis
      reason: string
      deadline: string
    }
  | {
      kind: 'group'
      id: string
      skill: string
      reason: string
      memberCharacterIds: string[]
      rolled: { characterId: string; total: number; success: boolean }[]
      deadline: string
    }
  | {
      kind: 'assist'
      id: string
      primaryCharacterId: string
      primarySkill: string
      assistSkill: string
      effect: 'enable' | 'bonus'
      reason: string
      deadline: string
    }

export interface DispositionDelta {
  value: number
  reason: string
}

export type NpcProposedAction =
  | { type: 'join_combat' }
  | { type: 'leave' }
  | { type: 'give_item'; item: string }
  | { type: 'canonize_theory'; theory: string }

/** Validated NPC Agent reply (F10 SS3.3) - deltas clamped, reveals still unfiltered here. */
export interface NpcAgentOutput {
  dialogue: string
  tone: string
  addressPc: string | null
  reveals: string[]
  opening: { unlockedBy: string; skill: string } | null
  dispositionDelta: DispositionDelta
  proposedActions: NpcProposedAction[]
}

/** Row shape shared with the proposals table (F07 SS4). */
export type ProposalStatus = 'pending' | 'accepted' | 'edited' | 'rejected' | 'expired' | 'auto_applied'

export interface ProposalView {
  id: string
  type: string
  status: ProposalStatus
  summary: string
  createdAt: string
}

/** Ingredient fields the reveal gate needs (subset of the ingredients row). */
export interface RevealCandidate {
  id: string
  npcId: string | null
  locationId: string | null
  condition: string | null
  discovered: boolean
  boundCharacterId: string | null
  anyPc: boolean
}

export type { Json }
